### ISSUE TITLE
Activating extension 'lextudio.restructuredtext' failed: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#101]
**Environment**
- Extension version: 71.0.0
- Visual Studio Code version: 1.26.1
- Operating System version: Windows 10.0.17134.228 x64
- Python version: 3.7.0
- sphinx version: 1.7.8

**Expected behavior**
The extension should work.

**Actual behavior**
It fails to activate with the error:
```
Activating extension 'lextudio.restructuredtext' failed: Cannot find module 'mkdirp'
```

Missing dependency in the published vsix I guess...

**Detailed Steps to reproduce the problem**
1. Install the extension.
2. Try to use anything it provides.
3. Check the developer console.

**Comment by lextm** [comment]
Something was wrong with `vsce` right now and broke the published package. Will have to wait till a solution is found.

**Comment by lextm** [comment]
Thanks for the prompt report. Please update to release 72.0.0, where I manually patched the installer.

Will close this issue once `vsce` fixes their bug.

**Comment by lextm** [comment]
https://github.com/Microsoft/vscode-vsce/issues/283

**Comment by lextm** [comment]
Seems to be a mistake when deduplicating `vscode` in `package.json`. Fixed.
