### ISSUE TITLE
Preview not refreshing automatically with restructuredtext.updateOnTextChanged: true

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#102]
**Environment**
- Extension version: 74.0.0
- Visual Studio Code version: 1.26.1
- Operating System version: Windows 10.0.17134.228 x64
- Python version: 3.7.0
- sphinx version: 1.7.8

**Expected behavior**
With `restructuredtext.updateOnTextChanged` set to `"true"`, the preview should refresh automatically. (The setting is a string...? The configuration is JSON schema, which means you can define it as `"type": "boolean"`)

**Actual behavior**
It doesn't.

**Detailed Steps to reproduce the problem**
1. Create a any Sphinx project and open it with VS Code with the extension installed.
2. Open a preview to the side.
3. Change the document & save.
4. The preview doesn't refresh.

**Analysis**
The extension registers for text change events here:

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/e0df7ec06da1b8ea9e8fe5e1eb107e519893c06a/src/extension.ts#L82-L89

(`onDidChangeTextDocument` fires for text edits such as the user typing in a document, but the Sphinx preview uses `sphinx-build`/`rst2html` which is only going to notice files on disk and not dirty unsaved files in the editor. This should probably be using `onDidSaveTextDocument` than. Possibly renaming the setting for clarity?)

And this fires this code:

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/fb3ff8a9e726114329a644461058c9a475d91356/src/features/rstDocumentContent.ts#L124-L136

But no one seems to be registering for the event, so it does nothing.

**EDIT:** VS Code itself is registering for the event. And the extensions seems to also register for `onDidSaveTextDocument`:

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/e0df7ec06da1b8ea9e8fe5e1eb107e519893c06a/src/extension.ts#L76-L80

Which can't be controlled by a setting...

The real issue is this:
```
[warning] Provider for scheme 'restructuredtext' is firing event for schema 'file' which will be IGNORED
```

**Comment by qiujiangkun** [comment]
I'm facing the same problem. Has it been fixed?
I think we can update preview for a specific period(like most markdown editor), rathan than just load changed file from disks.
