### ISSUE TITLE
Live preview launches new Sphinx/Python on every keypress

### ISSUE THREAD

**Issue by larsch** [vscode-restructuredtext/vscode-restructuredtext#104]
**Environment**
- [ ] Extension version: 77.0.0
- [ ] Visual Studio Code version: 1.271.
- [ ] Operating System version: Windows 10, Version 1803
- [ ] Python version: Python 3.6.4 :: Anaconda, Inc.
- [ ] sphinx version: sphinx-build 1.8.0
- [ ] A sample of conf.py or its important fragments:

**Actual behavior**

If the preview is open, a new instance of python is launched on every single keypress (`python  -m sphinx -b html . "x:\work\....`), bringing my PC to it's knees (CPU & RAM usage).

**Detailed Steps to reproduce the problem**

Open .RST, open Live Preview, begin typing...

**Comment by larsch** [comment]
Thanks for the tips. Autosave is already completely off. My X: is a network share, but mounted to a local virtual machine. Python is installed locally.

The live preview doesn't actually update until i save manually, but still many Python instances are launched while I edit...

It would be nice if, at least, the update wouldn't trigger until the previous update had completed. I saw as many as 20 concurrent python instances running...

**Comment by chrisjsewell** [comment]
Yeh I second this being 'fixed':

1. You shouldn't need to turn off auto-save to turn off auto updating. If I set `restructuredtext.updateOnTextChanged` to `false` I would expect auto updating to be turned off
2. The maximum number of parallel updates running should be able to be controlled via a settings. At present, unless I set `restructuredtext.updateDelay` to around 100000, it consistently crashes vs code
3. Minor one, but why is the value of `restructuredtext.updateOnTextChanged` a string and not a boolean?

**Comment by memeplex** [comment]
I have set `restructuredtext.updateOnTextChanged` to `false` and the preview is still constantly updated (every 300 ms). Changing `restructuredtext.updateDelay` works as expected.

I'm also surprised by the fact that  `restructuredtext.updateOnTextChanged` is not a boolean.

Also, grepping for that setting gives just:

```
~/./e/lextudio.restructuredtext-114.0.0:: grep -r updateOnTextChanged *
package.json:				"restructuredtext.updateOnTextChanged": {
```
so it seems to be doing nothing at all (?).

**Comment by lextm** [comment]
No longer valid after switching to esbonio.
