### ISSUE TITLE
restructuredText.confPath setting expanded in workspace settings

### ISSUE THREAD

**Issue by pgerell** [vscode-restructuredtext/vscode-restructuredtext#107]
**Environment**
- [x] Extension version: 78.0.0
- [x] Visual Studio Code version: 1.27.2
- [x] Operating System version: Windows 10 Pro version 1803
- [x] Python version: 3.6.5
- [x] sphinx version: 1.8

I have my documentation in a subfolder of the workspace called docs.
Thus I have added `"restructuredtext.confPath": "${workspaceFolder}/docs"` to the workspace settings.
However the extension replaces this with the actual path when generating a preview.
`"restructuredtext.confPath": "c:\\Users\\peter\\project\\docs"`
Obviously it is not a good idea to have non-portable paths in the workspace settings as these are committed to git.

**Comment by lextm** [comment]
Such settings should not be checked in to Git or other source control system, as they are not guaranteed to be machine independent (like where you install Python, and what the actual files locate). It is a rule not only for this extension, but other extensions as well.

I agree it is possible to force this extension use some special path, but I have no plan to work on that right now.

Pull requests are welcome.

**Comment by pgerell** [comment]
I agree about not checking in machine dependent paths to source control.
That is why I try to use ${workspaceFolder} as part of the path
I just wish the extension respected my setting instead of replacing it with an absolute path.
Settings not to be checked in I keep in the user settings and not in the workspace settings.
I notice that this extension itself has the settings checked in.

My proposal is:

1. Accept the setting as is and do not change it if already set.
2. Only perform the recursive search for conf.py if the setting is missing.
3. Encode path name to the selected conf.py using ${workspaceFolder} when writing path to settings.json.

**Comment by lextm** [comment]
I am not sure how you wrote the proposal, as I can only see point 3 is a useful tip on what might fix the issue. The other two conflict with the current code base if you check carefully.

Like I said above, pull requests are welcome. If you can implement point 3, then I will review and accept it.

**Comment by pgerell** [comment]
I sent a pull request implementing proposal 1.
It seems to work, but maybe I have missed some important use case.
My change also resolves another annoying problem:
If confPath was configured but did not point to an existing file, the setting was restored to the incorrect value every time the user tried to correct it.
The only way to correct the value was to disable the extension and then modify the setting or to exit vscode and modify the json file using another editor.

**Comment by lextm** [comment]
I commented above that **only 3 might work**.

I cannot accept the pull request, as other part of this extension depends on such before your modification.

**Comment by lextm** [comment]
When a folder contains multiple `conf.py` files, this extension relies on the value stored in `confPath` to generate preview pages. Thus, the setting is written with the user selected value from a prompt.

That's exactly why I say 1 and 2 might not work, as they break the current feature.

**Comment by pgerell** [comment]
I hadn't noticed that clicking on the status bar did reset the setting and prompting the user for a new choice.
When I have time I will continue looking deeper into this. As have have limited experience (actually none at all) of typescript/javascript this make take some time.

Maybe the user's choice could be stored in the workspaceState of the ExecutionContext instead of the settings.json.

**Comment by lextm** [comment]
The user's choice must be persistent, just like the active project in a Visual Studio solution. That's why it is saved to `settings.json` immediately after the selection.

**Comment by alexdresko** [comment]
From https://stackoverflow.com/a/32979933/250094:

> Check in the .vscode folder if you want to share settings, task configuration and debug configuration with the team. I think generally it makes sense to share settings (e.g. whitespace vs tabs) with the team if you want to enforce settings in a team. **We in the VS Code team share debug and task specific settings as well because we want our team to have the same set of debug targets and task targets for VS Code**.

**Comment by lextm** [comment]
@alexdresko the example in that post is invalid, as spaces/tabs should go via EditorConfig, not settings.json.

**Comment by Yajo** [comment]
This bug still happens. The config is written to team-shared config file, which is absurd because each computer can have docutils installed in a different path.

Other extensions that store these kind of settings do so in `~/.config/Code` outside of the workspace folder, which is usually git-controlled and shared.

Workspace folder settings should always be shareable, otherwise it doesn't make sense to have them inside the git directory. A sample of shareable settings we use can be found [here](https://github.com/Tecnativa/doodba-scaffolding/blob/master/.vscode/settings.json) and it includes settings specific for this project and handcrafted to work across computers.

Please store this somewhere else :pray: :sweat:

**Comment by lextm** [comment]
@Yajo What you commented has nothing to do with the original issue here.

You noticed that `"restructuredtext.confPath": ""` is being added, as that's the way this extension knows that it should use docutil as preview engine.

This setting alone can work perfectly for a whole team, as long as they agree to use docutil on all members' machines. I don't see why it is not sharable.

If you believe there should be some changes in this extension to adapt to your usage, please open a new issue and reveal more information.

**Comment by alexdresko** [comment]
That's just it. Not everyone is on the same team. In OSS, you can't depend on stuff like that. We all have different machines.

**Comment by lextm** [comment]
It is subjective here, as I personally consider `restructuredtext.confPath` per project setting. A project should be previewed either sphinx or docutil, and then all persons working on that project should stick to the same setting. I think it is a waste of time if someone uses sphinx and others use docutil because the preview results are completely different.

I created a separate issue #177 to track this.
