### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by sualko** [vscode-restructuredtext/vscode-restructuredtext#111]
> Please follow [the troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide) to locate the culprit.

Was the troubleshooting guide moved? 

**Environment**
- [x] Extension version: 78.0.0
- [x] Visual Studio Code version: 1.27.2
- [x] Operating System version: Ubuntu bionic
- [x] Python version: 2.7.15
- [x] sphinx version: 1.6.7
- [x] A sample of conf.py or its important fragments: Default settings from `sphinx-quickstart`.

**Expected behavior**
Headlines and blocks get highlighted.

**Actual behavior**
Only comments, `:foobar:` and `|foobar|` gets highlighted.

**Detailed Steps to reproduce the problem**
- Setup a new project with `sphinx-quickstart`. 
- Open the `index.rst` file.

Language mode shows `reStructuredText`.

**Comment by qiujiangkun** [comment]
I'm facing the same problem. Has it been fixed?

**Comment by lextm** [comment]
Starting from 159.0.0 release, this extension no longer provides syntax highlighting.

Close old items as off-topic.
