### ISSUE TITLE
Can't preview because the extension keeps override (correct) config path to wrong one

### ISSUE THREAD

**Issue by fireattack** [vscode-restructuredtext/vscode-restructuredtext#112]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 78
- [x] Visual Studio Code version: 1.28.1
- [x] Operating System version: Win 7
- [x] Python version: 3.7
- [x] sphinx version: 1.7.9
- [x] A sample of conf.py or its important fragments:

**Detailed Steps to reproduce the problem**

I have sphinx project in F:\.

I also explicitly set workplace's option (`.vscode/settings.json`) to:

```
{
    "restructuredtext.confPath": "F:\\sync\\code\\mahoromaticdb"
}
````

However, everytime I run preview on any rst file, the extension will override the above setting to `E:\\sync\\code\\mahoromaticdb` and then not be able to generate preview (ovbivously).

Log:

```
Source file: f:\sync\code\mahoromaticdb\songs\shiningofthedark.rst
Sphinx conf.py directory: e:\sync\code\mahoromaticdb
Sphinx html directory: e:\sync\code\mahoromaticdb\_build\html
Description: Cannot find "conf.py". Please review "restructuredtext.confPath" setting.
Error: Current "conf.py" setting is "e:\sync\code\mahoromaticdb\conf.py".
```

**Comment by fireattack** [comment]
The problem is gone after I moved the folder to another directory and then move it back.

I still think there is some problem there (cache?) but since it's hard to reproduce, I will close this for now.

**Comment by rizickus** [comment]
I am having the same problem. The idea of overwriting user settings is terrible and really annoying. @fireattack , please reopen this issue.

**Comment by fireattack** [comment]
I opened it. If anyone can get a more detailed repro, feel free!

**Comment by rizickus** [comment]
1. Generate preview.
2. Move conf.py file to another directory.
3. Change conf file path in configuration.
4. Try to generate preview again.
5. Now the new configuration is overwritten by the old one.

**Comment by lextm** [comment]
@rizickus When you find that a user setting needs to be manually set, that's a red flag.

**Comment by lextm** [comment]
@fireattack Please don't reopen your issue when someone else claims the same. He or she should open a new issue with relevant details.

**Comment by lextm** [comment]
@rizickus Please create a new issue with more details. Most importantly, what is the operating system, and what entries are recorded in the Log (you can check what @fireattack posted in the first comment above).

**Comment by rizickus** [comment]
Why close this issue if it was not solved at all? Please reopen it instead of creating duplications.
There is more information, I hope that helps.

**Environment**
- [x] Extension version: 78
- [x] Visual Studio Code version: 1.28.2
- [x] Operating System version: Win 10
- [x] Python version: 3.7.0
- [x] sphinx version: 1.8.1
- [x] A sample of conf.py or its important fragments:

**Expected behavior**

Do not touch user settings at all in any cases.

**Actual behavior**

Overwrites user settings.

**Detailed Steps to reproduce the problem**

1. Generate preview with that configuration:
```
{
    "restructuredtext.confPath": "c:\\Workspaces\\module-timeSync\\docs",
}
```
2. Move conf.py file to another directory.
3. Change conf file path in VS Code configuration:
```
{
    "restructuredtext.confPath": "c:\\Workspaces\\module-timeSync\\",
}
```
4. Try to generate preview again.
5. Now the new configuration is overwritten by the old one and generating preview terminates with an error.
```
{
    "restructuredtext.confPath": "c:\\Workspaces\\module-timeSync\\docs",
}
```

Log:
```
Source file: c:\Workspaces\module-timeSync\index.rst
Sphinx conf.py directory: c:\Workspaces\module-timeSync\docs
Sphinx html directory: c:\Workspaces\module-timeSync\docs\_build\html
Description: Cannot find "conf.py". Please review "restructuredtext.confPath" setting.
Error: Current "conf.py" setting is "c:\Workspaces\module-timeSync\docs\conf.py".
```

**Comment by lextm** [comment]
@rizickus The thread was closed, as there were not enough info to debug.

Clearly yours involves completely different steps and log entries, so it should be in a new issue.

**Comment by rizickus** [comment]
I added more details. Please read all posts one more time and pay more attention as both cases look similar. Okay, the discussion is going more about appropriate issue management, not the bug itself, so I will stop here. If needed, create a separate issue by your self. I am leaving facts as they are - there is a bug. You can leave it or solve it, your choise.
