### ISSUE TITLE
How to change the color style of preview

### ISSUE THREAD

**Issue by Shihta** [vscode-restructuredtext/vscode-restructuredtext#114]
The text can't be read clearly, the color is too similar.

**Environment**
- [x] Extension version: 79.0.0
- [ ] Visual Studio Code version: 1.28.1
- [ ] Operating System version: Mac
- [ ] Python version: 2.7.10
- [ ] sphinx version: no
- [ ] A sample of conf.py or its important fragments: no

**Expected behavior**

**Actual behavior**
![2018-10-20 10 09 14](https://user-images.githubusercontent.com/5186176/47250204-66162680-d450-11e8-88c0-0d4ae9199914.png)

**Detailed Steps to reproduce the problem**
Use the follow statement:

:code:`pip install docutils`

and then you'll find the color is too similar.

**Comment by lextm** [comment]
As we switched to docutils, it is now possible to customize preview styles if you use docutils engine.

The settings are almost the same as the Markdown settings, https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css
