### ISSUE TITLE
support relative python.pythonPath

### ISSUE THREAD

**Issue by tt4g** [vscode-restructuredtext/vscode-restructuredtext#122]
when set to relative path `python.pythonPath`, extension not working.
but Microsoft Python extension set relative path to `python.pythonPath`.

see: Microsoft/vscode-python#2705 and Microsoft/vscode-python#2685.

I don't want to set absolute path because I want to share settings.json.
Could you support relative `python.pythonPath`?

**Environment**
- [ ] Extension version: 83.0.0
- [ ] Visual Studio Code version: 1.29.1
- [ ] Operating System version: Microsoft Windows [Version 10.0.17134.407]
- [ ] Python version: 3.6.5
- [ ] sphinx version: 1.8.2
- [ ] A sample of conf.py or its important fragments: N/A

**Expected behavior**

open preview.

**Actual behavior**

does not working extension.

**Detailed Steps to reproduce the problem**

1. run *Python: Select Interpreter* of Microsoft Python extension.
2. set project venv python executable.
3. run *reStructuredText: Open Preview*.

**Comment by lextm** [comment]
Thanks. I will do some digging to see what kind of changes I might make.

**Comment by tt4g** [comment]
I tried `python.pythonPath: ${workspaceFolder}\\venv\\Script\\python.exe` but it not working,
and deprecated: contains ${workspaceFolder} in settings.json.
Microsoft/vscode-python#2459

**Comment by ypapouin** [comment]
For the record, I'm using this extension in a virtual environment created using pipenv on Windows and I don't have any issue using relative python path.
Preview is also working perfectly.

```
    "restructuredtext.confPath": "${workspaceFolder}\\source",
    "python.pythonPath": "${workspaceFolder}\\.venv\\Scripts\\python.exe",
```

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by tt4g** [comment]
@ypapouin Thank you for the information.

I also preview using this extension.

```json
{
  "python.pythonPath": "${workspaceRoot}/venv/Scripts/python",
  "restructuredtext.builtDocumentationPath": "${workspaceRoot}/build/html",
  "restructuredtext.confPath": "${workspaceRoot}/source",
  "restructuredtext.updateOnTextChanged": "true",
  "restructuredtext.updateDelay": 300,
  "restructuredtext.sphinxBuildPath": "${workspaceRoot}/venv/Scripts/sphinx-build"
}
```

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by tt4g** [comment]
I would like to close this issue.

@kazbeel How about you?

**Comment by Eido95** [comment]
For future folks, @ypapouin comment directed me to the solution.

I have Linux, and this extension didn't find my virtual environment `python` file.

I had the following setting in my `settings.json` file, which didn't work:
```
"python.pythonPath": "venv/bin/python",
```
Then I added `"${workspaceFolder}` prefix:
```
"python.pythonPath": "${workspaceFolder}/venv/bin/python"
```
Now confirmed to work.

**Comment by rgov** [comment]
The extension should support this properly without needing the configuration to be modified to work around it. Can this be re-opened?

**Comment by lextm** [comment]
@rgov Can you test release 107.0.0? I added some extra code to process relative path for `python.pythonPath` and at least that worked for me on macOS.

**Comment by juliohm1978** [comment]
I'm trying to make this work using pyenv from its default directory.

```
{
  "python.pythonPath": "${env:HOME}/.pyenv/versions/3.8.2/envs/myvenv/bin/python"
}
```
vscode does not recognize the venv and defaults to the system's python path.

Should this work for any ${} substitution?

**Comment by fordp2002** [comment]
"python.pythonPath" is selecting an absolute path in my Appdata. This will clearly not work for other users getting these settings. If I manually set it to:
"python.pythonPath": "%APPDATA%\\Local\\Programs\\Python\\Python38\\python.exe",
which would work for other windows users with a default python 3.8 install it fails to recognise it as the same.
