### ISSUE TITLE
Preview jumps to bottom of page

### ISSUE THREAD

**Issue by pwinston** [vscode-restructuredtext/vscode-restructuredtext#123]
**Environment**
- [x] Extension version: 83.0.0
- [x] Visual Studio Code version: 1.29.1
- [x] Operating System version: macOS 10.12.5
- [x] Python version: 3.6.5
- [x] sphinx version: 1.8.2

**Expected behavior**
When preview updates itself, it doesn't scroll away from the area I'm previewing. 

**Actual behavior**
When preview updates, it jumps to the bottom of the page its previewing. So I have to scroll back up to find where I was.

**Detailed Steps to reproduce the problem**
Open preview for .rst document that's longer than a page. Edit document. Preview jumps to bottom.

**Comment by lextm** [comment]
Related to #121

**Comment by lextm** [comment]
A quick update on this is that I cannot reproduce "it jumps to the bottom of the page" (my example is https://github.com/lextm/sharpsnmp_docs/blob/master/pro/getting-started/assembly-features.rst).

Like #121 indicated, the sync preview now uses an ugly algorithm to trigger the sync, so it can behave wrongly in certain cases. Before I found a page from my own repos that can reproduce the issue, you might share the page you work on so that I can better investigate the cause.

**Comment by pwinston** [comment]
I will see if I can figure it out. It hasn't been happening as much, but it's still not behaving as well as it could. So it's trying to sync in both direction? Scroll in RST and the Preview should match? Scroll in Preview and code should match?

Too early to say but it might make sense to just give up on one of the two, so it's more understandable and consistent. Like when you make a change in RST the Preview jumps there. But if you are reading along in Preview don't mess with the position in the RST. I think if it was 100% solid in that direction, and you just knew to find your position in the RST you'd have to search for a phrase, that might be better. Do the lesser thing well.

But I'll try to be observant and see what's going on. Pretty impressive to have this preview mode at all, very useful.

**Comment by kevinsullivan** [comment]
I too am seeing scroll to bottom of preview page upon refresh after change to source. How can I help?

**Comment by lextm** [comment]
@kevinsullivan can you provide a small sample project (a folder of necessary files to reproduce the issue)? Then let me know the steps to reproduce the issue. That can help a lot.

**Comment by rizickus** [comment]
My colleague also has this issue when writing longer documents. Will try to get a sample project on Monday.

**Comment by rizickus** [comment]
[rst.zip](https://github.com/vscode-restructuredtext/vscode-restructuredtext/files/2670860/rst.zip)
It can be reproduced with any longer document. Change the header in the `index.rst` file and a preview on the side jumps to the bottom of the page.

**Comment by pwinston** [comment]
I got this happening again. I have a RST file that's 250 lines long. When I scroll down to line 97 the preview hits bottom. As I keep scrolling down to line 130 the preview stays fixed at the bottom. As I continue to scroll down the preview scrolls *up*, I got one line down the preview goes one line up. When I hit line 250 the preview is about 3/4 of the way back up to the top. So the mapping between the two is way off.

I wondering if it would be useful if you could just toggle off the syncing, in both directions. Even apart from this bug, it seems like some people might just prefer not having the syncing.

**Comment by yozlet** [comment]
I'm using the extension on a Mac (OS 10.14.2) with VSCode & the extension up to date. I see very similar behaviour to @pwinston, but scaled to the length of the file:

* Total file length: 363 lines
* On scrolling the editor downwards:
    * preview scrolls downward much faster than editor
    * preview reaches bottom at line 111
    * preview starts scrolling back upwards slower from line 160
	* preview reaches top at the same time that editor reaches bottom
* On scrolling the editor upwards from the bottom, I get a similar behaviour in reverse, but with the pivot points moved:
    * preview scrolls upward much faster than editor
    * preview hits the top, waits a while, then scrolls downward slower while the editor continues upward
* On scrolling the preview:
    * editor jumps to top as soon as scroll starts
    * editor scrolls slowly between lines 1 and 111 as I move the preview from top to bottom and back

The problem with the sync algorithm is bi-directional between editor and preview. If either of the two "scrollXwithY" settings is enabled, I can repro it.

**Comment by lextm** [comment]
All efforts will be resumed in #121
