### ISSUE TITLE
No plantUML output in preview window

### ISSUE THREAD

**Issue by rizickus** [vscode-restructuredtext/vscode-restructuredtext#124]
No plantUML output in preview window. Instead of images, the uml source code is shown. In older versions everything was okay, I am not sure which version broke the preview feature. All images are shown when opened with browser.

**Environment**
- [x] Extension version: 83.0.0
- [x] Visual Studio Code version: 1.29.1
- [x] Operating System version: Win 10
- [x] Python version: 3.7.0
- [x] sphinx version: 1.8.2
- [x] A sample of conf.py or its important fragments:

```
extensions = [
    'sphinxcontrib.plantuml'
]
```

**Comment by rizickus** [comment]
Also a preview style looks different. CSS file not found? Maybe there is a problem with paths?

**Comment by lextm** [comment]
Can you show what is displayed on status bar? `docutils` or your `conf.py`? 

https://docs.restructuredtext.net/articles/configuration.html#sample-project

**Comment by rizickus** [comment]
I do not use `docutils` at all. All projects are based on sphinx and status bar shows my selected `conf.py` file.

**Comment by lextm** [comment]
Thanks. First time to try PlaneUML.

It seems to insert an image to the HTML page, while 81.0.0+ of this extension uses another way to load the HTML which requires a different link prefix for such images. When the link is not right, `alt` is displayed instead, which is the UML source like you reported.

I will see if I can fix such links to make the images load properly.

**Comment by rizickus** [comment]
Manually running sphinx returns `build succeeded` without any warnings or errors. I can see generated images in folder `_images` and in browser.


I tried to delete the `_build` folder. Then I generated a preview in the VS Code and it does not show any image. But if I look into `_build` folder, I can see that images were generated and if I open the `index.html` in browser everything looks as expected.

**Comment by lextm** [comment]
Thanks. Sounds like I need to grab a Windows machine to try again.

**Comment by lextm** [comment]
Fixed #127. Can you test release 86.0.0? I assume this issue should also be fixed then.

**Comment by rizickus** [comment]
It works! Thank you for this awesome extension!

**Comment by lextm** [comment]
Thanks for confirming it. Mark it as duplicate.
