### ISSUE TITLE
Preview selection sphinx/docutils reset not working

### ISSUE THREAD

**Issue by xrayn** [vscode-restructuredtext/vscode-restructuredtext#125]
**Environment**
- [x ] Extension version: 84.0.0
- [x ] Visual Studio Code version: 1.29.1
- [x ] Operating System version: Windows 10
- [x ] Python version: 3.7
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

"The active rst to htlm transformer (click to reset)"
Clkicking the button should reset the current transformer and allow to select a different transformer.

**Actual behavior**

Clicking does not reset the transformer (nothing happens when clicking on text)

**Detailed Steps to reproduce the problem**

Click on the text (red box attached image)

![image](https://user-images.githubusercontent.com/1036978/49690750-505edc80-fb36-11e8-8789-fb31dbe6c2d1.png)

When sphinx is selected via the initial setup, changing back to docutils is also not possible.

**Comment by lextm** [comment]
Thanks. Sounds like another Windows related issues. I need to find a Windows test machine in the coming days.

**Comment by xrayn** [comment]
FYI: it seems to work in Linux on Debian as you said:

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

restructuredtext version: 85.0.0 

However, it is necessary to spamclick until sometime the selection appears.

**Comment by lextm** [comment]
Thanks. I can reproduce this on a Windows machine. Will see how to fix it.

**Comment by lextm** [comment]
The patch will be included in release 87.0.0.

**Comment by adam-grant-hendry** [comment]
@lextm I am having this issue as well. I am running restructuredtext version 129.0.0.

**Comment by adam-grant-hendry** [comment]
@lextm False alarm. This happens if you put restructuredtext JSON settings in the WSL Remote Settings in VSCode as opposed to the locally set settings in the .vscode folder. Moving settings from WSL JSON file to local file fixed problem. No need to reopen.
