### ISSUE TITLE
doc8 configuration

### ISSUE THREAD

**Issue by ovv** [vscode-restructuredtext/vscode-restructuredtext#128]
**Environment**
- [x] Extension version: 87.0.0
- [x] Visual Studio Code version: 1.29.1
- [x] Operating System version: ArchLinux
- [x] Python version: 3.7
- [x] sphinx version: 1.8.1
- [x] doc8 version: 0.8.0
- [ ] A sample of conf.py or its important fragments: N/A

**Visual Studio Code Settings**

```
{
    "restructuredtext.linter.executablePath": "/home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/doc8",
    "python.pythonPath": "/home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/python",
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/build",
    "restructuredtext.confPath": "${workspaceFolder}/wiki",
    "restructuredtext.linter.extraArgs": ["--ignore D001", "--max-line-length 200"],
}
```

**Expected behavior**

No D001 warning

**Actual behavior**

D001 warnings (Line too long) are present

**Detailed Steps to reproduce the problem**

I initially had a `doc8.ini` file:
```
[doc8]
ignore=D001
```
and the warnings where present so I tried multiple `restructuredtext.linter.extraArgs` with no success.
There is no output in the Visual Studio Code output tab for debugging.

Executing `doc8` in the terminal output no D001 warnings

```
> /home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/doc8
Scanning...
Validating...
========
Total files scanned = 21
Total files ignored = 0
Total accumulated errors = 0
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 0
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 0
    - CheckValidity = 0
```

**Comment by lextm** [comment]
Some investigation results,

* Extra args work for me on macOS. So I might need a Linux machine to reproduce it.
* If doc8.ini is used to change linter behavior, then VSCode needs to be restarted for the settings to take effect. I will try to add this to documentation.

**Comment by ovv** [comment]
I'm also not sure where should the `doc8.ini` file be. For the moment it's at `${workspaceFolder}/doc8.ini`, I'm not sure if `restructuredtext.confPath` changes that.

>  So I might need a Linux machine to reproduce it.

I'm not familiar with the VSCode extension system but if there is anything I can activate to get more debug information feel free to let me know.

**Comment by lextm** [comment]
Can you upgrade to release 89.0.0 and then test again? I added linting log entries, which might show more information and reveal the actual problem calling it on your machine.

I built a Ubuntu machine but could not reproduce the issue you initially described.

**Comment by ovv** [comment]
Thanks for the update, I was able to do some tests. There seems to be a second issue (or a misunderstanding on my part) on how workspace work, See #130

Testing on a single project the `restructuredtext.linter.extraArgs` worked properly but the `doc8.ini` file is not detected. The `doc8.ini` path is `${workspaceFolder}/doc8.ini`.

**settings**
```
{
    "python.pythonPath": "/home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/python",
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/build",
    "restructuredtext.confPath": "${workspaceFolder}/wiki",
}
```
**vscode debug output**
```
Execute linting: /home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/python -m doc8.main /home/quent/projects/perso/wiki/wiki/infra/physical.rst in /home/quent/projects/perso/wiki.
```
**shell test**

From home directory:
```
> /home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/python -m doc8.main /home/quent/projects/perso/wiki/wiki/infra/physical.rst
Scanning...
Validating...
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:17: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:19: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:21: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:23: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:25: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:177: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:179: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:181: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:183: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:185: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:187: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:189: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:194: D001 Line too long
/home/quent/projects/perso/wiki/wiki/infra/physical.rst:195: D001 Line too long
========
Total files scanned = 1
Total files ignored = 0
Total accumulated errors = 14
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 14
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 0
    - CheckValidity = 0
```

From project directory
```
~/projects/perso/wiki master*
> /home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/bin/python -m doc8.main /home/quent/projects/perso/wiki/wiki/infra/physical.rst
Scanning...
Validating...
========
Total files scanned = 1
Total files ignored = 0
Total accumulated errors = 0
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 0
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 0
    - CheckValidity = 0
```

The `in` part of the vscode debug ouput is matching the shell directory when `doc8.ini` is detected but it's not working. It is possible to give the path to the configuration file using `restructuredtext.linter.extraArgs` but it must be the full path, using `${workspaceFolder}/doc8.ini` doesn't work (`${workspaceFolder}` is not replaced).

Depending on the work required to fix automatic detection of `doc8.ini` and additional settings supporting `${workspaceFolder}` could be a good middle ground.

**Comment by lextm** [comment]
#131 is the most important bug here. 

But the location of `doc8.ini` is also an interesting topic to explore, so let's use this issue to merely track that.

**Comment by lextm** [comment]
It is not clear to me why doc8 process initialized by Node.js does not read `doc8.ini` from the working directory. Don't want to spend too much time on that.

In release 95.0.0+, you can use macro in linter arguments, so you can pass `--config ${workspaceFolder}/doc8.ini` like,
```
    "restructuredtext.linter.extraArgs": [
        "--config ${workspaceFolder}/doc8.ini"
    ],
```

**Comment by ovv** [comment]
Thanks for the fix

**Comment by flying-sheep** [comment]
Can you please reopen this? I have a doc8.ini in my workspace directory which is ignored by the doc8 process started from your extension.

I want the default behavior to work (trying out `tox.init`, `doc8.ini`, …) since multiple projects have the `[doc8]` section in different of those files.

**Comment by lextm** [comment]
@flying-sheep Please open a new issue, and also provide more details on what you want to achieve (examples of config files and so on).

**Comment by flying-sheep** [comment]
Done, #154
