### ISSUE TITLE
Previewer sphinx-build cannot be found

### ISSUE THREAD

**Issue by ssbarnea** [vscode-restructuredtext/vscode-restructuredtext#129]
I keep getting Previewer sphinx-build cannot be found with no indication on how to sort the issue, as I do have the cli insalled in my shell.

**Comment by lextm** [comment]
Please provide more info as detailed in the issue template, https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/.github/ISSUE_TEMPLATE.md Without that it is difficult to tell what might be wrong.

**Comment by ssbarnea** [comment]
Apparently it was a local issue caused by the installation of sphinx using --user while having pyenv. Later when I updated pyenv from 2.7.14 to 2.7.15 the symlink from the script pointed to the wrong python. I guess this is a permanent source of issues for anyone that uses pip install --user and pyenv, once you upgrade pyenv you will likely endup with some broken scripts in your ~/.local/bin -- and the brokend status is quite hard to spot because you don't get interpreter error, just that they cannot find their packages... but the shebang tells why.

While original bug was not of the tool I think there is a solution to improve the error message and avoid future false reports: Ask user to test the missing command using **vscode terminal**, this being the only safe way to validate it. If the message can also contain a clickable link the opens the vscode terminal even better.

The vscode terminal environment can be very different than the one you use on  your terminal, if the message mentions this, people will be able to narrow down their problems.

Without such an message their insting would be to rest on their shell,... and in many cases it works in their shell.

And thanks for the quick reply!

**Comment by lextm** [comment]
Release 92.0.0+ should attempt to assert missing dependencies and install them before moving on. That should help avoid such issues.
