### ISSUE TITLE
Workspace vs folder setting

### ISSUE THREAD

**Issue by ovv** [vscode-restructuredtext/vscode-restructuredtext#130]
**Environment**
See #128 

**Expected behavior**

Using a workspace with multiple projects the project specific settings should be taken into account.

**Actual behavior**

Some settings are not used.

**Detailed Steps to reproduce the problem**

* Create a workspace with two projects
* Set `restructuredtext.linter.extraArgs` in the project specific settings
* `doc8` is invoked without the extra arguments

-----

* Create a workspace with two projects
* Set `python.pythonPath` in the project specific settings
* `doc8` is called using system python

**Comment by lextm** [comment]
There are multiple issues related to this one. So will try to close the relevant items and then close this one.
