### ISSUE TITLE
No longer get sphinx preview working

### ISSUE THREAD

**Issue by lindhor** [vscode-restructuredtext/vscode-restructuredtext#133]
**Environment**
- [x] Extension version: 91.0.0
- [x] Visual Studio Code version: 1.30.0
- [x] Operating System version: Windows 10
- [x] Python version: 3.7.0 and 3.7.1
- [x] sphinx version: 1.8.2
- [x] A sample of conf.py or its important fragments:

```
# -*- coding: utf-8 -*-
project = 'test'
copyright = '2018, test'
author = 'test'
version = ''
release = '1.0'
extensions = [
]
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
language = None
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = None
html_theme = 'alabaster'
html_static_path = ['_static']
htmlhelp_basename = 'testdoc'
latex_elements = {
}
latex_documents = [
    (master_doc, 'test.tex', 'test Documentation',
     'test', 'manual'),
]
man_pages = [
    (master_doc, 'test', 'test Documentation',
     [author], 1)
]
texinfo_documents = [
    (master_doc, 'test', 'test Documentation',
     author, 'test', 'One line description of project.',
     'Miscellaneous'),
]
epub_title = project
epub_exclude_files = ['search.html']
```

**Expected behavior**
I love this extension and have had it working fine until lately. The preview now only shows a "simple" preview layout, not including the selected theme. I'm normaly using the sphinx-rtd-theme but also get the same issue with the default alabaster theme as well.

**Actual behavior**
Looking in the developer console I see messages that makes me Believe that the restructuredtext extension has crashed
``

**Detailed Steps to reproduce the problem**

**Comment by lindhor** [comment]
Submitted a bit too soon… Errors from the developer console shows
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Activating extension 'tht13.rst-vscode' failed: command '_rst.moveCursorToPosition' already exists.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5724 Activating extension 'tht13.rst-vscode' failed: command '_rst.moveCursorToPosition' already exists.
t._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5724
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Activating extension `tht13.rst-vscode` failed:  command '_rst.moveCursorToPosition' already exists
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Here is the error stack:  Error: command '_rst.moveCursorToPosition' already exists
	at e.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:500:341)
	at Object.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:733:544)
	at CommandManager.registerCommand (C:\Users\Basalt\.vscode\extensions\tht13.rst-vscode-3.0.1\out\commandManager.js:26:47)
	at CommandManager.register (C:\Users\Basalt\.vscode\extensions\tht13.rst-vscode-3.0.1\out\commandManager.js:19:14)
	at activate (C:\Users\Basalt\.vscode\extensions\tht13.rst-vscode-3.0.1\out\extension.js:39:20)
	at <anonymous>
```
In the Output log nothing special is shown
```
[Log - 11:33:28 AM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 11:33:28 AM] Running cmd: python -c "import sys; print(sys.version_info[0])"
[Log - 11:33:28 AM] Successful exec
3

[Log - 11:33:28 AM] Running cmd: python -c "import docutils;"
[Log - 11:33:29 AM] Successful exec
[Log - 11:33:29 AM] Running cmd: python -c "import sphinx;"
[Log - 11:33:29 AM] Successful exec
[Log - 11:33:29 AM] Running cmd: python -c "import doc8.main;"
[Log - 11:33:30 AM] Successful exec
```
I have tried setting user preferences without any change.
```
    "restructuredtext.confPath": "${workspaceFolder}",
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/_build/html",
    "restructuredtext.sphinxBuildPath": "C:\\Python\\Scripts\\sphinx-build.exe",
```
I have also tried downgrading to the extension version 0.78 that I was using earlier but no change.

I get the same results on Another machine that is freshly installed.

Standard sphinx `make html` works fine.

My guess is that the extension crashes for some reason and that what I'm seeing is some builtin preview from vscode,

After disabling ALL extensions, restarting, enabling the rst extension and python extension, restarting again, I get back to a working environment. By trial and error, enabling one extension at the time, it seems like the extension Template Toolkit https://marketplace.visualstudio.com/items?itemName=samosad.tt clashes with the rst extension.

Do you possibly have any idea what can have gone wrong or how to troubleshoot this further?

**Comment by lextm** [comment]
You might uninstall the extension `tht13.rst-vscode` to see if that resolves the issue (as that's the crash you saw in log).

I am not familiar with `samosad.tt` but if it is for Perl, then there should be no conflict with this extension.

**Comment by lindhor** [comment]
Thanks for quick reply. On one of my machines I had the RST Preview extension loaded (the.rst-vscode) but not the Template Toolkit (samoad.tt). On the other it was the opposite, Template Toolkit loaded but not RST Preview. Disabling these two and keeping all my other extensions loaded and all is working fine on both machines. If you want me to provide any further logs or such in order to troubleshoot, please let me know, otherwise you may close the issue.

**Comment by lextm** [comment]
Thanks. What you provided should be enough for me to get started. I will check the code of `samosad.tt` to see if any obvious conflict can be found.

**Comment by lextm** [comment]
I added conflicting extension detection, so this extension reports an error if `tht13.rst-vscode` is also installed.

However, there is no evidence that `samosad.tt` is conflicting. I checked its source code and could not find any obvious problem either.

Close it now.
