### ISSUE TITLE
starting the extension seems to hang

### ISSUE THREAD

**Issue by bearsh** [vscode-restructuredtext/vscode-restructuredtext#134]
**Environment**
- [x] Extension version: 91.0.0
- [x] Visual Studio Code version: 1.30.0
- [x] Operating System version: gentoo
- [x] Python version: 3.6.6
- [x] sphinx version: 1.8.2
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
the extension starts up and works correctly

**Actual behavior**
the extension seems to hang during startup and one _code_ process use a lot of cpu
"""
[Log - 13:41:22] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 13:41:22] Running cmd: python -c "import sys; print(sys.version_info[0])"
"""
![image](https://user-images.githubusercontent.com/1089356/50087999-0ba40700-0202-11e9-9134-ee275799331a.png)

is the a way to generate more debugging indos?

**Comment by lextm** [comment]
Can you disable IntelliSense and try again? 

https://docs.restructuredtext.net/articles/configuration.html#intellisense
```
"restructuredtext.languageServer.disabled": true
```

**Comment by bearsh** [comment]
this seems to work
```
[Log - 14:41:53] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 14:41:53] Running cmd: python -c "import sys; print(sys.version_info[0])"
[Log - 14:41:53] Successful exec
3

[Log - 14:41:53] Running cmd: python -c "import docutils;"
[Log - 14:41:53] Successful exec
[Log - 14:41:53] Running cmd: python -c "import sphinx;"
[Log - 14:41:53] Successful exec
[Log - 14:41:53] Running cmd: python -c "import doc8.main;"
[Log - 14:41:53] Successful exec
```

**Comment by bearsh** [comment]
is there anything I can help you with, e.g. provide some more log, ...?

**Comment by lextm** [comment]
There is not much you can help, as IntelliSense is still experimental, and only partially tested on Ubuntu. I am not sure how gentoo might lead to such issues, but I might build a virtual machine to try out.

What version of gentoo do you use?

**Comment by bearsh** [comment]
I don't know if it's worth the effort right now as gentoo doesn't have versioned releases, it's a rolling distro where you compile everything by yourself. so it would probably take hours to have a virtual machine running the right software stack...

**Comment by lextm** [comment]
I just took a look at Gentoo, and found similar info.

The IntelliSense feature uses .NET Core, which does not support Gentoo, https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md

So instead of going deeper, I will try to automatically disable IntelliSense on Gentoo in next release.

There would be no workaround, but switch to a supported Linux distribution.

**Comment by bearsh** [comment]
does the extension download .NET core (or whatever it needs form it) or does it expect to be installed somehow on the system? if

**Comment by lextm** [comment]
The language server is self contained, so you don't need to install .NET Core runtime on your own. However, that still does not support Gentoo.

**Comment by lextm** [comment]
Release 92.0.0+ will automatically disable IntelliSense on Gentoo. Close this issue now.

**Comment by bearsh** [comment]
I did some research and came across this site https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md where the system prerequisites for .NET-Core are listed. after installing libunwind (which was missing on my system), the IntelliSense feature seems to work. (I verified it by downgrading the extension, remove libunwind again, which resulted in the hanging process, installing it again, extension works)

**Comment by bearsh** [comment]
> Release 92.0.0+ will automatically disable IntelliSense on Gentoo. Close this issue now.

is this just the default config setting (-> I can enable it in settings.json) or is it hard disabled?

**Comment by lextm** [comment]
I think you might configure two settings to enable IntelliSense,
```
"restructuredtext.languageServer.disabled": false,
"restructuredtext.languageServer.supportedPlatforms": ["Gentoo Linux"]
```
