### ISSUE TITLE
doc8 deprecation warnings get reported as problems

### ISSUE THREAD

**Issue by ovv** [vscode-restructuredtext/vscode-restructuredtext#136]
Deprecation warnings raised by the doc8 library get reported as problems in my documents

**Environment**
See #128

**Expected behavior**
No problems reported

**Actual behavior**
`DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.`

**Detailed Steps to reproduce the problem**

Running doc8 version 0.8.0 on my environment output:
```
/home/quent/.local/share/virtualenvs/wiki-BPmjEsJJ/lib/python3.7/site-packages/doc8/main.py:90: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  parser.readfp(fh, filename=fn)
Scanning...
Validating...
========
Total files scanned = 1
Total files ignored = 0
Total accumulated errors = 0
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 0
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 0
    - CheckValidity = 0

```

The first line gets reported as an error coming from my document when it's actually coming from doc8.

This can be fixed by launching python with `-W ignore::DeprecationWarning` or adding `-W ignore::DeprecationWarning` in `restructuredtext.linter.extraArgs`.

IMO this should be either documented, set by default when launching doc8 or not added as a problem by the extension.

**Comment by lextm** [comment]
Tracked at doc8 https://bugs.launchpad.net/doc8/+bug/1809562

The next release will filter out such.
