### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#137]
I've actually noticed something similar, that might be more direct as it what I came looking for. 
BUT
I am seeing side effects of the RST markdown creeping into my code-block.

![capture](https://user-images.githubusercontent.com/39355436/50387726-9c328980-06d1-11e9-9c73-5dfc307574aa.PNG)

Whilst I don't have the lexer loaded for this language, I would expect it to just not interfere and leave it syntax free. 

Do you see in 'List Type' section above, the words between ` text source <cheatsheet.txt>` are colorized red, but the same back tick in the code block is also colorized red - and with an entirely different meaning, it just floods the code.

Thanks

_Originally posted by @michaelsimonelli in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/135#issuecomment-449664895_

**Comment by qiujiangkun** [comment]
I'm facing the same problem. Has it been fixed?

**Comment by lextm** [comment]
The test code is

```

.. code-block:: q

  select col1 from tab where t=1

  .py.reflect:{[module]
    import: .py.imp[module];
    mdinfo: .py.mod_info[import];

    .py.meta[module]:mdinfo;

    classes: mdinfo[`classes];
    reflect: (key classes)!.py.cxt[import; classes];

    .pq[module],:reflect;

    1b};
```

In release 154.0.0 the old grammar file was replaced by the one from https://github.com/trond-snekvik/vscode-rst .

Close this item now as it does not appear with that grammar file.
