### ISSUE TITLE
Output should not append _sources

### ISSUE THREAD

**Issue by bnmnetp** [vscode-restructuredtext/vscode-restructuredtext#138]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 69
- [ ] Visual Studio Code version: 1.30.1
- [ ] Operating System version: macOS 10.14.2
- [ ] Python version: 3.7.1
- [ ] sphinx version: 1.8.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

**Actual behavior**

I get the following error message from Live Preview

```
ENOENT: no such file or directory, open '/Users/bradleymiller/Runestone/httlads/book/build/httlads/_sources/Happiness/happiness.html'
```
In my settings I have the following custom settings:

```
    "restructuredtext.sphinxBuildPath"        : "/Users/bradleymiller/bin/runestonebuild.sh",
    "restructuredtext.builtDocumentationPath" : "${workspaceRoot}/book/build/httlads",
    "restructuredtext.confPath"               : "${workspaceFolder}/book",
```

**Detailed Steps to reproduce the problem**

The build runs successfully and produces html in the build/httlads folder as expected, however Live Preview seems intent on adding  `_sources/` to the path.

More from the output pane:

```
[Log - 5:23:04 PM] Compiling file: /Users/bradleymiller/Runestone/httlads/book/_sources/Happiness/happiness.rst
Sphinx conf.py directory: /Users/bradleymiller/Runestone/httlads/book
Sphinx html directory: /Users/bradleymiller/Runestone/httlads/book/build/httlads
Compiler: /Users/bradleymiller/bin/runestonebuild.sh -b html . "/Users/bradleymiller/Runestone/httlads/book/build/httlads"
Working directory: /Users/bradleymiller/Runestone/httlads/book
HTML file: /Users/bradleymiller/Runestone/httlads/book/build/httlads/_sources/Happiness/happiness.html
Description: <p>Cannot read preview page "/Users/bradleymiller/Runestone/httlads/book/build/httlads/_sources/Happiness/happiness.html".</p>                        <p>Possible causes are,</p>                        <ul>                        <li>A wrong "conf.py" file is selected.</li>                        <li>Wrong value is set on "restructuredtext.builtDocumentationPath".</li>                        </ul>
```

**Comment by lextm** [comment]
Release 69.0.0 was made on Aug 27.

There is no plan to support any previous version. Please upgrade to the latest.

**Comment by bnmnetp** [comment]
Sorry, that was a typo, I was referring to the latest version 96.0
