### ISSUE TITLE
[Feature request] Show preview button

### ISSUE THREAD

**Issue by TormodLandet** [vscode-restructuredtext/vscode-restructuredtext#139]
I just saw that the [LaTeX Workshop plugin](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) has a dedicated button on the editor that opens the preview. This makes it very discoverable. Not essential, but nice to have.

![](https://github.com/James-Yu/LaTeX-Workshop/raw/master/demo_media/preview.gif)

Thanks for all your great work Lex!

**Comment by lextm** [comment]
This extension also has such a button, though it reuses the icon of VSCode Markdown extension.

![image](https://user-images.githubusercontent.com/425130/50868295-ce541480-137c-11e9-92ab-9e2cebec129f.png)
