### ISSUE TITLE
Can't preview in vscode 1.1.1

### ISSUE THREAD

**Issue by fenbox** [vscode-restructuredtext/vscode-restructuredtext#14]
```
python==3.5.1

Sphinx
=======
Metadata-Version: 2.0
Name: Sphinx
Version: 1.4.2
Summary: Python documentation generator
Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
Installer: pip
License: BSD
Location: /Users/xxxxxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages
```

When I run `ctrl+shift+r` return a error below

![image](https://cloud.githubusercontent.com/assets/360618/15766649/58795e46-2973-11e6-98d7-a5650e1356a9.png)

> Unable to open '/Preview: '/source/reputation.rst'': Cannot read property 'document' of undefined.

the developer show these error:

![image](https://cloud.githubusercontent.com/assets/360618/15812865/60b22cf2-2bec-11e6-90e9-e145bb00feb4.png)

> ENOENT: no such file or directory, stat `./_build/html/source/***.html`

In fact, my directory tree are:

![image](https://cloud.githubusercontent.com/assets/360618/15812902/b4f0506e-2bec-11e6-9e30-d6f61054bcb5.png)

**Comment by moigagoo** [comment]
Preview doesn't work in the latest Insider build as well (1.3.0 at the moment of writing).

The error is Unable to open '/Preview: '/path/to/README.rst'': Error

Console output on Pastebin: http://pastebin.com/gK3HghnL

**Comment by lextm** [comment]
Not sure what's your conf.py content, but you might have to set Preview Settings,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

So as to let this extension know that it should go to `./build/html` instead of `./_build/html`.

**Comment by moigagoo** [comment]
I don't have a Sphinx project, just a single .rst file.

**Comment by moigagoo** [comment]
BTW syntax highlighting doesn't work either.

**Comment by lextm** [comment]
@moigagoo this extension puts Sphinx as a prerequisite so your case is not supported.

**Comment by moigagoo** [comment]
OK, now I'm in a Sphinx project, I have Sphinx installed, conf.py is pretty much default. Still having the same error.

I probably should have mentioned I'm on Mac.

**Comment by moigagoo** [comment]
@lextm Preview works if:
1. It's a Sphinx project (therefore the extension title may be misleading).
2. The root of the VSCode project is the root of the Sphinx project (otherwise the lookup path for the generated .html is wrong, e.g. `_build/html/dirname/` vs `dirname/_build/html`).

**Comment by moigagoo** [comment]
@lextm Sorry, I am clearly being an idiot here. Obviously, the paths can be specified in the settings, which I completely overlooked.

I think @fenbox had the very same issue, so tuning the settings should help.

If yes, I think it is safe to close the issue.

P.S. Thanks for investing your time and talent into this great extension!

**Comment by fenbox** [comment]
OK, I config follow [this](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md)  and it works now.
It's not seem like a live preview.

**Comment by lextm** [comment]
@fenbox It can be live preview only if you run "sphinx-autobuild" and set the generated HTML path as above. Then every time you change the source, the generated HTML reflects the changes.

However, the preview window won't update itself yet, which is something I will try to explore soon. Yes, a lot of work is ahead.

**Comment by fenbox** [comment]
@lextm Roger that.
That's a pretty extension. Keep on ^__^

**Comment by nhathongly** [comment]
Sorry for commenting in a closed issue. But I got this error when using Visual Code on Windows 10. I followed [this](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md) carefully, but it couldn't help

Error: Error
spawn C:\WINDOWS\system32\cmd.exe ENOENT
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by RosscoeP** [comment]
The extension does NOT list it's pre-requisites. After digging around in it's docs you eventually find a reference to what needs installing to get it to run. It is not present on the extensions home page as with other projects.

I'm windows 10 PRO, VSCode 1.26.0,  reStructuredText 75.0.0, python 3.7.0, pip 18.0
I ran pip install sphinx sphinx-autobuilder doc8
so I now have sphinx-build 1.7.9.

I've run sphinx-quickstart in my repo's root folder and let it destroy my makefile and add other files.

ctrl+shift+r:-

Cannot show preview page.

Description:

Cannot preview. Please review "restructuredtext.sphinxBuildPath" setting.

Detailed error message

Error
Command failed: "C:\Program Files\Python37\Scripts\sphinx-build.EXE" -b html . "c:\Users\rhedges\Documents\GitHub\tangentlabs\nailsinc-us\www\nailsinc\promotions\_build\html"

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "c:\program files\python37\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 1, in 
    from oscar.core.loading import get_class
ModuleNotFoundError: No module named 'oscar'


Error: Command failed: "C:\Program Files\Python37\Scripts\sphinx-build.EXE" -b html . "c:\Users\rhedges\Documents\GitHub\tangentlabs\nailsinc-us\www\nailsinc\promotions\_build\html"

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "c:\program files\python37\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 1, in 
    from oscar.core.loading import get_class
ModuleNotFoundError: No module named 'oscar'


	at ChildProcess.exithandler (child_process.js:287:12)
	at emitTwo (events.js:126:13)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "c:\program files\python37\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 1, in 
    from oscar.core.loading import get_class
ModuleNotFoundError: No module named 'oscar'

More Information

Diagnostics information has been written to OUTPUT | reStructuredText panel.

The troubleshooting guide can be found at

https://www.restructuredtext.net/en/latest/articles/troubleshooting.html



Oh and the link to the troubleshooting page doesn't work!
I give up!

**Comment by TormodLandet** [comment]
You do not need Sphinx if your RST is not using Sphinx. If you are writing ReStructuredText then I assume you have docutils installed? Newer versions of the RST extension will use docutils' rst2html command to generate the preview without messing with any configuration files or overwriting any Makefiles.

If you have a problem with this procedure I recommend opening a separate issue instead of commenting on a closed one. I agree with you that the Sphinx / rst2html functionality (and dependencies) could be listed in the plugin README which is shown when you install the extension

**Comment by lextm** [comment]
Please avoid commenting under a closed issue. The Python community makes it difficult to set up everything on Windows (or Microsoft, who knows), so I think we need a dedicate article on the documentation site to provide hints (I cannot promise step by step, as that won't work for everyone).

This extension cannot use a simple "prerequisites" like other extensions, as the setup indeed is over complicated. If we count virtual environment, which I am not yet quite familiar with, it is more complex.

It is not something this extension alone can improve immediately. I just found the Microsoft Python extension can be helpful sometimes, so the new article might refer to it from time to time.
