### ISSUE TITLE
Additional rst role snippets/shortcuts

### ISSUE THREAD

**Issue by lindhor** [vscode-restructuredtext/vscode-restructuredtext#143]
It would be good to add snippets with shortcuts for :code:\`xxx\`, :command:\`xxx\`, :file:\`xxx\`, :kbd:\`xxx\`, :guilabel:\`xxx\` and :menuselection:\`xxx\` in addition to the existing ones.
These are all quite common when writing technical handbooks and thus would benefit from being easily available.

**Comment by lextm** [comment]
Sounds like they come from https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html

**Comment by lindhor** [comment]
Yes, that’s correct!

Hälsar / Best regards

Roger Lindholm
System Architect
Basalt AB

POSTADRESS Box 38, 745 21 Enköping, Sweden
BESÖKSADRESS Basaltgatan 3

TELEFON +46 171- 17 05 00
MOBIL +46 722 01 8008
E-POST roger.lindholm@basalt.se

________________________________
Från: Lex Li <notifications@github.com>
Skickat: måndag, februari 4, 2019 9:19 em
Till: vscode-restructuredtext/vscode-restructuredtext
Kopia: Roger Lindholm; Author
Ämne: Re: [vscode-restructuredtext/vscode-restructuredtext] Additional rst role snippets/shortcuts (#143)


Sounds like they come from https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html

**Comment by lextm** [comment]
Added a few more in the latest release. You can find them in https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/snippets/snippets.json

**Comment by lindhor** [comment]
Thanks! Works fine!
