### ISSUE TITLE
Kill/queue process on new build (and provide separate log window)

### ISSUE THREAD

**Issue by chrisjsewell** [vscode-restructuredtext/vscode-restructuredtext#147]
I would strongly suggest you refactor your build code to resemble  [LaTeX-Workshop's](https://github.com/James-Yu/LaTeX-Workshop), 
[builder class](https://github.com/James-Yu/LaTeX-Workshop/blob/2c85e0b95d3cf08653f33340d53c5868078da08f/src/components/builder.ts#L14).

This has two key benefits:

1. It provides a separate log window for the process stdout/stderr
2. It only allows one compilation process to run at a time (fixing #104)

<img width="763" alt="screen shot 2019-02-16 at 08 48 49" src="https://user-images.githubusercontent.com/2997570/52897227-efa0ef80-31c9-11e9-8076-29f2f779f4b1.png">

**Comment by lextm** [comment]
I don't like its approach to kill the current process. There should be a better way, but currently I have no time to invest in this area.

**Comment by chrisjsewell** [comment]
> I don't like its approach

Fair enough, but it works and I use it constantly, whereas because of #104 I find your previewer unusable. Which is a shame, because it could be equally great with a few tweaks

**Comment by dtgraham9** [comment]
@lextm Curious as to why you don't like to kill the current process.

**Comment by lextm** [comment]
@dtgraham9 because I don't own the sphinx components, and I cannot guarantee killing them won't lead to problems.

**Comment by chrisjsewell** [comment]
> I don't own the sphinx components

Perhaps I am misunderstanding, but what do you mean by this?
You are simply spawning a child process, which you own, that calls the `sphinx-build` python entry point. If you kill this process, there shouldn't be any problem.

If not this then, perhaps a more elegant approach, is to have a child process queue, which only starts a new process once any current process has finished. Something like:

```typescript
import * as cp from 'child_process'

class ProcessQueue{
    currentProcess: cp.ChildProcess | undefined = undefined
    queuedCommand: string[] | undefined = undefined

    queueProcess(command: string[]) {
        this.queuedCommand = command
        this.startQueuedProcess()
    }

    startQueuedProcess() {
        if (this.queuedCommand !== undefined) {
            if (this.currentProcess === undefined) {
                this.currentProcess === cp.spawn(
                    'sphinx-build', this.queuedCommand
                )
                this.queuedCommand = undefined
                this.currentProcess.on('exit', (exitCode, signal) => {
                    this.currentProcess = undefined
                    this.startQueuedProcess()
                })
            }
        }

    }
}
```

**Comment by lextm** [comment]
> You are simply spawning a child process, which you own, that calls the `sphinx-build` python entry point. If you kill this process, there shouldn't be any problem.

Killing a process while it is working on document generation is not as safe as you might have thought. Sphinx is a complex project, so I won't assume I can simply go ahead and just kill the process.

Thanks for sharing the code snippet, but it is too ideal to assume this extension only spawns processes.

Anyway, I started to work on this item, so as to better suppress unnecessary preview process in the background.

**Comment by lextm** [comment]
No longer valid after switching to esbonio.
