### ISSUE TITLE
Spurious underlining in RST tables

### ISSUE THREAD

**Issue by rfjakob** [vscode-restructuredtext/vscode-restructuredtext#15]
Every second column is being underlined, making the tables hard to work with, because the underlining masks actual underlines. Is this a bug or a feature? ;)

Table RST code:
```
+---------+-------+--------+
| Example | Table | Header |
+=========+=======+========+
| Lorem   | Ipsum | Dolor  |
+---------+-------+--------+
| Sit     | Amet  | Lorem  |
+---------+-------+--------+
| Ipsum   | Dolor | Sit    |
+---------+-------+--------+
```

Rendering in vscode:
![rst-rable](https://cloud.githubusercontent.com/assets/286847/16517546/4331f8c4-3f7e-11e6-8d01-5d78e7449da8.png)

**Comment by rfjakob** [comment]
Rendering in Sublime Text:
![sublime](https://cloud.githubusercontent.com/assets/286847/16517731/5617320a-3f7f-11e6-8f8e-a0bb7f059eed.png)

**Comment by lextm** [comment]
Can you reproduce this issue after uninstalling this extension? If so, this issue should be reported to VSCode, https://github.com/Microsoft/VSCode

**Comment by rfjakob** [comment]
No, with the extension uninstalled there is no highlighting at all for rst.

<img width="355" alt="vscode-no extensions" src="https://cloud.githubusercontent.com/assets/286847/16544533/9645a3e8-410a-11e6-8a46-e919506c490b.PNG">

**Comment by lextm** [comment]
Now it is part of 0.0.13 release. You can update the extension in VSCode and check it out.

**Comment by rfjakob** [comment]
Tested and works! Awesome, thanks!!
