### ISSUE TITLE
Install instructions are incomplete

### ISSUE THREAD

**Issue by fulldecent** [vscode-restructuredtext/vscode-restructuredtext#150]
The install instructions are listed as: 

>  ...well. VS Code can't copy past Marketplace info. But there are only 4 steps.

But following these instructions are insufficient to actually use vscode-restructuredtext. Please include the full install instructions there.

**Comment by lextm** [comment]
The 4 steps are all you needed to install the extension.

If your goal is to configure dependencies for the first time, there is already a link to guide you through. Steps for such are lengthy so they won't be included in readme.

**Comment by fulldecent** [comment]
Test case:

1. Follow install instructions
2. Open http://docutils.sourceforge.net/docs/user/rst/demo.txt

This produces an error:

<img width="1489" alt="Screen Shot 2019-03-18 at 9 10 13 PM" src="https://user-images.githubusercontent.com/382183/54573326-49abf500-49c2-11e9-8ade-3337764fe129.png">

**Comment by lextm** [comment]
1. That's a warning, not an error.
1. The message explains what exactly happens and how to fix.

If you look for more information, https://docs.restructuredtext.com is the documentation site.

**Comment by fulldecent** [comment]
The message that shows is:

> Cannot lint /Users/williamentriken/Desktop/doc.rst. The executable 'doc8' was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable
