### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ssteinerx** [vscode-restructuredtext/vscode-restructuredtext#151]
- Issue Type: `Performance`
- Extension Name: `restructuredtext`
- Extension Version: `105.0.0`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.33.0-insider`

[lextudio.restructuredtext-unresponsive.cpuprofile.txt](https://github.com/vscode-restructuredtext/vscode-restructuredtext/files/2975284/lextudio.restructuredtext-unresponsive.cpuprofile.txt)

**Comment by lextm** [comment]
Might be related to #29 but without a reliable way to reproduce it, troubleshooting would be impossible.
