### ISSUE TITLE
doc8 configuration is not read from project directory

### ISSUE THREAD

**Issue by flying-sheep** [vscode-restructuredtext/vscode-restructuredtext#154]
### Environment
- Extension version: 106.0.0
- Visual Studio Code version: 1.33.0
- Operating System version: Arch Linux (up-to-date. It’s a rolling release)
- Python version: 3.7.3
- sphinx version: 1.8.5
- A sample of conf.py or its important fragments: N/A

### Setup
I have (depending on the project) a `tox.ini` or a `doc8.ini` in my project directory. The file contains a `[doc8]` section in it. The section specifies either `ignore=D001` or `max-line-length=160`.

`doc8` invoked from the terminal in the project directory works fine and reads this config. Long lines are ignored or only considered long if longer than 160 characters (depending on the setup value)

### Expected behavior
The extension should invoke doc8 in a way that it does the same by default.

### Actual behavior
VS Code gives me diagnostics saying “D001 Line too long”.

### Rationale
There should be a sane default that “just works” in the way the CLI tool does. I shouldn’t have to go into the extension settings, specifically because there’s no way to specify `restructuredtext.linter.extraArgs` globally to make it work. I’d have to do a per-project setup to set either

```json
"restructuredtext.linter.extraArgs": ["--config", "${workspaceFolder}/doc8.ini"]
```

or

```json
"restructuredtext.linter.extraArgs": ["--config", "${workspaceFolder}/tox.ini"]
```

I’d have to do this on each machine or commit my `.vscode` directory

**Comment by lextm** [comment]
Switched to rstcheck in #203 so it is time to close this.
