### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by briglx** [vscode-restructuredtext/vscode-restructuredtext#155]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 107.0.0
- [x] Visual Studio Code version: 1.33.1
- [x] Operating System version: 10.0.17763 build 17763
- [x] Python version: 3.5.6
- [x] sphinx version: 2.0.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
ctrl + shift + r should preview the document

**Actual behavior**
ctrl + shift + r  throws PermissionError: [Errno 13] Permission denied:

**Detailed Steps to reproduce the problem**
Create project in folder with space. Use python conda environment.

c:\Users\username\OneDrive - Microsoft\src\projectname\README.rst

Running cmd: "C:\Users\username\Anaconda3\envs\projectname\python.exe" C:\Users\username\.vscode\extensions\lextudio.restructuredtext-107.0.0\python\preview.py c:\Users\username\OneDrive - Microsoft\src\projectname\README.rst

Looks like the path to the file needs to include " in case there is a space.

Error is: PermissionError: [Errno 13] Permission denied: 'c:\\Users\\username\\OneDrive'

**Comment by lextm** [comment]
Thanks. Just published 108.0.0 with the fix.
