### ISSUE TITLE
Preview out of sync

### ISSUE THREAD

**Issue by HIAB-vesteel** [vscode-restructuredtext/vscode-restructuredtext#157]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version:
- [X] Visual Studio Code version: 1.33.1
- [X] Operating System version: Windows 7
- [X] Python version: 3.6.6
- [X] sphinx version: 1.8.4
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
When scrolling document the preview Window is either sync or (feature request) in detach mode where the windows can scroll independently.

**Actual behavior**
The preview windows is lagging far behind not showing correct information.

**Detailed Steps to reproduce the problem**
Install plugin. Create long file with tables..

**Comment by lextm** [comment]
Duplicate to #121 . You might refer to that thread to disable synchronization.
