### ISSUE TITLE
File name is truncated

### ISSUE THREAD

**Issue by mpachis** [vscode-restructuredtext/vscode-restructuredtext#158]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 108.0.0
- [ ] Visual Studio Code version: 1.33.1
- [ ] Operating System version: Windows 10
- [ ] Python version: 3.7.2
- [ ] sphinx version: 2.0.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
HTML preview of the .rst file. when clicking on preview pane

**Actual behavior**
Error returned "file not found". It does look in the correct directory however the file name is truncated. For example previewing a file named "README.rst" the file is returned as "ME.rst". Each file is truncated a different number of characters. For example a file named "AUTHORS.rst" is returned as "ORS.rst". 

I can see in the build directory and the html files were built and correctly named.

**Detailed Steps to reproduce the problem**
It occurs on every file preview request.

**Comment by lextm** [comment]
Truncation happens if `confPath` is wrong. Make sure you select the right path,

https://docs.restructuredtext.net/articles/configuration.html#live-preview

**Comment by mpachis** [comment]
That was it, thanks.

Michael
