### ISSUE TITLE
"Linter doc8 not installed" even though it is available in my $PATH

### ISSUE THREAD

**Issue by chrish42** [vscode-restructuredtext/vscode-restructuredtext#159]
I install all the linters and tools I use for Python each in a separate, isolated virtualenv (via pipx). The commands (e.g. "doc8", etc.) are then made available in my $PATH. However, I keep getting "linter doc8 not installed. Install now?" prompts when editing .rst files, so it looks like the heuristic used to figure out if a doc8 is installed looks in the virtualenv of the package only. Would it be possible to look into the $PATH by default for linters and not just in the virtualenv? Thank you!

**Environment**
- [x] Extension version: 109.0.0
- [x] Visual Studio Code version:
- [x] Operating System version: macOS 10.14.5
- [x] Python version: 3.7.3

**Comment by lextm** [comment]
$PATH is only used if you have neither linter path nor Python path set,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/src/features/rstLinter.ts#L24

If you set either of them, $PATH is ignored.

**Comment by Xarkam** [comment]
Hello, I have same problem
```
{
	"resource": "/c:/Developpement/Base_Doc/source/installation.rst",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "C:\\Python\\python.exe: Error while finding module specification for 'doc8.main' (ModuleNotFoundError: No module named 'doc8')",
	"source": "restructuredtext",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1.7976931348623157e+308
}
```
But, doc8 is available
![image](https://user-images.githubusercontent.com/331816/61058073-d443b480-a3f6-11e9-83af-5a68995b83cd.png)

Operating system: Windows 10 x64.
Extension version: 111.0.0
vscode: 1.36.1
python: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05)
doc8 version: 0.8.0
