### ISSUE TITLE
Sphinx Language support

### ISSUE THREAD

**Issue by jgossage** [vscode-restructuredtext/vscode-restructuredtext#160]
As stated in the documentation, this project relies on and makes use of Sphinx. Sphinx uses a super-set of RST as its' markup language and the documentation does not make it clear whether the full Sphinx markup is supported.

**Comment by lextm** [comment]
It is difficult to assert how much of Sphinx syntax is supported, as VSCode syntax engine has its own limitation. The syntax we use was ported from TextMate.

Related to #142.

**Comment by lextm** [comment]
Due to #313 this extension no longer provides syntax highlighting.

Close this old discussion.
