### ISSUE TITLE
Hyperlinks to local `.html` files should open in the previewer.

### ISSUE THREAD

**Issue by max-sn** [vscode-restructuredtext/vscode-restructuredtext#161]
**Environment**
- [v110.0.0] Extension version:
- [1.35.1] Visual Studio Code version:
- [Ubuntu 16.04] Operating System version:
- [3.5.2] Python version:
- [2.1.1] sphinx version:

**Expected behavior**
With multi-page documentation files, I would expect that clicking a hyperlink to a local `.html` file inside the previewer, would open the linked file in the previewer in the same tab, similar to how a web browser would handle it.

**Actual behavior**
When clicking a hyperlink to a local `.html` file, the linked file is opened as raw html in a new tab. 

**Detailed Steps to reproduce the problem**
1. Create a multi-page reST documentation project. 
2. Include the page(s) in your `index.rst`.
3. Open `index.rst` and generate a preview.
4. Click a link to the included file, the raw `.html` file will open in a new tab.

**Comment by lextm** [comment]
It is VSCode behavior.

**Comment by MaxSnippe** [comment]
Thanks for your response. I do not have any experience with developing VSCode extensions, but it seems to me that this should be possible. For example, the [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/) extension allows hyperlinking between previews. I cannot judge whether this is feasible, but maybe you can after having a look at the referenced extension.

**Comment by lextm** [comment]
Thanks. Then I leave it open.

**Comment by adam-grant-hendry** [comment]
@max-sn I concur.

**Comment by lextm** [comment]
Close it now, as starting from 190.1.17 the live preview is removed.
