### ISSUE TITLE
Prompt to install doc8 even with "restructuredtext.linter.run": "off"

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#163]
**Environment**
- Extension version: 112.0.0
- Visual Studio Code version: 1.36.1
- Operating System version: Windows 10.0.18362.239 x64
- Python version: 3.7.4 64-bit
- sphinx version: 2.1.2

**Expected behavior**
You only get prompted to install doc8 when the linter is enabled in the configuration (`restructuredtext.linter.run`).

**Actual behavior**
You get prompted to install doc8 even when `restructuredtext.linter.run` is set to `off`.

**Detailed Steps to reproduce the problem**
1. Set `restructuredtext.linter.run` to `off`.
2. Run in a Python environment without doc8 installed, e.g. a new no-site-package virtualenv.
2. Open an "rst" file.

**Comment by lextm** [comment]
If you don't need linter, click "Do not show again" when it prompts.

`restructuredtext.linter.run` is a completely irrelevant setting.
