### ISSUE TITLE
Preview has no styles/fonts and no pictures

### ISSUE THREAD

**Issue by reaseno** [vscode-restructuredtext/vscode-restructuredtext#164]
**Environment**
- [ ] Extension version: 113
- [ ] Visual Studio Code version: 1.36.1
- [ ] Operating System version: Win10-1809
- [ ] Python version: 3.72
- [ ] sphinx version: 1.8.3

**Expected behavior**
Preview should have same appearance as in the browser.

**Actual behavior**
Preview has no styles/fonts and no pictures.

I get no errors in the extension log.

I configured the paths to the syles like this:

```
    "restructuredtext.styles": [
        "C:\\Users\\Mkk\\corp\\Documentation-temp\\de\\_static\\corp.css",
        "C:\\Users\\Mkk\\corp\\Documentation-temp\\de\\_static\\css\\theme.css"
    ],
```

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview or language server based actions but recommends the Esbonio extension to be used instead. Close this issue now.
