### ISSUE TITLE
[Feature request] Write rst faster

### ISSUE THREAD

**Issue by NinoFloris** [vscode-restructuredtext/vscode-restructuredtext#17]
I would love to see options to speed up things like creating section headers as this is slow without tools

**Comment by lextm** [comment]
Thanks for the suggestion. It heavily depends on the service provided by VSCode, so let's record it now and revisit in a few weeks.

**Comment by lextm** [comment]
Closed via #66 . Type the section header and then use `Ctrl+=` (on Mac `Cmd+=`) to insert the header separators.
