### ISSUE TITLE
CSS and Javascript files are not loaded in the Preview

### ISSUE THREAD

**Issue by chrisjaquet** [vscode-restructuredtext/vscode-restructuredtext#171]
Greetings,

With the latest update to VSCode 1.37, the preview no longer uses the css files for the relevant sphinx theme, e.g. bizstyle.

Using the developer console I see the following error every time I save my document:
`Webview: Cannot load resource outside of protocol root`

Pausing the debugger at the point where the error occurs (in `webviewProtocols.ts:27`), the url giving problems is `"vscode-resource:\d:\Temp\ReST\source\_build\html\_static\bizstyle.css"`.

I suspect it has something to do with this change: https://code.visualstudio.com/updates/v1_37#_webviewtowebviewresource-and-webviewcspsource

Note that the Webview error occurs for all the CSS files and any javascript files that the generated output refers to. This is possibly related to #126 

**Environment**
- [x] Extension version: v113.0.0
- [x] Visual Studio Code version: 1.37
- [x] Operating System version: Windows 10 (19.03)
- [x] Python version: 3.7.2
- [x] sphinx version: 2.1.2
- [x] A sample of conf.py or its important fragments:
```
# Use default created by sphinx-quickstart and then change
html_theme = 'bizstyle'
```

**Expected behavior**
HTML Preview renders the preview with the CSS styling, same as in normal web browser, same as in vscode 1.37

**Actual behavior**
CSS is not loaded, nor is any other javascript resource used by the generated output.

**Detailed Steps to reproduce the problem**

This is easily reproduced by 
1. Create a new folder
2. In this folder run `sphinx-quickstart` and use defaults.
3. Open the folder in vscode and configure the extension if necessary.
4. Edit the `conf.py` file and change the theme: `html_theme = 'bizstyle'`
5. Open preview and see that there is no styling.

**Comment by chrisjaquet** [comment]
A quickfix (for windows) in `src/rstEngine.ts`, in the function `fixLinks`, replace 
```
const newUrl = [
    p1,
    process.platform === 'win32' ? 'vscode-resource:\\' : 'vscode-resource:',
    path.join(
        path.dirname(documentPath),
        p2,
    ),
    p3,
].join('');
return newUrl;
```
with
```
let newPath = Uri.file(path.join(path.dirname(documentPath), p2));
const newUrl = [
    p1,
    newPath.with({ scheme: 'vscode-resource' }).toString(true),
    p3,
].join('');
return newUrl;
```

I have only tested this on windows, with a simple test project.

**Comment by rizickus** [comment]
Any official fixes? Our team also bumped into this issue. This extension is super useful of writing our documentation.

**Comment by lextm** [comment]
Fixed in latest release.
