### ISSUE TITLE
Can you use pandoc instead of having a hard dependency on sphinx?

### ISSUE THREAD

**Issue by gsemet** [vscode-restructuredtext/vscode-restructuredtext#172]
Hi. Maybe you already tried it, but I would prefere having this extension use a system's installation of pandoc instead of having to install a sphinx in my virtualenv. Pandoc is way simpler to use and could render your rst file to html way faster:

```bash
$ pandoc -f rst -t html -o README.html README.rst
```

Thanks anyway for your extension, I won't use the live preview of rst file that much but the other features are cool.

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/preview.html#rendering-engines

Sphinx is optional.
