### ISSUE TITLE
Sphinx preview always syncs to the bottom of the generated HTML file

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#173]
**Environment**
- [ ] Extension version: 113.0
- [ ] Visual Studio Code version: 1.37.0
- [ ] Operating System version: Ubuntu 18.04
- [ ] Python version: 3.6.8
- [ ] sphinx version: 1.7.8
- [ ] A sample of conf.py or its important fragments: I don't know what might be relevant...

**Expected behavior**

The preview should sync roughly to where I'm editing in the .rst source

**Actual behavior**

The preview always shows the bottom of the generated HTML in the preview

**Detailed Steps to reproduce the problem**

Open .rst file
Open preview file to the right
Move the scrollbar in the preview to the right
Navigate in the .rst, the preview pops to the bottom

When I look in the log, I don't see anything untoward, but I don't see that it contains information that would allow the preview to scroll to a position that corresponds to where I'm editing either:

```
[Log - 7:55:26 AM] Document line count: 285; element count: 0
[Log - 7:55:31 AM] provideTextDocumentContent
{
  "source": "file:///[deleted]/index.rst",
  "line": 15,
  "lineCount": 285,
  "scrollPreviewWithEditor": true,
  "scrollEditorWithPreview": true,
  "doubleClickToSwitchToEditor": true,
  "disableSecurityWarnings": false
}
[Log - 7:55:31 AM] Compiling file: [deleted]/index.rst
Sphinx conf.py directory: /home/oyvind/docs/source
Sphinx html directory: /home/oyvind/docs/source/_build/html
Compiler: python3 -m sphinx -b html . "/home/oyvind/docs/source/_build/html"
Working directory: /home/oyvind/docs/source
HTML file: [deleted]/index.html
[Log - 7:55:33 AM] Document line count: 285; element count: 0
[Log - 7:55:34 AM] updateForView
{
  "rstFile": {
    "$mid": 1,
    "fsPath": "[deleted]/index.rst",
    "external": "file:///[deleted]/index.rst",
    "path": "/[deleted]/index.rst",
    "scheme": "file"
  }
}

```

**Comment by lextm** [comment]
Duplicate to #121
