### ISSUE TITLE
If the workspace folder and conf.py folder is identical, sphinx will refuse to generate output

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#174]
**Environment**
- [ ] Extension version: 113.0.0
- [ ] Visual Studio Code version: 1.37.1
- [ ] Operating System version: Ubuntu 18.04
- [ ] Python version: 3.6.8
- [ ] sphinx version: 2.2.0
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

Preview should work when opening a visual studio code workspace in the folder of a conf.py

**Actual behavior**

Preview fails:

```
Error
Command failed: python3 -m sphinx -b html . "[path to conf.py]"

Application error:
Source directory and destination directory cannot be identical

Error: Command failed: python3 -m sphinx -b html . "[path to conf.py]"

Application error:
Source directory and destination directory cannot be identical
```

**Detailed Steps to reproduce the problem**

1. cd <folder of conf.py>
2. "code ."
3. Open preview
4. Error message above

**Comment by lextm** [comment]
What does your `settings.json` look like?

`python3 -m sphinx -b html . "[path to conf.py]"` indicates that your Sphinx setting was incorrect. You should not set a html directory or you should set it to a valid place (not the same as the source directory),

https://docs.restructuredtext.net/articles/configuration.html#sphinx-build-path-25-0-and-above

**Comment by oharboe** [comment]
That's that worked.

The additional caveat is that the build folder must be a sub-folder of the vscode workspace, or the preview doesn't work correctly: the built-in HTML browser refuses to show images. I presume it's a security thing.
