### ISSUE TITLE
[Feature request] Button for fix position of preview editor 

### ISSUE THREAD

**Issue by roeeyn** [vscode-restructuredtext/vscode-restructuredtext#176]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: v114.0.0
- [x] Visual Studio Code version:  1.37.1
- [x] Operating System version: MacosMojave 10.14.6
- [x] Python version: 3.7
- [x] sphinx version: 2.1.2
- [ ] A sample of conf.py or its important fragments: NA

**Expected behavior**
As syncing sometimes not working ok, I would love to have a button or something to fix the position of the preview, while I change some code in the rst file.

**Actual behavior**
If syncs not working ok (mainly because of font sizes), the preview just jumps somewhere else and is very difficult for writing and having the preview in the same visual space.

**Detailed Steps to reproduce the problem**
Just use a bigger font with a big file, and the preview gets kind of messy.

**Comment by lextm** [comment]
You might refer to #121 to disable sync.

**Comment by roeeyn** [comment]
I'm so sorry. I searched for hours and didn't find the option. Thanks for the help.
