### ISSUE TITLE
Pointlessly frequent preview rebuilds (every 300 ms!) even if no change was saved

### ISSUE THREAD

**Issue by memeplex** [vscode-restructuredtext/vscode-restructuredtext#179]
**Environment**

- Extension version: 114.0.0
- Visual Studio Code version: 1.38.1
- Operating System version: Ubuntu 19.04
- Python version: 3.7.3
- sphinx version: 2.2.0
- A sample of conf.py or its important fragments: no conf.py

**Expected behavior**

Preview is updated only if file changes.

**Actual behavior**

Preview is updated every `updateDelay` ms (300 ms by default) while one is typing. I mean sphinx is run on the (unsaved hence unchanged) file to produce a new (identical) html output. This is pointless. If you change `updateDelay` to, say, 5000 ms then you have to wait 5 seconds after saving to see the updated preview, so that's no workaround. Moreover,  mathjax is barely usable because it's formulas are re-rendered all the time.

Besides `updateOnTextChanged` does nothing. You can't disable it. It's just a dummy configuration variable that doesn't seem to be actually used anywhere.

I believe this is a serious regression. You can't have everything refreshed every 300ms by default, and some dynamic stuff in the page rearranging  itself all the time. Furthermore, there is no way to disable this because `updateOnTextChanged`  is broken.

**Detailed Steps to reproduce the problem**

1. Create a rst file
2. Open its preview
3. Open the output log
4. Start typing in the file
5. See how it's pointlessly rebuilt every updateDelay ms no matter whether you saved it or not

**Comment by memeplex** [comment]
This is probably related https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/104.

Regarding the now useless `updateOnTextChanged` setting, its usages were removed in https://github.com/vscode-restructuredtext/vscode-restructuredtext/commit/a1103c3f09685337635e70ff5fcff24c3acc7a76#diff-45327f86d4438556066de133327f4ca2 but apparently you forgot to remove the setting (and its documentation).

**Comment by memeplex** [comment]
The problem I see here is that in preview.js `doUpdate` checks for `this.currentVersion.version === document.version` which looks at changes in the document that are not necessarily saved to disk. This might be ok, but then in rstDocumentContent `provideTextDocumentContent` doesn't save the document or produce an auxiliary document from the editor contents. So the should-update check is looking at a different thing (editor contents) than the one that ultimately gets the update (file contents).

I could write a PR that fixes this but first I would like to know what do you think. Should I save the editor to a temporary file in `provideTextDocumentContent`?

**Comment by memeplex** [comment]
I would be very simple if you could get the document.version in disk. But all you get is a dirty flag. Catching save events to track disk-versions seems not only ugly but also not very robust, since files are initially open without being saved yet and, moreover, could change outside the editor.

**Comment by memeplex** [comment]
Maybe this could lead to a solution. I've wrapped the part of `doUpdate` that does an effective build & update inside a check for not dirty:

```typescript
        if (!document.isDirty) {
            this.currentVersion = { resource, version: document.version };
            const content = await this._contentProvider.provideTextDocumentContent(document, this._previewConfigurations, this.line, this.state);
            if (this._resource === resource) {
                this.editor.title = RSTPreview.getPreviewTitle(this._resource, this._locked);
                this.editor.iconPath = this.iconPath;
                this.editor.webview.options = RSTPreview.getWebviewOptions(resource);
                this.editor.webview.html = content;
            }
        }
```

This ensures you're always tracking the right version of the document (the one synced to disk).  Also, I believe it could be more performant to replace:

```typescript
        vscode.workspace.onDidChangeTextDocument(event => {
            if (this.isPreviewOf(event.document.uri)) {
                this.refresh();
            }
        }, null, this.disposables);
```

with an `onDidSaveTextDocument` handler.

**Comment by memeplex** [comment]
@lextm I would like to get this working ASAP because in a couple of weeks we're migrating all documentation to sphinx at work and almost everybody is using vscode these days here. I would like to ask my employer to either:

1. Give me some time in order to write a PR (but then I will need some extra feedback from you in order to understand how do you want to approach the issue).
2. Post a bounty to you so that you work on the issue.

What do you think?

**Comment by lextm** [comment]
I am fully occupied on other stuffs, so you'd better go option 1.

**Comment by cuihantao** [comment]
This issue is also affecting me. I have to set the preview rebuild time to 5000 ms to avoid freezing my macOS. I was able to see hundreds of sphinx build processes running if the rebuild time is set to 300 ms.

**Comment by FlashSheridan** [comment]
How about Dead Preview, i.e. an option to update the preview manually?

**Comment by lextm** [comment]
Completely removed the refresh after switching to esbonio.
