### ISSUE TITLE
Preview fails, path is truncated

### ISSUE THREAD

**Issue by RichWellum** [vscode-restructuredtext/vscode-restructuredtext#180]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: : 114.0.0
- [ ] Visual Studio Code version: : 1.38.1
- [ ] Operating System version: OSX 10.14.6
- [ ] Python version: 3.7.4
- [ ] sphinx version: 1.8.5
- [ ] A sample of conf.py or its important fragments:

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
#    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
#    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
#    'sphinx.ext.napoleon',
]

- [ ] settings.json:
{
    "restructuredtext.experimental": false,
    "restructuredtext.languageServer.disabled": false,
    "restructuredtext.builtDocumentationPath" : "${workspaceRoot}/_build/html",
    "restructuredtext.confPath"               : "${workspaceRoot}",
    "restructuredtext.updateOnTextChanged"    : "true",
    "restructuredtext.updateDelay"            : 300,
}

**Expected behavior**
Preview to display the generated HTML

**Actual behavior**
Fails with the following output:

Log - 4:00:59 PM] Compiling file: /Users/rwellum/cloud-enable/README.rst
Sphinx conf.py directory: /Users/rwellum/cloud-enable/docs
Sphinx html directory: /Users/rwellum/cloud-enable/_build/html
Compiler: python -m sphinx -b html . "/Users/rwellum/cloud-enable/_build/html"
Working directory: /Users/rwellum/cloud-enable/docs
HTML file: /Users/rwellum/cloud-enable/_build/html/ME.html
Description: <p>Cannot read preview page "/Users/rwellum/cloud-enable/_build/html/ME.html".</p>                        <p>Possible causes are,</p>                        <ul>                        <li>A wrong "conf.py" file is selected.</li>                        <li>Wrong value is set on "restructuredtext.builtDocumentationPath".</li>                        </ul>
Error: Error
ENOENT: no such file or directory, open '/Users/rwellum/cloud-enable/_build/html/ME.html'
Error: ENOENT: no such file or directory, open '/Users/rwellum/cloud-enable/_build/html/ME.html'

It looks like the path(s) are incorrect:

/Users/rwellum/cloud-enable/_build/html/ME.html
Should be:
/Users/rwellum/cloud-enable/_build/html/README.html

Another example:
/Users/rwellum/cloud-enable/_build/html/ect-process.html
Should be:
/Users/rwellum/cloud-enable/_build/html/project-process.html

This happens in subdirectories too:

/Users/rwellum/cloud-enable/_build/html/ning/README.html'
Should be:
/Users/rwellum/cloud-enable/_build/html/scanning/README.html'

It doesn't seem like an issue with absolute path etc - more like the path is being cut somehow.

**Detailed Steps to reproduce the problem**
Just basic operation as above, removing all the restructuredtext setting made no difference. Also adding absolute path to conf.py didn't help

**Comment by lextm** [comment]
Please select the right preview engine from the dropdown list,

https://docs.restructuredtext.net/articles/configuration.html#live-preview

You shouldn't modify `settings.json` right now, as choosing the right option from that list will allow this extension to generate the right settings itself.

**Comment by RichWellum** [comment]
I don't see or receive a dropdown list - unless I am missing it. The page says it 'might' show a dropdown ("By triggering a preview, this extension might show a list of options"). I don't get a status bar indication either.

Gone through the full documentation now, but nothing jumping out. Relatively new to vscode so maybe missing where the list of options is displayed.

**Comment by RichWellum** [comment]
I finally found it, and I changed it to docutils from Sphinx and now I have a valid preview.

**Comment by rockboynton** [comment]
@RichWellum @lextm  I am having the same issue, but switching to docutils previewer didn't work, instead I get:
```
Command failed:  "c:\Users\goali\.vscode\extensions\lextudio.restructuredtext-116.0.0\python\preview.py" "c:\proj\grips\HISTORY.rst"

Error: Command failed:  "c:\Users\goali\.vscode\extensions\lextudio.restructuredtext-116.0.0\python\preview.py" "c:\proj\grips\HISTORY.rst"

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

I would like to use sphinx, and it works for the rst files in the docs directory, but not the files in the root directory.
The issue appears to be **It truncates the first 4 characters of the rst file**
e.g. `HISTORY.rst` becomes `ORY.html` and `README.rst` becomes `ME.html` an `CONTRIBUTING.rst` becomes `RIBUTING.html`

**Comment by rockboynton** [comment]
By the way I used the cookiecutter termplate `https://github.com/audreyr/cookiecutter-pypackage`

**Comment by kylecribbs** [comment]
> @RichWellum @lextm I am having the same issue, but switching to docutils previewer didn't work, instead I get:
> 
> ```
> Command failed:  "c:\Users\goali\.vscode\extensions\lextudio.restructuredtext-116.0.0\python\preview.py" "c:\proj\grips\HISTORY.rst"
> 
> Error: Command failed:  "c:\Users\goali\.vscode\extensions\lextudio.restructuredtext-116.0.0\python\preview.py" "c:\proj\grips\HISTORY.rst"
> 
> 	at ChildProcess.exithandler (child_process.js:303:12)
> 	at ChildProcess.emit (events.js:200:13)
> 	at maybeClose (internal/child_process.js:1021:16)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> ```
> 
> I would like to use sphinx, and it works for the rst files in the docs directory, but not the files in the root directory.
> The issue appears to be **It truncates the first 4 characters of the rst file**
> e.g. `HISTORY.rst` becomes `ORY.html` and `README.rst` becomes `ME.html` an `CONTRIBUTING.rst` becomes `RIBUTING.html`

Having the same issue...
