### ISSUE TITLE
citations with sphinx-bibtex

### ISSUE THREAD

**Issue by Nadano** [vscode-restructuredtext/vscode-restructuredtext#184]
How difficult would it be to have something like:

https://github.com/notZaki/PandocCiter
https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#Citations

for managing bibtex citations with sphinx-bibtex?

It would greatly help in making vscode an all-around tool for writing papers.

**Comment by lextm** [comment]
Pull requests are welcome, but I think it might end up as a separate extension.

**Comment by Nadano** [comment]
I asked notZaki for his opinion and he got something working very fast.

https://github.com/notZaki/PandocCiter/issues/9

He would like someone else to maintain it though.
