### ISSUE TITLE
Feature request: Grid table adds an empty row under the current one if "enter" is pressed

### ISSUE THREAD

**Issue by Nadano** [vscode-restructuredtext/vscode-restructuredtext#185]
I don't even know if it would be possible in vscode, but it would be great if hitting "enter" while in a cell could insert an empty row under the current one and move the pointer to the start of the cell in the new row. It would make the editing of tables basically the same as editing normal text, without bothering about the shape of the table.

I know list-tables are a thing, but for clarity in big documents having an actual table shape helps a lot.

**Comment by Nadano** [comment]
As a reference, markdown extended have some crazy functionality for tablets, maybe the code could be integrated here easily

https://github.com/qjebbs/vscode-markdown-extended

**Comment by lextm** [comment]
Technically Markdown parsing is quite simple, but far more difficult for reStructuredText.

**Comment by lextm** [comment]
Related to #76 .

The new table editor does have this functionality.
