### ISSUE TITLE
The preview jumps around as I type text

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#186]
**Environment**
- [ ] Extension version: v116.0.0
- [ ] Visual Studio Code version: 1.40.1
- [ ] Operating System version: Ubuntu 18.04
- [ ] Python version:  3.6.8
- [ ] sphinx version: 2.2.0
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

The preview should not scroll, as I disabled scrolling:

```
   "restructuredtext.preview.scrollEditorWithPreview": false,
    "restructuredtext.preview.scrollPreviewWithEditor": false
```

**Actual behavior**

When typing, the preview scrolls to what seems like a random place in the document, then after a couple of hops scrolls to the top of the document

**Detailed Steps to reproduce the problem**

1. Open an .rst file
2. Scroll the preview to a chapter that's a couple of pages down
3. Edit the text in this chapter
4. The preview jumps around a couple of times, then scrolls to the top

**Comment by JonathanLindsey** [comment]
I tested this with the file at https://github.com/vscode-restructuredtext/docs/blob/master/articles/configuration.rst and did not see that behavior with those 2 settings set.

However, my environment is different:
**Environment**
* [ ]  Extension version: v129.0.0
* [ ]  Visual Studio Code version: 1.50.1
* [ ]  Operating System version: Windows 10 2004
* [ ]  Python version:  3.8.5
* [ ]  sphinx version: 3.1.2

**Comment by oharboe** [comment]
When I use Extension version v129.0.0, the preview/editor does not jump around when I disable the scrolling. I did try the scrolling, but there appers to be little correlation between preview and the .rst file. This applies both ways.

The most important thing is that it's possible to disable scrolling, which works.

**Comment by JonathanLindsey** [comment]
The odd behaviour when scrolling is enabled is #121.

**Comment by oharboe** [comment]
Since I opened this issue and it's now fixed and I appear to have the access rights to close the issue, I'm closing the issue. Hope that's OK.

**Comment by hacker1024** [comment]
For anyone who came here because their editor intermittently scrolls to the top upon saving, disabling the `restructuredtext.preview.scrollEditorWithPreview` setting is a decent workaround.
