### ISSUE TITLE
Add Executable Path option for live preview

### ISSUE THREAD

**Issue by noonedeadpunk** [vscode-restructuredtext/vscode-restructuredtext#187]
**Environment**
- [x] Extension version: 116.0.0
- [x] Visual Studio Code version: 1.41.1
- [x] Operating System version: Ubuntu 18.04
- [x] Python version: 2.7, 3
- [x] sphinx version: 1.8.5
- [x] A sample of conf.py or its important fragments: https://opendev.org/openstack/openstack-ansible/src/branch/master/doc/source/conf.py

**Expected behavior**

It would be great to have an option to control python executable path for live preview as this will make possible to use virtualenvs and select python version to use

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/configuration.html

It is important to install Microsoft's Python extension and configure a valid Python installation to use. This extension simply reuses the relevant settings, and does not have its own.
