### ISSUE TITLE
the extension mistook the lines of a table that under a 'table' directive as headings...

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#189]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 116.0.0
- [ ] Visual Studio Code version: 1.41.1
- [ ] Operating System version: Windows 10 Version 10.0.17763.914, Ubuntu 19.10
- [ ] Python version: 3.7.5
- [ ] sphinx version: 2.2.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
the lines should not be hight-lightened as headings.

**Actual behavior**
the lines were high-lightned as headings.

**Detailed Steps to reproduce the problem**
```
.. table::
    :widths: 10 10 40

    +------------+------------+-----------+
    | Header 1   | Header 2   | Header 3  |
    +============+============+===========+
    | body row 1 | column 2   | column 3  |
    +------------+------------+-----------+
    | body row 2 | Cells may span columns.|
    +------------+------------+-----------+
    | body row 3 | Cells may  | - Cells   |
    +------------+ span rows. | - contain |
    | body row 4 |            | - blocks. |
    +------------+------------+-----------+

```
![table-line-high-light-error](https://user-images.githubusercontent.com/16525011/71610939-3cb66600-2bd0-11ea-8137-3b480a9030c3.png)

**Comment by noisnemid** [comment]
how about this RE rule to match the headings only?

```
^\s*(=|-|~|`|#|"|\^|\+|\*|:|\.|'|_|\+)\1{3,}$
```

**Comment by noisnemid** [comment]
P.S
this occurs only when the table was indented to a lower level.

**Comment by lextm** [comment]
I excluded the changes you made in #199 on this issue. More testing is needed.

**Comment by lextm** [comment]
Due to #313 this extension no longer provides syntax highlighting.

Close this old item.
