### ISSUE TITLE
Please review Python installation on this machine before using this extension.

### ISSUE THREAD

**Issue by mactsouk** [vscode-restructuredtext/vscode-restructuredtext#191]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 116.0.0
- [ ] Visual Studio Code version: 1.41.1
- [ ] Operating System version: macOS 10.15.2
- [ ] Python version: Python 3.7.6
- [ ] sphinx version: 2.2.11
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
I expect to get no notifications when editing .rst file.

**Actual behavior**
Each time I open vscode, I get the "Please review Python installation on this machine before using this extension." notification.

**Detailed Steps to reproduce the problem**
I just have to open a .rst file.

Thanks.

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features

You need to install Microsoft Python extension, and open up conf.py. Then that extension should prompt you to set up the relevant Python settings which this extension relies on.

**Comment by mactsouk** [comment]
@lextm Thanks!

**Comment by Melebius** [comment]
> You need to install Microsoft Python extension, and open up conf.py. Then that extension should prompt you to set up the relevant Python settings which this extension relies on.

@lextm  This helped me, too, but could the reST extension say _“You need to install Microsoft Python extension”_ directly, so we are not obliged to check GitHub for it? From the current message, I assumed it referred to Python installation on my machine literally (which works well for me) and not the VSCode Python extension (which I hadn’t installed).
