### ISSUE TITLE
Q: Where are the src codes about documentSymbolProvider and foldingProviders and documentLinkProviders?

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#192]
I noticed in ver 117's 'out' folder there's a 'documentSymbolProvider.js', but it seems that it doesn't make the outline view work, and there's not the 117's source code in this repo when I want to make some debug work for it.

**Comment by noisnemid** [comment]
@lextm why couldn't I find any code about 'DocumentSymbolProvider' around the source code?

After I tried to build the vsix via the following commands:
```
npm install
npm run compile
vsce package
```
and I changed the suffix of newly generated 'restructuredtext-117.0.0.vsix'  to 'zip' and could not find the 'documentSymbolProvider.js' under the out/features folder.

but if I installed the extension from the vscode's built-in ext manager from the marketplace, the file appears in the c:/users/***/.vscode/extensions/lextudio.restructuredtext-117.0.0/out/features/

and I downloaded the vsix pack manually from the marketplace website, and un-zip it, those 'documentsymbolprovider.js' and some other corresponded files were there under the folder 'out/features'

confusing...

Are these files added by the microsoft or ...? 

![Snipaste_2020-02-01_03-37-18](https://user-images.githubusercontent.com/16525011/73568862-3142ad00-44a4-11ea-9faa-a7c9acc28711.png)

**Comment by lextm** [comment]
Those files came from my local disk, as part of my initial attempt to investigate the relevant API. But it was never finished. I just noticed that I forgot to delete them all from the published extension.

**Comment by noisnemid** [comment]
Thanks so much for your replying!
