### ISSUE TITLE
Feature Request: jump between footnotes/cross-file links

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#193]
```
aaaa [1]_ 

.. rubric:: footnote
.. [1] aaaaabbbccc

```
when ctrl+left-mouse-btn-click on '[1]_', or ' .. [1] aaaaabbbccc', the cursor jumps between them.

same actions on the internal hyper link-pairs(cross-file refs)

in file1:

```
some text....

.. _text-1:

:ref:`note-1`

```

in file 2:

```
.. _note-1:

note-1
---------------------------------------------------------------
:Original: :ref:`original <text-1>`
notesssssssssssssssssssssssss
```

**Comment by lextm** [comment]
The Snooty language server does implement such jumps among files, so you can give it a try,

https://docs.restructuredtext.net/articles/configuration.html#intellisense

**Comment by lextm** [comment]
This should one day be made an esbonio feature.
