### ISSUE TITLE
Live preview might not work on Windows

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#20]
Tested only on macOS and Linux with VSCode 1.3.0.

Will test and fix Windows issues soon.

**Comment by lextm** [comment]
Verified that it works on Windows.

**Comment by kamranayub** [comment]
What did you need to do to make it work in Windows? My error says "make" is not a command or program.

![image](https://cloud.githubusercontent.com/assets/563819/18333177/7047cf3e-7532-11e6-901b-985d74599ff3.png)

**Comment by lextm** [comment]
@kamranayub can you share more details on how you get the "RTD sphinx template"? 

To set config.py path, you can follow

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#live-preview-settings

**Comment by kamranayub** [comment]
I just followed the tutorial on RTD: http://docs.readthedocs.io/en/latest/getting_started.html#write-your-docs

When you run `sphinx-quickstart` it generates the above folder structure.
