### ISSUE TITLE
Feature request: Ability to set the docutils writer

### ISSUE THREAD

**Issue by uyar** [vscode-restructuredtext/vscode-restructuredtext#200]
When using docutils for generating output, it would be nice to be able to set the writer that is going to be used. I'm working on some custom docutils writers (such as for impressjs and revealjs for example). This feature would make it possible to use such custom writers.

I've made a patch for that but since I'm not confident in vscode plugin development, I didn't dare to make a PR. Here's the patch:

https://github.com/uyar/vscode-restructuredtext/commit/c8481e2ccbcc82e42f547338493329a5eba0dd1e

**Comment by lextm** [comment]
I think it looks good. You can send a pull request for review.

**Comment by uyar** [comment]
OK, I have. I forgot to reference the issue number in the commit message. Thanks.

**Comment by lextm** [comment]
Closed via #201
