### ISSUE TITLE
vscode-restructuredtext can't recognize python3 in macOS

### ISSUE THREAD

**Issue by shootsoft** [vscode-restructuredtext/vscode-restructuredtext#204]
Not sure this is an issue in this plugin or vscode

My os is macOS Mojave 10.14.6

The default python /usr/bin/python is python2.7 

I'm using fish shell, I override path in fish shell with python 3.7, which when I run python it actually running in python 3.7. I got pip setup with python3.7 as well.

However after I installed vscode-restructuredtext, when I click "Preview" for a rst file, vscode kept saying "install docutils failed", asking me to install it manually.

When I do manual installation, because my pip is using python3, I installed without any issue. It still failing in vscode.

After a few struggling, I decided to install pip for python2. Pip2 was installed in a different path, I have to add it to PATH after python3. Amazingly it works this time!

**Comment by lextm** [comment]
Configuring Python can be hard, so I updated the guide a few days ago,

https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features

I think instead of changing your system PATH, you should consider Option 2.

**Comment by lextm** [comment]
Changed default to python3 in b2d5ed29217e60b3a4b15340cc4fc3e8163c90d3, which should avoid such issues if Python 3 is already installed.

**Comment by shootsoft** [comment]
> https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features

Thanks for updates.
