### ISSUE TITLE
Title overline too short with accented characters

### ISSUE THREAD

**Issue by lgarcin** [vscode-restructuredtext/vscode-restructuredtext#206]
**Environment**
- [ ] Extension version: 123.0.0
- [ ] Visual Studio Code version: 1.43.2
- [ ] Operating System version: Windows 10
- [ ] Python version: 3.8.2 64bit
- [ ] sphinx version:  2.4.4

**Expected behavior**

The following code should not trigger a warning.

```rst
====================
Chaînes de caractère
====================
```

**Actual behavior**

The linter triggers "Title overline too short" warning.

When I add an equal sign for each accented character, the warning is no more triggered.

```rst
======================
Chaînes de caractère
======================
```
It seems each accented character is accounted for twice.

**Comment by lextm** [comment]
Can you confirm that rstcheck is being used? If so, this issue should be reported to https://github.com/myint/rstcheck/issues

**Comment by lgarcin** [comment]
Yes, rstcheck 3.3.1 is being used. I am going to file an issue on their repo.

**Comment by lextm** [comment]
Tracked by https://github.com/myint/rstcheck/issues/66. Close this one.
