### ISSUE TITLE
Deactivate Snippets.

### ISSUE THREAD

**Issue by jaguarfi** [vscode-restructuredtext/vscode-restructuredtext#207]
It would be nice to have a `enable snippets` configuration in the settings of the VS Code extension.

**Environment**
- [ ] Extension version:
- [ ] Visual Studio Code version:
- [ ] Operating System version:
- [ ] Python version:
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
-> VSCode Settings
"Enable Snippets" : true

**Actual behavior**
The snippets are always active, and it is not possible to deactivate them from the editor.

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
I don't think VSCode gives its extensions such an option.
