### ISSUE TITLE
Option To Turn Off Syntax Highlighting

### ISSUE THREAD

**Issue by rmorshea** [vscode-restructuredtext/vscode-restructuredtext#210]
The fact that syntax highlighting for directives with pre-formatted text [is not supported](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/142) can be fairly prohibitive to readability. Thus, while that issue remains open it would be great to have an option to simply turn off syntax highlighting entirely.

**Comment by lextm** [comment]
It is impossible right now to provide an option to turn off TextMate based syntax highlighting.

Once we migrate to semantic highlighting, this can be revisited.
