### ISSUE TITLE
Stop modifying the workspace settings

### ISSUE THREAD

**Issue by pgerell** [vscode-restructuredtext/vscode-restructuredtext#212]
**Environment**
- [x] Extension version: 126.0.0
- [x] Visual Studio Code version: 1.45.0
- [x] Operating System version: Windows 10 build 19041.208
- [x] Python version: 3.7
- [x] sphinx version: 1.8.5
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
No version controlled files touched without explicit editing

**Actual behavior**
The entry  `"restructuredtext.workspaceRoot": "c:\\path\\to\\workspace"` is added to (or modified in) the workspace settings.
This is very annoying as you have to discard the changes every time you want to pull from git.
This line is also often committed by mistake and leads to merge conflicts as the actual path differs between users and for every clone of the repository.

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
Can you uninstall and reinstall 126.0.0? That should trigger another download of the latest language server, which should resolve this issue.

**Comment by pgerell** [comment]
> Can you uninstall and reinstall 126.0.0? That should trigger another download of the latest language server, which should resolve this issue.

That did resolve the issue
