### ISSUE TITLE
Step by Step Video Guide

### ISSUE THREAD

**Issue by GuokLiu** [vscode-restructuredtext/vscode-restructuredtext#214]
Sincerely thanks for your contributions to the VSCode extension.

Could you please provide a video guide from installing to how to use it?

I'm not sure if it works on my python 2.7 environment.

Thank you very much : )

**Comment by lextm** [comment]
You might follow the guide to get started. No plan to record video clips, as this extension does not require too much special configuration compared to other extensions. If any dependency is missing, now this extension is able to tell you and guide you through.

**Comment by GuokLiu** [comment]
Hi Lextm,
Sorry, I missed checking my email and Github.

Thanks for your timely reply and I finally figured it out.

And I wrote a blog for potential users who are not familiar with VSCode.

- https://guokliu.blog.csdn.net/article/details/106954082
- https://zhuanlan.zhihu.com/p/150604385

Hope the embedded figure helps those who are in need.

I super like this extension.

Thank you.
