### ISSUE TITLE
Error command failed when conf.py in docs folder

### ISSUE THREAD

**Issue by fjp** [vscode-restructuredtext/vscode-restructuredtext#215]
**Environment**
- [x] Extension version: v128.0.0
- [x] Visual Studio Code version: 1.46.1 
- [x] Operating System version: macOS Catalina 10.15.5 (19F101)
- [x] Python version: 3.7.7
- [x] sphinx version: 3.1.1
- [x] A sample of conf.py or its important fragments:

**Expected behavior**

I have a project where the `conf.py` is located inside a `/Users/fjp/project/docs/conf.py` folder and the `/Users/fjp/project/README.rst`. I've configured `settings.json`:

```
"restructuredtext.builtDocumentationPath": "/Users/fjp/project/docs/_build/html",
"restructuredtext.confPath": "/Users/fjp/project/docs",
```

When I try to preview the `README.rst` I get 

> Description:
> Cannot generate preview page.
> 
> Possible causes are,
> 
> Python is not installed properly.
> Sphinx is not installed properly (if preview uses "conf.py").
> Wrong value is set on "restructuredtext.sphinxBuildPath".
> A wrong "conf.py" file is selected.
> DocUtils is not installed properly (if preview uses docutils).
> Detailed error message
> Error
> Command failed: "python" -m sphinx -b html . "/Users/fjp/project/docs/_build/html"
> ...

Although I've set the path `restructuredtext.confPath` to `/Users/fjp/project/docs` the command uses `'.'`.

I am not sure exactly but there might be an issue with [rstEngine.ts#L82](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/28a18629a10b648704cf8611849f107bb32cac05/src/rstEngine.ts#L82)? The `cmd` seems to be always using `'.'` instead of the `restructuredtext.confPath` value.

**Comment by feslima** [comment]
Yeah, I've stumbled in this same issue here...

**Comment by lextm** [comment]
@fjp What's the contents of your `conf.py`? When a project is in `/Users/fjp/project/docs/`, I don't think you should have any .rst files in parent directories.

**Comment by fjp** [comment]
@lextm I am basically using [cookiecutter-pylibrary](https://github.com/ionelmc/cookiecutter-pylibrary) as template. I just found out that this template has a `docs/readme.rst` that includes a `README.rst` located at the project root folder and this readme file has the actual readme content in it. Trying to preview the `docs/readme.rst` works but previewing the `README.rst` (with the content in it) gives me the error:

> Cannot show preview page.
> Description:
> Cannot read preview page "/Users/fjp/project/python-nameless/docs/_build/README.html".
> 
> Possible causes are,
> 
> A wrong "conf.py" file is selected.
> Wrong value is set on "restructuredtext.builtDocumentationPath".
> Detailed error message
> Error
> ENOENT: no such file or directory, open '/Users/fjp/project/python-nameless/docs/_build/README.html'
> Error: ENOENT: no such file or directory, open '/Users/fjp/project/python-nameless/docs/_build/README.html'
> More Information
> Diagnostics information has been written to OUTPUT | reStructuredText panel.
> 
> The troubleshooting guide can be found at
> 
> https://docs.restructuredtext.net/articles/troubleshooting.html

**Comment by lextm** [comment]
Switching to esbonio partially solves this kind of issues. You can upgrade to release 176.0.0 and try again.
