### ISSUE TITLE
Disable "Select how to generate ..."

### ISSUE THREAD

**Issue by allefeld** [vscode-restructuredtext/vscode-restructuredtext#217]
I use the extension not for the preview or HTML generation features, but solely for the editor language support.

Whenever I switch to a tab containing an `.rst` file, the question "Select how to generate html from rest files" pops up. The answer is, I don't want the extension to generate HTML, but there is no such option. I also haven't found anything in the extension settings to get rid of this question.

Is there a way to disable "Select how to generate html from rest files"?
If not, would it be possible to add this?

I am actually using Sphinx, but with a slightly nonstandard configuration, so I fear that if I select a 'Sphinx' though I don't want to use it from the extension, it might mess with my setup.

**Environment**
- [ ] Extension version: 128.0.0
- [ ] Visual Studio Code version: 1.46.1
- [ ] Operating System version: Debian 10.4

**Comment by noisnemid** [comment]
ctrl+, vscode settings, find 'restructuredtext' section, find the following entries and turn them to disabled:

preview>doctutil> disabled.

preview>sphinx>disabled.

which means, check the option 'Flag to disable....' (when it's checked, the corresponding previewing engined will be disabled).

**Comment by lextm** [comment]
There is no such setting yet.

**Comment by allefeld** [comment]
I assumed it would write files. If that is not the case, no problem.

**Comment by lextm** [comment]
Made some changes in cfd7f9b20b3152fe4bacf1aa3b12d9c618f008e4. You can now follow the suggestion from @noisnemid to disable preview engines, and then no such message should be displayed.
