### ISSUE TITLE
Do not automatically create the file ${workspaceFolder}/.vscode/settings.json

### ISSUE THREAD

**Issue by jamilraichouni** [vscode-restructuredtext/vscode-restructuredtext#218]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 128.0.0
- [x] Visual Studio Code version: 1.47.0
- [x] Operating System version: macOS Catalina 10.15.5
- [x] Python version: 3.7.7
- [x] sphinx version: 3.1.2
- [ ] A sample of conf.py or its important fragments: not needed for this issue report

**Expected behavior**
When any `.rst` file is being opened, a file `${workspaceFolder}/.vscode/settings.json` shall **NOT** be created.

**Actual behavior**
I have a workspace root folder where I do not want to see any `.vscode/settings.json` file but every time when I open any `.rst` file, the extension creates that file with the following content:

```JSON
{
    "restructuredtext.confPath": "${workspaceFolder}/docs/source"
}
```

**Detailed Steps to reproduce the problem**

1. Create a folder inlcuding a Sphinx project stored in sub dir `docs`.
1. Ensure that there is just a file `.vscode/launch.json` but no file `.vscode/settings.json`.
1. Open a `.rst` file of the Sphinx project
1. Ensure that there is some entry comparable to the next listing in the global `.code-workspace` config file:

   ```JSON
   {
       "settings": {
           "restructuredtext.confPath": "${workspaceFolder}/docs/source"
       }
   }
```

1. Check if a file `.vscode/settings.json` has been created.

**Comment by jamilraichouni** [comment]
Okay, the file seems to be created in
`.vscode/extensions/lextudio.restructuredtext-128.0.0/out/features/utils/configuration.js`:

```Javascript
    static async saveAnySetting(configSection, value, resource, header = 'restructuredtext') {
        // await vscode_1.workspace.getConfiguration(header, resource).update(configSection, value);
        return value;
    }
```

When I comment the `await` the `settings.json` file is not being created.

**Comment by lextm** [comment]
That file is generated to help the live preview related code. No plan to revise in this area.

**Comment by jamilraichouni** [comment]
Understand. I do not use that feature. I installed your extension due to the language (syntax highlighting) support and when working on a Sphinx project I have sphinx-autobuild running in the background.

Anyway:

Why is the first root folder settings file (`.vscode/settings.json`) created with the setting

```json
{
    "settings": {
        "restructuredtext.confPath": "${workspaceFolder}/docs/source"
    }
}
```

although that is already being set in the workspace global settings stored in the file `.code-workspace`?

Can the extension first check the workspace global settings for that key/ value pair and if found:
Do not create a fresh `.vscode/settings.json` for the first workspace root folder.

**Comment by jamilraichouni** [comment]
I think that would be a solution without breaking anything since you always check, if the needed setting is given or not. In my case it is already given but just one level upwards in the VSCode settings hierarchy which is from top to down for settings:

1. `Code/User/settings.json`
1. `.code-workspace` file (where I have set that setting `"restructuredtext.confPath"`)
1. `.vscode/settings.json` (where the setting shall not be automatically introduced, if it exists on one of the higher levels (previous bullet points)

**Comment by lextm** [comment]
What you proposed cannot be accepted as it breaks the functionality.

About why your setting in other locations are not passed down to this extension, some further investigation is required.

**Comment by jamilraichouni** [comment]
I don't understand it, sorry :-) What do I propose that breaks the functionality?

**My understanding is:**

The extension needs the setting `"restructuredtext.confPath"` for the life preview function and I fully understand that.

**The settings concept of Visual Studio Code shall be considered/ followed:**

It shall not matter on which level of the settings hierarchy any setting is given, but if it is given on multiple levels, then the order for over-ruling is:

1. Prio: Root folder setting (`.vscode/settings.json`) overwriting
1. Prio: Workspace setting(`.code-workspace`)) overwriting
1. Prio: Global user setting (`Code/User/settings.json`)

This is at least my understanding after reading the [documentation for the interface](https://github.com/microsoft/vscode/blob/aa930e56196a1af56cae6d70b0e424fa0e99b824/src/vs/vscode.d.ts#L4674) `WorkspaceConfiguration` defined in the VSCode API.

That further investigation is also of interest for me. I'm not the most experienced extension developer but I code & maintain a personal one and like to know, if my above description is a correct interpretation of the settings flow through hierarchy levels.

Copied from the interface description they say for the interface `WorkspaceConfiguration`:

```typescript
	/**
	 * Represents the configuration. It is a merged view of
	 *
	 * - *Default Settings*
	 * - *Global (User) Settings*
	 * - *Workspace settings*
	 * - *Workspace Folder settings* - From one of the [Workspace Folders](#workspace.workspaceFolders) under which requested resource belongs to.
	 * - *Language settings* - Settings defined under requested language.
	 *
	 * The *effective* value (returned by [`get`](#WorkspaceConfiguration.get)) is computed by overriding or merging the values in the following order.
	 *
	 * ```
	 * `defaultValue`
	 * `globalValue` (if defined)
	 * `workspaceValue` (if defined)
	 * `workspaceFolderValue` (if defined)
	 * `defaultLanguageValue` (if defined)
	 * `globalLanguageValue` (if defined)
	 * `workspaceLanguageValue` (if defined)
	 * `workspaceFolderLanguageValue` (if defined)
	 * ```
	 * **Note:** Only `object` value types are merged and all other value types are overridden.
```

**Comment by jamilraichouni** [comment]
Has this been fixed?

**Comment by lextm** [comment]
No. Won't work on it.
