### ISSUE TITLE
[Feature request] Consider publishing to open-vsx.org

### ISSUE THREAD

**Issue by kir0ul** [vscode-restructuredtext/vscode-restructuredtext#219]
Hi,

Would you please consider publishing this extension to [open-vsx.org](open-vsx.org) in addition to the VS Code Marketplace?
The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks in advance :slightly_smiling_face:

**Comment by lextm** [comment]
A site like that can always aggregate VSIX packages from VS Code Marketplace. I don't think manual work like submitting again is worth the while.

**Comment by kir0ul** [comment]
I've no idea how all that work, I'm using [VSCodium](https://vscodium.com/) and found out that your extension was not available, so I just followed their advice [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).

**Comment by lextm** [comment]
You can click "Download Extension" link to grab the VSIX file from Marketplace, https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext

No plan to support VSCodium at all.
