### ISSUE TITLE
python.pythonPath is being deprecated -- this breaks preview for users using the Python extension's virtual environment handling

### ISSUE THREAD

**Issue by cpbotha** [vscode-restructuredtext/vscode-restructuredtext#222]
I have latest of everything as of today.

Please read https://devblogs.microsoft.com/python/python-in-visual-studio-code-may-2020-release/ and specifically the section "Coming Next: moving python.pythonPath out of settings.json"

It seems that this extension relies on `python.pythonPath` -- on my setup this broke restructuredtext preview although I have the correct virtual environment selected for the VS Code Python extension.

I have worked around this by re-adding python.pythonPath, but I am mentioning it here because other users might run into the same issue, and so that the authors / maintainers can think about updating their logic to use the currently selected Python environment.

**Comment by lextm** [comment]
Linked to https://github.com/microsoft/vscode-python/issues/2125
