### ISSUE TITLE
It doesn't work. No preview, no syntax highlighting. Nothing.

### ISSUE THREAD

**Issue by andersea** [vscode-restructuredtext/vscode-restructuredtext#225]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 129.0.0
- [x] Visual Studio Code version: 1.47.3
- [x] Operating System version: Windows 10 Pro 1909
- [x] Python version: 3.8.5 64amd
- [x] sphinx version: 3.2.1
- [ ] A sample of conf.py or its important fragments: ???

**Expected behavior**

It works.

**Actual behavior**

Nothing.

**Detailed Steps to reproduce the problem**

Python is installed in: ```C:\Program Files\Python38```
Scripts location: ```C:\Users\Anders\AppData\Roaming\Python\Python38\Scripts```
Required modules installed with: ```python -m pip install --user sphinx sphinx-autobuild rstcheck```

Environment variables -

(System) ```PATH=C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\```

(User) ```C:\Users\Anders\.poetry\bin;C:\Users\Anders\scoop\apps\ruby\current\gems\bin;C:\Users\Anders\scoop\apps\ruby\current\bin;C:\Users\Anders\scoop\shims;C:\Users\Anders\AppData\Roaming\Python\Python38\Scripts;C:\Users\Anders\AppData\Local\Microsoft\WindowsApps;C:\Users\Anders\AppData\Roaming\npm;```

Project is using poetry with this folder structure -
```
.\README.rst
.\docs\conf.py
.\docs\index.rst
.\docs\Makefile
.\docs\make.bat
.\docs\_build\
``` 

venv is using poetry standard path: ```C:\Users\Anders\AppData\Local\pypoetry\Cache\virtualenvs```

**Comment by lextm** [comment]
Syntax highlighting does not require any Python setup. So if it does not work, I can only assume you have a corrupt VSCode installation and I won't be able to help much on that.

**Comment by andersea** [comment]
Thanks for the suggestion. I did a complete wipe of VSCode, uninstalling the app, and manually deleted the appdata folder and the extensions folder and reinstalled. I now have syntax highlighting, so I am hopeful I can get the rest working as well.
