### ISSUE TITLE
What is the project maintenance status

### ISSUE THREAD

**Issue by ssbarnea** [vscode-restructuredtext/vscode-restructuredtext#226]
While I have no expectations regarding bug fixing, I feel bit sad to see PRs lingering for long period of time, some of them quite good.

@lextm Are you the only core contributor to the project? Any plans to invite others? I am not having anyone particular in mind but having two people would avoid risk of abandonware.

**Comment by lextm** [comment]
I cannot see much about "some of them quite good". Or they should have been merged a long while ago.

**Comment by ssbarnea** [comment]
If they are not ready, make a review with request changes (so they report red), also mention that if not updated in two weeks it will be closed. Keep the PR list short, the longer a PR is open the least is the chance that the original author will have motivation to fix it.  

Same does not apply to issues, these are "cheap", no need to bother about them. PRs are valuable as they require effort to raise.

And thanks for this extension! As a author and maintainer of many python libraries, i find it very useful.

**Comment by lextm** [comment]
If you meant the ones opened by the same guy, I already commented in https://github.com/vscode-restructuredtext/vscode-restructuredtext/pull/165 . However, that original author still sent low quality PRs (no clear goal, and code without enough explanation) that cannot be accepted.

No plan to waste more time on them, but leave open if someone would like to pick up.
