### ISSUE TITLE
Support the OpenVSX registry which is the default for Codium

### ISSUE THREAD

**Issue by tchernobog** [vscode-restructuredtext/vscode-restructuredtext#227]
[VSCodium](https://vscodium.com/) (the VSCode flavor without proprietary license restrictions) started using a libre registry of plugins to ensure independence from Microsoft telemetry support and marketplace sole control. This is called [OpenVSX](https://open-vsx.org/) and is developed by the Eclipse Foundation.

This is a request for the maintainer of this plugin to add a GitHub action to release this extension on OpenVSX too. It requires registering an account, importing the secret token, and then adding the corresponding GitHub action to CI. See https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by lextm** [comment]
Anyone can fork this repo to produce the suitable binaries for VSCodium. But I have no plan to do that from here.
