### ISSUE TITLE
Please review Python installation on this machine before using this extension

### ISSUE THREAD

**Issue by brunodantas** [vscode-restructuredtext/vscode-restructuredtext#229]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 129.0.0
- [ ] Visual Studio Code version: 1.48.2
- [ ] Operating System version: Ubuntu 19.10
- [ ] Python version: 3.7.3 (conda)
- [ ] sphinx version: 3.2.1
- [ ] A sample of conf.py or its important fragments: No significant changes

**Expected behavior**

Live preview etc.

**Actual behavior**

When opening a .rst file or issuing a live preview, a notification appears:

`Please review Python installation on this machine before using this extension.`

**Detailed Steps to reproduce the problem**

Installed the extension, and followed both the [prerequisites](https://docs.restructuredtext.net/articles/prerequisites.html) and [configuration](https://docs.restructuredtext.net/articles/configuration.html) steps. The VS Code outputs stay empty.
Installed extensions: Anaconda Extension Pack, Python, reStructuredText, YAML.

**Comment by lextm** [comment]
Can you open OUTPUT panel and check what reStructuredText log section looks like? The log entries there should tell what's the cause.

**Comment by brunodantas** [comment]
```
[Log - 3:42:47 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 3:42:47 PM] Unknown distribution.
[Log - 3:42:47 PM] Your OS is:{"os":"linux","dist":"Ubuntu Linux","codename":"eoan","release":"19.10"}
[Log - 3:43:08 PM] [preview] set config to /home/dantas/solveoee_guide
[Log - 3:43:08 PM] Running cmd: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
[Log - 3:43:08 PM] Running cmd: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
[Log - 3:43:08 PM] Error
Command failed: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
/bin/sh: 1: /home/dantas/anaconda3: Permission denied

Error: Command failed: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
/bin/sh: 1: /home/dantas/anaconda3: Permission denied

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)

/bin/sh: 1: /home/dantas/anaconda3: Permission denied

[Log - 3:43:08 PM] Cannot find Python.
[Log - 3:43:08 PM] Error
Command failed: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
/bin/sh: 1: /home/dantas/anaconda3: Permission denied

Error: Command failed: "/home/dantas/anaconda3" -c "import sys; print(sys.version_info[0])"
/bin/sh: 1: /home/dantas/anaconda3: Permission denied

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)

/bin/sh: 1: /home/dantas/anaconda3: Permission denied

```

I installed VS Code through Anaconda btw.

**Comment by lextm** [comment]
The log entries show the root cause clearly.

For some unknown reason you set `/home/dantas/anaconda3` as Python path, and that doesn't seem right.

Please run `whereis python` or `whereis python3` command to learn where you can find the right Python path, and then configure that according to https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features .

**Comment by brunodantas** [comment]
Solved, thanks.
I set it to `/home/dantas/anaconda3/bin/python`.
