### ISSUE TITLE
'No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".'

### ISSUE THREAD

**Issue by DavidA2014** [vscode-restructuredtext/vscode-restructuredtext#230]
**Environment**
- [ ] Extension version: 129.0.0
- [ ] Visual Studio Code version: 1.49.1
- [ ] Operating System version: WSL 2 (Ubuntu 20.04)
- [ ] Python version: 3.8.2 64-bit
- [ ] sphinx version: 3.2.1

My index.rst contains:

```
Welcome to Poseidon's documentation!
====================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

.. automodule:: zodiac_control
   :members:

.. automodule:: zodiac_control_client
   :members:
```
I see the following problem reported in VS Code:

    (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".

What's the explanation please?

**Comment by lextm** [comment]
This is by design. docutils preview engine does not support all features of sphinx, so you have to switch to sphinx engine.

**Comment by vepain** [comment]
Hi, I re-open this issue because I have the same even if the preview engine is set on `sphinx` and docutil is disabled:
```json
{
    "restructuredtext.preview.name": "sphinx",
    "restructuredtext.preview.docutil.disabled": true
}
```
- [ ] Extension version: v149.0.0
- [ ] Visual Studio Code version: 1.55.2
- [ ] Operating System version: WSL 2 (Ubuntu 20.04)
- [ ] Python version: Python 3.9.4 64-bit
- [ ] sphinx version: 3.2.1

Thank you for your works,
Regards

**Comment by ChriZ982** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/28103843/116871478-9ab7eb00-ac14-11eb-861d-4970c1369435.png)

**Comment by lextm** [comment]
Turned out to be duplicate to #261 . Directives from extensions are not yet now supported by snooty.
