### ISSUE TITLE
Support docker runtime

### ISSUE THREAD

**Issue by authsec** [vscode-restructuredtext/vscode-restructuredtext#231]
It would be nice if the sphinx-build command could be configured to be run from a docker container.

That way you can keep a clean system installation, as you just pull your docker container to work on a document and everything is contained on that container.

I've built such a container [here](https://github.com/authsec/sphinx) if you want/need a reference.

**Comment by lextm** [comment]
This extension works well with VSCode remote development. So you can use that to connect to your container.

**Comment by authsec** [comment]
This may be an option as well, didn't think of it that way. My basic idea is to use the container as a runtime environment provide. So instead of called `sphinx-build` from the OS you'd call `docker run --rm -v $(pwd):/docs authsec/sphinx sphinx-build` from the container. 

That way you can provide collaborators a simple container that contains all extensions your documentation project needs to run properly.
