### ISSUE TITLE
Default preview keyboard shortcut clashes with VSCode default

### ISSUE THREAD

**Issue by jamesbooker** [vscode-restructuredtext/vscode-restructuredtext#232]
**Environment**
- [ ] Extension version: 129.0.0
- [ ] Visual Studio Code version: 1.49.2 (user setup)
- [ ] Operating System version: Windows 10 v2004
- [ ] Python version: 3.8.0
- [ ] sphinx version: 3.2.1
- [ ] A sample of conf.py or its important fragments: N/A

**Expected behavior**
Pressing CTRL+K, CTRL+R is supposed to open the preview window to the side.

**Actual behavior**
VSCode now has this set as a default to open up the keyboard shortcuts PDF. The VSCode keybaord shortcut overrides the one from this extension

**Detailed Steps to reproduce the problem**
Install as above, press CTRL+K,CTRL+R

**Suggested Solution**
Change the default shortcut to CTRL+SHIFT+K, CTRL+SHIFT+R or CTRL+K,CTRL+SHIFT+R

**Comment by lextm** [comment]
Finally I tested this myself on a Windows machine with both VSCode 1.51.1 and 1.52.0.

* When some other files are opened, CTRL+K CTRL+R shows the PDF document for shortcuts like you described.
* When a .rst file is opened, CTRL+K CTRL+R does open the preview panel.

Sounds like Microsoft has fixed the conflicts on its side.
