### ISSUE TITLE
Valid 'python.pythonPath' configuration pointing to virtual Python environment (venv) directory not supported

### ISSUE THREAD

**Issue by boy-vd** [vscode-restructuredtext/vscode-restructuredtext#236]
**Environment**
- [x] Extension version: 129.0.0
- [x] Visual Studio Code version: 1.50.0
- [x] Operating System version: 10.15.6
- [x] Python version: 3.7.3
- [x] sphinx version: 1.8.5
- [ ] A sample of conf.py or its important fragments: N/A

**Expected behavior**
Extension derives correct path to Python from 'python.pythonPath' setting when that setting points to a directory of a virtual Python environment.

**Actual behavior**
Extension interprets configuration of setting 'python.pythonPath' as complete path to a Python executable even when the setting points to a directory of a virtual Python environment instead 

**Detailed Steps to reproduce the problem**
- In root of Sphinx documentation project create virtual Python environment: `python3 -m venv .venv`
- Activate venv: `source .venv/bin/activate` (on Bash or zsh)
- Install Sphinx in venv: `pip install sphinx==1.8.5 sphinx_rtd_theme==0.4.3 docutils==0.15.2 rstcheck pylint` (exact versions shouldn't matter here, but this is what I use)
- Configure 'python.pythonPath' for workspace of Sphinx documentation project: `"python.pythonPath": "${workspaceFolder}/.venv"`
- Open random ReStructeredText file in project
- Check 'Output' of Visual Studio Code and you should see something like this:

`Error: Command failed: "/Users/usp_boy/repos/rtd/.venv" -c "import sys; print(sys.version_info[0])"
/bin/sh: /Users/usp_boy/repos/rtd/.venv: is a directory`

Even though Visual Studio Code clearly allows 'python.pythonPath' to point to the directory of a virtual Python environment instead of the actual Python executable within that environment. Even more so, it's the recommended practice, because the setting will work across different operating system environments if configured in this way: 

> Path to the Python interpreter, or the path to a folder containing the Python interpreter. Can use variables like ${workspaceFolder} and ${workspaceFolder}/.venv. Using a path to a folder allows anyone working with a project to create an environment in the .venv folder as appropriate to their operating system, rather than having to specify an exact platform-dependent path. The settings.json file can then be included in a source code repository.

The above is taken from the official Visual Studio Code documentation: https://code.visualstudio.com/docs/python/settings-reference#_general-settings

**Comment by lextm** [comment]
You should open `conf.py` first and use Microsoft's Python extension to select your virtual environment's Python as interpreter. Then things should start to work.

https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features

Even if you cannot use Microsoft Python extension, the value assigned to `python.pythonPath` should be an absolute path pointing to the Python executable, not a folder.
