### ISSUE TITLE
Scrolling through Raw Text and Preview does not match scroll position

### ISSUE THREAD

**Issue by JonathanLindsey** [vscode-restructuredtext/vscode-restructuredtext#237]
**Environment**
- [ ] Extension version: 129.0.0
- [ ] Visual Studio Code version: 1.50.1
- [ ] Operating System version: Windows 10 2004
- [ ] Python version: 3.8.5
- [ ] sphinx version: 3.1.2
- [ ] A sample of conf.py or its important fragments: https://github.com/vscode-restructuredtext/docs/blob/master/conf.py

**Expected behavior**

The preview scrolls right along with the raw text.

**Actual behavior**

With the raw text and preview side by side in VS Code, if I scroll through the raw text, the preview will scroll about twice as fast until I get about half-way through the raw text at which point it is at the bottom of the preview. As I keep scrolling down in the raw text, the preview pauses and then scrolls up at about 2x speed while I scroll down through the second half of the raw text.

When scrolling through the preview instead of the raw text, the raw text is always in the first half of the document.

**Detailed Steps to reproduce the problem**

1. Clone https://github.com/vscode-restructuredtext/docs.
2. Open the articles/configuration.rst document in VS Code with the text editor and preview side-by-side.
3. Scroll through the raw text.
4. Notice the preview does not match the position of the raw text as described above.

**Comment by lextm** [comment]
Duplicate to #121

**Comment by lextm** [comment]
Duplicate to #121
