### ISSUE TITLE
Source folder is always the same as conf.py folder

### ISSUE THREAD

**Issue by Predelnik** [vscode-restructuredtext/vscode-restructuredtext#238]
**Environment**
- [ 129.0.0 ] Extension version:
- [ 1.50.1 ] Visual Studio Code version:
- [ Windows 8.1]  Operating System version:
- [ 3.9 ] Python version:
- [ 3.2.1 ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

Source directory could be specified relative to `conf.py` but not always be the same as `conf.py` directory.

**Actual behavior**

Extension always runs `sphinx` with `.` as source path

I would suggest allowing specifying source folder in config just as config/build folders could be.

**Comment by lextm** [comment]
Can you provide a sample project on GitHub showing why you need a non default source path?

This extension does not mean to cover all Sphinx scenarios so its defaults match many recommended setup (like ReadTheDocs guides).

But if yours turns out to be a typical case that requires attention then some changes can be implemented.

**Comment by Lucide** [comment]
I got stuck in this too, I didn't even have to search!
I'm working on a CMake C project, the three is roughly this:
```
.
├── cmake-build-debug-win
│   ├── doc
│   │   ├── conf.py //configured conf.py
│   │   ├── html(dir) //sphinx output dir
│   │   └── xml(dir) //doxygen output dir/breathe extension input dir
├── doc
│   ├── conf.py.in //template conf.py
│   ├── index.rst
│   └── static(dir)
├── venvWin(dir)
└── venvWsl(dir)
```
In CMake, you're expected to do "out of source builds", where the configure/build process leaves the project unchanged, and it writes only under the build directory (here `cmake-build-debug-win`).
The `conf.py` is one of those files that need to be "filled out" by CMake. The configured version is put in the respective build directory. This is a very common C/C++ project layout.
In this case, Sphinx's source folder should be `./doc/`. I couldn't find a way to express that to the extension. This is what it does instead:
```
[Log - 12:28:57] [linter] Execute: "D:\Users\Nemo\Roaming\Python\Python39\Scripts\rstcheck.exe" "d:\Users\Nemo\OneDrive-shared\c\VisualT\doc\index.rst" in d:\Users\Nemo\OneDrive-shared\c\VisualT.
[Log - 12:30:18] Running cmd: "d:\Users\Nemo\OneDrive-shared\c\VisualT\venvWin\Scripts\python.exe" -c "import sphinx;"
[Log - 12:30:19] Successful exec
[Log - 12:30:19] [preview] Compiling file: d:\Users\Nemo\OneDrive-shared\c\VisualT\doc\index.rst
[Log - 12:30:19] [preview] Sphinx conf.py directory: d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc
[Log - 12:30:19] [preview] Sphinx html directory: d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc\html
[Log - 12:30:19] [preview] Compiler: "d:\Users\Nemo\OneDrive-shared\c\VisualT\venvWin\Scripts\python.exe" -m sphinx -b html . "d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc\html"
[Log - 12:30:19] [preview] Working directory: d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc
[Log - 12:30:19] [preview] HTML file: d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc\index.html
```
Sphinx searches `index.rst` inside the build dir:
```
Error: Command failed: "d:\Users\Nemo\OneDrive-shared\c\VisualT\venvWin\Scripts\python.exe" -m sphinx -b html . "d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc\html"

Sphinx error:
master file d:\Users\Nemo\OneDrive-shared\c\VisualT\cmake-build-debug-win\doc\index.rst not found
```

**Comment by Predelnik** [comment]
@Lucide Thank you for providing a compelling example!

The project I'm working on is not open source unfortunately, and most of the open source projects I found during quick search indeed had `con.py` beside `index.rst`, so I was going to do a bit more thorough search on a week-end. But maybe this case already is enough to justify adding the option for this, @lextm?

**Comment by brboi** [comment]
Hello, another open source documentation project where this extension does not work with the same issue is https://github.com/odoo/documentation

**Comment by lextm** [comment]
With the recent change on live preview engine, this is going to be addressed soon.

**Comment by lextm** [comment]
Starting from release 172.0.0, you can use `restructuredtext.sourcePath` to specify the root directory of a sphinx project, in case it is different from `restructuredtext.confPath`.
