### ISSUE TITLE
Preview for python docstrings (sphinx format)  directly from python file.

### ISSUE THREAD

**Issue by cobordism** [vscode-restructuredtext/vscode-restructuredtext#239]
**Environment**
- [ x ] Extension version: 129.0.0
- [ x ] Visual Studio Code version: 1.50.1
- [ x ] Operating System version: Ubuntu 20.04
- [ x ] Python version: 3.8.5
- [ x ] sphinx version: 3.1.2
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
When I am editing a python (.py) file that contains extensive documentation in docstrings that are formatted for rst/sphinx, I would love to be able to see a rendered preview.

**Actual behavior**
The preview only works for the purely .rst files in the documentation but is not available for the python files.
The only way for me to see those docstrings in sphinx is to manually build the html / sphinx project.

Question:
Is this possible? i.e. Is my system just configured wrong, or is what I am asking for a missing feature?

---

It would be even nicer if the rendered rst were visible on the 'tooltip'-like window that appears when I hover over a python function. Right now I only see the raw rst code.

**Comment by lextm** [comment]
Some code of this extension might be reused to enable the features you described, but that should be a new extension or addition to an existing Python language extension.

**Comment by lextm** [comment]
Close it now, as it will not be worked on here as explained earlier.
