### ISSUE TITLE
[grammar] “The text within inline markup may not begin or end with whitespace”

### ISSUE THREAD

**Issue by flying-sheep** [vscode-restructuredtext/vscode-restructuredtext#242]
**Environment**
- [x] Extension version: 129
- [x] Visual Studio Code version: 1.50.1
- [x] Operating System version: Arch Linux (up-to-date)
- [x] Python version: 3.8.6
- [ ] sphinx version: N/A
- [ ] A sample of conf.py or its important fragments: N/A

**Expected behavior**
[Inline markup](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-markup) is defined to not start or end with whitespace.

**Actual behavior**
A single backtick highlights the whole rest of the document as “interpreted text”.

**Detailed Steps to reproduce the problem**
Paste this into a file and let this extension highlight it:

```
Text ` not inline markup` also not inline markup.
```

**Comment by lextm** [comment]
In release 154.0.0 the old grammar file was replaced by the one from https://github.com/trond-snekvik/vscode-rst .

Close this item now as it does not appear with that grammar file.
