### ISSUE TITLE
Linter executable not found

### ISSUE THREAD

**Issue by Formedras** [vscode-restructuredtext/vscode-restructuredtext#243]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: v129.0.0
- [x] Visual Studio Code version: 1.51.0-insider (system setup)
- [x] Operating System version: Windows 10 Pro Version 2004 Build 19041.572
- [x] Python version: 3.9
- [x] sphinx version: 3.2.1
- [ ] A sample of conf.py or its important fragments: conf.py is stock, except for minimum for adding ReadTheDocs theme

**Expected behavior**
For linter to run.
**Actual behavior**
Linter executable can't be found.

![2020-10-31 (1)](https://user-images.githubusercontent.com/2267190/97794697-85f19080-1bba-11eb-9de6-4a88a2d5beb0.png)
![2020-10-31](https://user-images.githubusercontent.com/2267190/97794699-89851780-1bba-11eb-8214-f142283298ed.png)

**Detailed Steps to reproduce the problem**
1. Install through Winget: VSCode Insiders
2. Install through Chocolatey: Python 3.9 (I also have Python 2.7 installed.)
3. Install through Pip: Sphinx (I also installed `sphinx-rtd-theme`)
4. Install extension in VSCode: reStructuredText
5. Create a Sphinx doc using `sphinx-quickstart`
6. Open `index.rst` in VSCode
7. Watch Linter error occur.
8. Specify `C:\Python39\scripts\rstcheck.exe` as Linter executable in reStructuredText settings in VSCode
9. Error again.

When looking online for solutions, I found that someone else already had this problem in 2017 (and posted in StackOverflow), and it was apparently fixed then?

**Comment by lextm** [comment]
At command prompt, what do you get when running `C:\Python39\scripts\rstcheck.exe`?

**Comment by Formedras** [comment]
`PS C:\Users\tizal> c:\Python39\scripts\rstcheck.exe`
`usage: rstcheck [-h] [-r] [--report level] [--ignore-language language] [--ignore-messages messages]`
`                [--ignore-directives directives] [--ignore-substitutions substitutions] [--ignore-roles roles]`
`                [--debug] [--version]`
`                files [files ...]`
`rstcheck: error: the following arguments are required: files`
I assume this is the desired output? I also tried gave it the `index.rst` file as an argument and there was no output (exits out immediately); I also assume that this is the desired result on a file without errors?

**Comment by lextm** [comment]
Due to the design of the linter integration, if the executable experiences unexpected errors, the error message is displayed (though its words can be misleading).

At this moment, you have to debug the source code of this extension in order to learn what's wrong with rstcheck on your machine.
