### ISSUE TITLE
VSCode Marketplace: Feature Contributions descriptions are missing/broken

### ISSUE THREAD

**Issue by OnlineCop** [vscode-restructuredtext/vscode-restructuredtext#245]
## Main Issue: VSCode Marketplace

In VSCode, Open the Extensions panel and navigate to **reStructuredText** in the marketplace. Click on the **_Feature Contributions_** tab (beside **_Details_**) below the project's title and description:

![image](https://user-images.githubusercontent.com/1168697/98014723-3cbb5f80-1db9-11eb-967e-69b76b3ce047.png)

The descriptions for many of the `restructuredtext.preview.*` show `%restructuredtext.preview.*.desc%` instead of the actual descriptive text.

I believe the actual descriptive text resides under [package.nls.json](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/package.nls.json). It contains, for example, descriptions such as this:

    "restructuredtext.styles.dec": "A list of URLs or local paths to CSS style sheets to use from the restructuredtext preview. Relative paths are interpreted relative to the folder open in the explorer. If there is no open folder, they are interpreted relative to the location of the restructuredtext file. All '\\' need to be written as '\\\\'.",
    "restructuredtext.preview.fontFamily.desc": "Controls the font family used in the restructuredtext preview.",
    "restructuredtext.preview.fontSize.desc": "Controls the font size in pixels used in the restructuredtext preview.",

## Other Issue: Setting Name Description Typo

The setting description `restructuredtext.styles.dec` should probably use `desc` instead of `dec` at the end to be consistent with all the other settings descriptions. It is referenced in [package.json](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/package.json) and [package.nls.json](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/package.nls.json) (and possibly other locations).

**Comment by lextm** [comment]
That's a well known bug of the VSCode system.
