### ISSUE TITLE
Cannot use variables other than workspaceFolder

### ISSUE THREAD

**Issue by anatolyburakov** [vscode-restructuredtext/vscode-restructuredtext#247]
Issue Type: <b>Bug</b>

I have an out-of-tree build path that includes multiple projects under "build/<project name>" that heavily relies on `workspaceFolderBasename` variable. This extension doesn't support any variables other than `workspaceFolder`, i think it should support all of them.

(as a side note, shouldn't this be done on VSCode side so that the extension doesn't have to do it for itself?)

Extension version: 129.0.0
VS Code version: Code - Insiders 1.52.0-insider (ee46c1f89ebb213e0827886f1688c0fbb55be49f, 2020-11-13T05:37:45.836Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-121-generic

**Comment by lextm** [comment]
No plan to work on this in the near future.

Once VSCode exposes related functions, might revisit this one.
