### ISSUE TITLE
Using externally generated previews?

### ISSUE THREAD

**Issue by anatolyburakov** [vscode-restructuredtext/vscode-restructuredtext#248]
This is not a bug, but i'm trying to figure out if this extension can do what i'm hoping it would.

So, we have doc generation as part of the build system, so there is no need to ever run Sphinx manually. Is there a way to force this extension to use already existing pre-generated documents as opposed to running sphinx directly?

(it's still possible to run sphinx manually within our project, but our conf.py relies on an environment variable that is provided by the build system which normally isn't set)

**Comment by lextm** [comment]
It's a good idea if the preview engine can be revised to utilize external contents, but that requires a complete rewrite from scratch I think. 

Too much effort for an open source project, so hope someone can step in.
