### ISSUE TITLE
Unable to select python version

### ISSUE THREAD

**Issue by anatolyburakov** [vscode-restructuredtext/vscode-restructuredtext#249]
Issue Type: <b>Bug</b>

I have both python 2 and 3 installed, with the default "python" command pointing to python 2. My `conf.py` requires python 3, yet there appears to be no way to tell the extension to use python 3 instead of 2.

Extension version: 129.0.0
VS Code version: Code - Insiders 1.52.0-insider (ee46c1f89ebb213e0827886f1688c0fbb55be49f, 2020-11-13T05:37:45.836Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-121-generic

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/prerequisites.html#install-python-for-most-features

Due to some recent changes, option 2 in step 2 might not work very well, so you might consider option 1.

**Comment by anatolyburakov** [comment]
@lextm setting python path for vscode worked for me, but it seems odd that the ReST extension relies on Python extension's settings to work. I could imagine a scenario where i would have ReST but not Python extension.

**Comment by lextm** [comment]
reStructuredText is primarily a technology owned by the Python community, so most users of this extension also use the Python extension. The scenario you described exists but is a minority. Even without the Python extension installed, you can set `python.pythonPath` in `settings.json` (though VSCode shows a warning then).

**Comment by ttelcl** [comment]
> 
> 
> reStructuredText is primarily a technology owned by the Python community, so most users of this extension also use the Python extension. The scenario you described exists but is a minority. Even without the Python extension installed, you can set `python.pythonPath` in `settings.json` (though VSCode shows a warning then).

That is no longer true. The current version of the Python extension now *removes* that setting if it detects its presence.

**Comment by lextm** [comment]
@ttelcl You have to name the version. I am using ms-python.python 2020.11.371526539 on macOS, but it does not remove that setting.

**Comment by ttelcl** [comment]
> @ttelcl You have to name the version. I am using ms-python.python 2020.11.371526539 on macOS, but it does not remove that setting.

That would be v2020.11.371526539 on windows

**Comment by lextm** [comment]
@ttelcl It will be rather weird that they design the Windows behaviors differently.

Anyway the latest 130.0.0 release talks to the Python extension directly to learn where to locate Python executable, so whether `python.pythonPath` exists no longer matters.
