### ISSUE TITLE
Update "pythonPath" to "interpreterPath"

### ISSUE THREAD

**Issue by patrickstump** [vscode-restructuredtext/vscode-restructuredtext#250]
**Environment**
- [ x] Extension version: 129.0.0
- [ x] Visual Studio Code version: 1.51.1
- [x ] Operating System version: MacOS X 10.15.7
- [ x] Python version: 3.8
- [ x] sphinx version: 3.2.1
- [x ] A sample of conf.py or its important fragments: NA

**Expected behavior**
reStructuredText should use the python path set by visual studio code either at the workspace level or the project level.

This was previously denoted by the config item `python.pythonPath`. `python.pythonPath` has now been deprecated and moved into an internal setting.  Per reference [DeprecatePythonPath](https://github.com/microsoft/vscode-python/wiki/AB-Experiments), 3rd party extensions shoud now use 
`${command:python.interpreterPath}.`

I believe this can be remedied by changing the following in `src/features/utils/configuration.ts`:
from 
```
return this.getConfiguration("python", resource).get<string>("pythonPath");
```

to 

```
return this.getConfiguration("python", resource).get<string>("interpreterPath");
```

This setting is supposed to give the extension the python path the project is using, which could be the system or a virtual environment.

**Actual behavior**
The extension is still using `python.pythonPath` which on mac manifests as using the mac version python of 2.7.  This requires all of the sphinx submodules you need to be installed at the system level and will not pull them from the virtual environment.

When previewing an rst in vscode the following is received:
Note the following says python 3.8 because I have manually set that path in settings.json at the vscode main level.
```
    "python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3",
```
Output from preview:

```
Error
Command failed: "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3" -m sphinx -b html . "/Users/username/Workspace/projects/current_project/docs/source/_build/html"

Extension error:
Could not import extension sphinx (exception: No module named 'sphinx')

```
This will occur for every pip module not installed at the system level.

**Detailed Steps to reproduce the problem**

- Install virtualenv
- Create a virtual environment
- pip install sphinx
- start up vscode and try to preview any rst. in that environment.

```
pip install virtualenv
virtualenv venv
pip install sphinx
code .
```

**Comment by lextm** [comment]
Related to #168

**Comment by boy-vd** [comment]
Also related to #236
