### ISSUE TITLE
Bug: Extension tries to open wrong file.

### ISSUE THREAD

**Issue by m-spitfire** [vscode-restructuredtext/vscode-restructuredtext#251]
- [x] Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

**Environment**

Extension version: v129.0.0
Visual Studio Code version: 1.51
Operating System version: Windows 10 pro
Python version: 3.8
sphinx version: 3.3.1
<details><summary>A sample of conf.py or its important fragments:</summary>
<p>

https://github.com/spitfire-hash/latex-admin/blob/master/docs/conf.py

</p>
</details>

**Expected behavior**

When you specify the settings like 

```json
{
    "restructuredtext.builtDocumentationPath": "${workspaceRoot}/docs/_build/html",
    "restructuredtext.confPath": "${workspaceRoot}/docs"
}
```

It should be able to preview the `rst` file.
**Actual behavior**
It gives an error
```py
Error: ENOENT: no such file or directory, open 'c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs\_build\README.html'
```
which is weird because I have setted the settings for `builtDocumentationPath` as `./docs/_build/html` not `./docs/_build/`.

And it just compiles fine the `html` files is in the directory `./docs/_build/html`, the problem is with the preview panel.
<details><summary>My whole <code>./.vscode/settings.json</code> file</summary>
<p>

```json
{
    "python.pythonPath": "C:\\Users\\Ilqar\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\latex-admin-a8oSVieQ-py3.8\\Scripts\\python.exe",
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--config=.flake8"
    ],
    "[python]": {
        "gitlens.codeLens.symbolScopes": [
            "!Module"
        ],
        "editor.formatOnSave": false
    },
    "restructuredtext.builtDocumentationPath": "${workspaceRoot}/docs/_build/html",
    "restructuredtext.confPath": "${workspaceRoot}/docs"
}
```

</p>
</details>
<details><summary>The output log from extension</summary>

```
[Log - 11:36:51 PM] Running cmd: "C:\Users\Ilqar\AppData\Local\pypoetry\Cache\virtualenvs\latex-admin-a8oSVieQ-py3.8\Scripts\python.exe" -c "import sphinx;"
[Log - 11:36:52 PM] Successful exec
[Log - 11:36:52 PM] [preview] Compiling file: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\README.rst
[Log - 11:36:52 PM] [preview] Sphinx conf.py directory: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs
[Log - 11:36:52 PM] [preview] Sphinx html directory: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin/docs/_build/html
[Log - 11:36:52 PM] [preview] Compiler: "C:\Users\Ilqar\AppData\Local\pypoetry\Cache\virtualenvs\latex-admin-a8oSVieQ-py3.8\Scripts\python.exe" -m sphinx -b html . "c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin/docs/_build/html"
[Log - 11:36:52 PM] [preview] Working directory: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs
[Log - 11:36:52 PM] [preview] HTML file: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs\_build\README.html
```
</details>

**Comment by spitfire-hash** [comment]
I just solved the issue.

Changed the setting for `builtDocumentationPath` to:

```json
{
    "restructuredtext.builtDocumentationPath": "${workspaceRoot}/docs/_build/html/jssdajns"
}
```

And know it knows that the `builtDocumentationPath` is `./docs/_build/html`. It's so weird. Here's the output:
```
[Log - 11:56:02 PM] [preview] Compiler: "C:\Users\Ilqar\AppData\Local\pypoetry\Cache\virtualenvs\latex-admin-a8oSVieQ-py3.8\Scripts\python.exe" -m sphinx -b html . "c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin/docs/_build/html/jssdajns"
[Log - 11:56:02 PM] [preview] Working directory: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs
[Log - 11:56:02 PM] [preview] HTML file: c:\Users\Ilqar\Desktop\repositories\latex-admin\latex_admin\docs\_build\html\README.html
```
now it works just fine 
![image](https://user-images.githubusercontent.com/66242799/99581276-f93c3480-29f9-11eb-8f11-d93b72dda1e4.png)

I won't close the issue because I think this is a bug.

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview or language server based actions but recommends the Esbonio extension to be used instead. Close this issue now.
