### ISSUE TITLE
Can't open Preview to Side

### ISSUE THREAD

**Issue by iccicci** [vscode-restructuredtext/vscode-restructuredtext#252]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [129.0.0 ] Extension version:
- [1.51.1 ] Visual Studio Code version:
- [ Windows 10 WSL2] Operating System version:
- [3.8.5 ] Python version:
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
Pressing ctrl+k ctrl+r should open the side preview

**Actual behavior**
Pressing ctrl+k ctrl+r opens following URL in my browser:
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Detailed Steps to reproduce the problem**
Just press ctrl+k ctrl+r

**Log in VScode**
[Log - 10:31:16 AM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 10:31:16 AM] Unknown distribution.
[Log - 10:31:17 AM] Your OS is:{"os":"linux","dist":"Ubuntu Linux","codename":"focal","release":"20.04"}

**Comment by lextm** [comment]
VSCode hijacks that key combination for something else.

**Comment by iccicci** [comment]
I deleted the default binding, now ctrl+k ctrl+r deos nothing.

More than this in the top left corner I can't see the icon which is clicked in the animated image in the homepage of this extension.

It seems it simply doesn't load without any error

**Comment by lextm** [comment]
Just built a WSL environment to test this out, but I could not reproduce the issue you described as ctrl+k ctrl+r always shows the preview to the side.

There must be something else in your test environment that blocks the extension from working properly, but it must be difficult to dive deeper.

**Comment by iccicci** [comment]
Thank you for the try @lextm .
I see the "more info needed" tag was added, but I don't know which other useful info I could provide.
Is there something to increase log verbosity?

**Comment by lextm** [comment]
Your only hope is to debug the source code and see what might be the culprit. There isn't any log to reveal more details.

**Comment by iccicci** [comment]
I can try, could you please provide me a doc link on how to debug it?
I never debugged a VSCode extension.

Thank you

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/development.html

**Comment by lextm** [comment]
Duplicate to #232

**Comment by lextm** [comment]
It's strange that I cannot reproduce the issue. CTRL+K CTRL+R works for me on a Windows 10 machine.

Close it now as it is duplicate, but we can reopen it if you find some hints.
