### ISSUE TITLE
Bullet lists are not rendered

### ISSUE THREAD

**Issue by reneklootwijk** [vscode-restructuredtext/vscode-restructuredtext#253]
- Extension version: 130.0.0
- Visual Studio Code version: 1.51.1
- Operating System version: MacOS 10.15.7
- Python version: 3.9.0
- sphinx version: 1.8.2

Bullet lists (using '* ') are not rendered but instead just rendered as if there was not bullet. When I build the documentation using make, everything is rendered correctly.

**Comment by reneklootwijk** [comment]
The following code:

`This is test rendering a bullet list:

* Item 1 
* Item 2

This is test rendering a numbered list:

#. Item 1
#. Item 2`

Is rendered as:
![image](https://user-images.githubusercontent.com/915437/101775842-5d7d8000-3af0-11eb-8a01-488a951f5b47.png)

**Comment by lextm** [comment]
Still cannot reproduce that.

What's the HTML theme you use in `conf.py`? That theme might render list items differently.

**Comment by reneklootwijk** [comment]
Sorry it was due to my local configuration. Fixed it now.
