### ISSUE TITLE
language server complains about 'literalInclude' directive

### ISSUE THREAD

**Issue by danieleades** [vscode-restructuredtext/vscode-restructuredtext#255]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 131.0.0
- [x] Visual Studio Code version: 1.52.0
- [x] Operating System version: ubuntu 20.10 (WSL2)
- [x] Python version: 3.8.6
- [x] sphinx version: 3.3.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

I can use `literalInclude` directives without error

**Actual behavior**
 'Snooty' doesn't seem too happy with my `literalInclude` directives, and returns an error - `Unknown directive type "literalInclude".`

**Detailed Steps to reproduce the problem**

```rst
Some Document
-------------------

.. literalInclude:: features/my-cool-feature.feature
    :language: gherkin

```

**Comment by lextm** [comment]
Expected. The MongoDB guys are still working on it (0.8.2 is the latest release).

Not sure when such can be fixed.

**Comment by lextm** [comment]
I just noticed that you should use
```
.. literalinclude:: features/test.feature
   :language: gherkin
```
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude
