### ISSUE TITLE
Extension broken with newer Python version(>=3.6)

### ISSUE THREAD

**Issue by v3470** [vscode-restructuredtext/vscode-restructuredtext#257]
**Environment**
- [x] Extension version: v132.0.0
- [x] Visual Studio Code version: 1.52
- [x] Operating System version: Windows 10 x64, 10.0.19042.685
- [x] Python version: 3.8.5
- [x] sphinx version: 3.2.1 final
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

the vscode-restructuredtext should running after the extension's auto update.

**Actual behavior**

the vscode-restructuredtext become unresponsive, and the log shows: can not install the `snooty` because its depends `watchdog~=0.10.3` which require python version >=2.7,< 3.6

**Detailed Steps to reproduce the problem**

1. install a Python runtime which version >=3.6
2. install the vscode-restructuredtext which version with starting set the `Use Snooty` to true as default (I don't know the exact minimal version number because there is not a changelog with the github release package).
3. finally the vscode-restructuredtext broken unless you change the language server.

PS: my question is, why decide to set the `Use Snooty` option to true as default without testing with newer Python version?

**Comment by lextm** [comment]
Tested with both Python 3.8 and 3.9. So what you experienced is a very tricky case that probably not many hit.

Language server is by default disabled, so setting use Snooty flag to true won't affect most users either. Those who are helping test the language server shouldn't be surprised at issues, as it remains an experimental feature, either the legacy one or Snooty.

**Comment by v3470** [comment]
@lextm I'm not sure what actually happen at my side, the log of 
`vscode-restructuredtext` extension shows the dependency issue. 

Currently if I still want to use this extension, I have to unselect the "Use Snooty" option. You said that you can not reproduce this case, that means you can install both `snooty` and `watchdog` with Python 3.8+. 

I rethink this problem, I tried to reproduce on a newer Linux environment, and then get the same result as yours. So I tried to test it whether a platform issue or a pip issue, and finally confirmed that this case only happen with older pip version(<=20.1.1).

This final result also make me confused, because according to [PEP-440#compatible-release](https://www.python.org/dev/peps/pep-0440/#compatible-release), `watchdog~=0.10.3` should be equal to `watchdog>=0.10.3,==0.10.*`. However newer version `pip`(tested with v20.3.3) seems ignored the second part of the limit of the version specifier. :upside_down_face:

**Comment by lextm** [comment]
Ah, that's interesting. But your conclusion is very important, and I will add a validation step to check pip version before installing snooty. 

Thanks for your hard work on this.

**Comment by lextm** [comment]
Added pip version check in 80c13ac183e14fcf77c5f4bfae7ac3c0a2b83741 so users of release 134.0.0 and above won't be blocked by old pip now.
