### ISSUE TITLE
Incorrect logic in platformIsSupported

### ISSUE THREAD

**Issue by ytimenkov** [vscode-restructuredtext/vscode-restructuredtext#259]
Extension version 134.0.0

I've noticed in my output:
```
[Log - 4:45:37 AM] OS is linux
[Log - 4:45:37 AM] dist: ubuntu
[Log - 4:45:37 AM] Supported distribution.
[Log - 4:45:37 AM] Not-supported distribution.
```

The code in `extension.ts` / `platformIsSupported` does `return true` but this return is from a lambda function, not from a top-level one, so control always falls through to the final `return false` statement on Linux.

Maybe replace `forEach` with `some` (or whatever is correct in JS)?

**Comment by lextm** [comment]
Fixed in cc78468386dcd4adede1b05263d945a91cf17e3c Thanks for the report.
