### ISSUE TITLE
language server complains about unknown directives from extension

### ISSUE THREAD

**Issue by danieleades** [vscode-restructuredtext/vscode-restructuredtext#261]
I'm using the (sphinx-needs)[https://sphinxcontrib-needs.readthedocs.io/en/latest/index.html] extension.

This introduces a number of directives ("`req`", "`spec`", plus user-configurable directives)

The language server is throwing errors on these

- is there some way to suppress these errors?
- is there a way to register the extra directives so that they are recognised?
  - if yes, is that something that the extension should be doing?

**Comment by lextm** [comment]
Thanks for the report. It will take some time to investigate and resolve.

**Comment by danieleades** [comment]
I also see this with the `uml` directives from the [plantuml](https://pypi.org/project/sphinxcontrib-plantuml/) extension

**Comment by Abdelkrim** [comment]
Here is the error message when I use the todo extension on vscode:

``` 
System Message: ERROR/3 (/home/www.alt-f1.be/dev/software_spec.rst, line 13)

Unknown directive type "todo".

.. todo::
    1. **Abdelkrim** summarizes the project

```

**Comment by lextm** [comment]
Directives from extensions are not supported at this moment. You might disable snooty by putting this line in VSCode settings,
```
"restructuredtext.languageServer.disabled": true
```

**Comment by danieltuzes** [comment]
I don't think we all request full support for external features, but it would be great if snooty didn't fail on them. If snooty recognizes that it is non-existent or not yet supported extension, show the code of the directive with a note that snooty cannot render its content and move on.

**Comment by lextm** [comment]
@danieltuzes MongoDB has its own priorities on snooty. So if you are willing to resolve that, send a pull request to https://github.com/vscode-restructuredtext/snooty-parser/pulls

**Comment by lextm** [comment]
Closed as switching to esbonio.

**Comment by danieltuzes** [comment]
Unknown directives still produce INFO messages, disturbing the visual appearance of the code. Is it possible to at least manually define the directives that are not part of the core sphinx? E.g. https://sphinx-toolbox.readthedocs.io/en/stable/extensions/collapse.html

**Comment by danieltuzes** [comment]
I still get an error, bc rstcheck still wants to check it:
![image](https://user-images.githubusercontent.com/6088393/157317415-4765d542-c6f1-4c04-bd83-adac4458de8e.png) saying

> (INFO/1) No directive entry for "collapse" in module "docutils.parsers.rst.languages.en".restructuredtext

I don't know why it is mentioned under docutils, but this comes from rstcheck:

```
PS C:\Users\daniel\source\collection\docs\source> rstcheck .\intro.rst  
.\intro.rst:9: (INFO/1) No directive entry for "collapse" in module "docutils.parsers.rst.languages.en".
```

Would it be possible to ask rstcheck to ignore directives, that are supported by sphinx and esbonio, but not by rstcheck?

**Comment by lextm** [comment]
@danieltuzes You might report to https://github.com/myint/rstcheck/issues but sounds like that project has been abandoned and no more updates to come.

**Comment by danieltuzes** [comment]
@lextm rstcheck provides all the necessary features, setting the exclusion list in the program call and in the settings, and it is not possible to do more on their side. Instead, if the language server recognizes a directive not part of the core rst or sphinx, it should tell rstcheck to neglect these directives.

**Comment by lextm** [comment]
doc8 does not have this false positive, so I am not sure if "it is not possible to do more on their side".

Anyway in the future, Esbonio should take place of individual linters.

**Comment by danieltuzes** [comment]
Is rstcheck not the recommended linter in lexstudio's reStructuredText? After switching to doc8, I get the following error:

> Found conflicting extension swyddfa.esbonio. Please uninstall it.

So I'd keep rstcheck, but the additional directives should be provided by lexstudio's reStructuredText for rstcheck.

**Comment by danieltuzes** [comment]
doc8 is also abandoned and produces false-positive cases: https://bugs.launchpad.net/doc8/+bug/1756704

**Comment by lextm** [comment]
@danieltuzes Though out of scope, but you might check out some news from #335
