### ISSUE TITLE
Python version is too old to run Snooty language server

### ISSUE THREAD

**Issue by MetRonnie** [vscode-restructuredtext/vscode-restructuredtext#262]
**Environment**
- [ ] Extension version: `141.0.0`
- [ ] Visual Studio Code version: `1.51.1 x64`
- [ ] Operating System version: Red Hat Enterprise Linux 7.9
- [ ] Python version: `3.7.0`
- [ ] sphinx version: `3.2.1`
- [ ] A sample of conf.py or its important fragments: (This shouldn't matter?)

Plus:
- [ ] conda version: `4.8.3`

**Expected behavior**

The extension should start with no error notifications.

**Actual behavior**

I get the error notification:
> Python version is too old to run Snooty language server. Must use 3.7 and above.

**Detailed Steps to reproduce the problem**

- This occurs when opening a workspace in VSCode with rst file tabs open (remembered from last time)
- Python in VSCode is set to use a particular conda environment `my_env`, Python 3.7.0 (remembered from last time)
- My rstcheck path is set in the extension's settings to `/path/to/miniconda3/envs/my_env/bin/rstcheck`

**Additional context**

Extension output log:
```
[Log - 2:28:58 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 2:28:58 PM] OS is linux
[Log - 2:28:58 PM] dist: rhel
[Log - 2:29:00 PM] Running cmd: "python" -c "import sys; print(sys.version_info[0])"
[Log - 2:29:00 PM] Successful exec
```

I suspect it may be using the wrong python? The default (non-conda) python install on my system is 2.7.

**Comment by lextm** [comment]
That's a known issue right now, that when opening a workspace, this extension by default reads the Python path from the workspace level, not folder level, and that value is likely to be `python` on macOS and Linux.

This default value maps unfortunately to Python 2, not Python 3.

Currently the workaround is to change your workspace setting according to https://code.visualstudio.com/docs/getstarted/settings

Note that Snooty language server might not work properly for workspaces at this moment, and more effort is required to improve in that area.

**Comment by sdelquin** [comment]
Is there any way to uninstall Snooty Snooty language server?

**Comment by sdelquin** [comment]
`pip uninstall snooty-lextudio`

**Comment by danilaml** [comment]
@lextm I have the same error but on windows, because I have Py2 and py3 simultaneously installed and `python` refers to Py2, while Py3 can be called by using `py`.
Can Snooty at least provide a way to configure path to Python binary if it fails to autodetect it?

**Comment by lextm** [comment]
@danilaml I don’t think you hit the same issue as this one is very specific to a workspace opened in VSCode. The latest release automatically disables Snooty in such cases.

**Comment by csaltos** [comment]
Same error here using Ubuntu Linux 20.04 ... may Snooty have a simple setting option to set the Python path to use? ... (I have Python 3 installed but I found no way to instruct Snooty to use it instead of the old one)

Thank you very much for Snooty !!

**Comment by manoj153** [comment]
> Same error here using Ubuntu Linux 20.04 ... may Snooty have a simple setting option to set the Python path to use? ... (I have Python 3 installed but I found no way to instruct Snooty to use it instead of the old one)
> 
> Thank you very much for Snooty !!

i had no idea i was using them, some how my code completion not working for this reaso

**Comment by colinhacks** [comment]
For other users encountering this:

To solve this problem for a single repo: install the `Python` VS Code extension and use the Command Palette > Python: Select Interpreter to set which version of Python VS Code uses.

To solve globally on your machine, Run `which python3` to get the absolute path to your Python 3 version, then open your User `settings.json` (the path varies based on your OS: look up yours [here](https://code.visualstudio.com/docs/python/python-tutorial#_macos)), then add this line:

```ts
// settings.json
{
  ...
  "python.pythonPath": "<output of `which python3`>"
  ...
}
```

**Comment by MetRonnie** [comment]
@colinhacks But the extension really ought to use the Python version set in the left side of the status bar

**Comment by csaltos** [comment]
> ```ts
> // settings.json
> {
>   ...
>   "python.pythonPath": "<output of `which python3`>"
>   ...
> }
> ```

Great !! ... you nailed my hero !! 👍😎

**Comment by rickstaa** [comment]
@MetRonnie I agree that the extension should pick the currently active python interperter. 

I am not receiving the error you experience on:

**Version:** 1.56.0-insider
**Commit:** 845efe5d8e31079cc858131c95c36103d9439e74
**Date:** 2021-04-09T09:50:18.334Z
**Electron:** 11.4.2
**Chrome:** 87.0.4280.141
**Node.js:** 12.18.3
**V8:** 8.7.220.31-electron.0
**OS:** Linux x64 5.8.0-48-generic
**python extension version:** v2021.3.680753044

**Comment by lextm** [comment]
@MetRonnie what version of vscode-restructuredtext are you using?

Version 130.0 and above talk to the Microsoft Python extension to learn which Python interpreter to use, https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/130.0.0

The notification of "We removed the "python.pythonPath" setting from your settings.json file" also comes from the Python extension, not this extension.

**Comment by manojbaishya** [comment]
@MetRonnie Please see https://github.com/microsoft/vscode-python/issues/12313.
Adding the following to user settings will fix the automatic deletion:
``` json
    "python.experiments.enabled": false,
    "python.experiments.optOutFrom": [
        "All"
    ],
```

Note: An alternative is to use [reStructuredText Syntax highlight](https://marketplace.visualstudio.com/items?itemName=trond-snekvik.simple-rst) and [rstviewer](https://pypi.org/project/rstviewer/) until the snooty issues are fixed.

**Comment by lextm** [comment]
Closed as switching to esbonio.
