### ISSUE TITLE
watchdog version not noraml

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#263]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 141.0
- [ ] Visual Studio Code version: CODE OSS 1.52.1
- [ ] Operating System version: ARCHLINUX UP-TO-DATE
- [ ] Python version: 3.9.1
- [ ] sphinx version:  3.3.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
pip install snooty-lextudio will work well.
**Actual behavior**
```
~/.pip[2]:pip install snooty-lextudio -i https://mirrors.aliyun.com/pypi/simple/
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting snooty-lextudio
  Using cached https://mirrors.aliyun.com/pypi/packages/63/d2/ae1bc56063775ebf5643e6223ead607a8ea6be9ad5dc979d3c636ff4c869/snooty_lextudio-1.8.6.dev0-py2.py3-none-any.whl (155 kB)
Collecting typing-extensions~=3.7.4.1
  Downloading https://mirrors.aliyun.com/pypi/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting pymongo[srv,tls]~=3.11.1
  Using cached https://mirrors.aliyun.com/pypi/packages/ca/93/705580789647dca4650a7753e6cb979974299a6b841fdf0907b6ecf076e6/pymongo-3.11.2-cp39-cp39-manylinux2014_x86_64.whl (518 kB)
Collecting fett~=0.3.2
  Using cached https://mirrors.aliyun.com/pypi/packages/a6/fb/d4f8e22ea58cfb4a86f617982f037d3fd057491b50d8f0fe81495c2f6f64/fett-0.3.2.tar.gz (7.2 kB)
Requirement already satisfied: toml~=0.10.1 in /usr/lib/python3.9/site-packages (from snooty-lextudio) (0.10.2)
Collecting python-jsonrpc-server~=0.3.4
  Using cached https://mirrors.aliyun.com/pypi/packages/a2/41/5145d9e28f097372970004c5151fd0879f615ec086f3dc3722daf4c87268/python_jsonrpc_server-0.3.4-py3-none-any.whl (9.0 kB)
Collecting networkx~=2.4
  Using cached https://mirrors.aliyun.com/pypi/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl (1.6 MB)
Requirement already satisfied: docutils==0.16 in /home/xx/.local/lib/python3.9/site-packages (from snooty-lextudio) (0.16)
Collecting watchdog~=0.10.3
  Using cached https://mirrors.aliyun.com/pypi/packages/2d/fb/183f63f23349a77e0597c3fa0146cccc48189441849d6bb4c2be8496f693/watchdog-0.10.5.tar.gz (99 kB)
ERROR: Package 'watchdog' requires a different Python: 3.9.1 not in '>=2.7, <3.6'


```

**Detailed Steps to reproduce the problem**
in ARCHLINUX operating system:

run the commands:

sudo pacman -Syu
sudo pacman -S code

install restructruedText extension. (this will ask for snooty-lextudio's installation)

you could manually run the command:

pip install snooty-lextudio -i https://mirrors.aliyun.com/pypi/simple/

it's because the network to the international pypi's site is very poor, the aliyun-mirror is used.

i tried to install watchdog package manually, the version is not 0.10.3:
```
pip install watchdog
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: watchdog in /home/xx/.local/lib/python3.9/site-packages (1.0.2)
```
is that because there's something error in dependency config of snooty-lextudio's linux package dist? i guess... 
e.g, is it only the matter of "snooty_lextudio-1.8.6.dev0-py2.py3-none-any.whl" ?

btw, there's not the same errors in Windows10/python3.9.1

**Comment by lextm** [comment]
Duplicate to https://github.com/mongodb/snooty-parser/pull/275

Will soon ship a new snooty-lextudio release to fully address this issue.
