### ISSUE TITLE
Feature request : list editing

### ISSUE THREAD

**Issue by PierreMarchand20** [vscode-restructuredtext/vscode-restructuredtext#265]
Thank you for your extension, it is a must when working with Sphinx on VSCode. I just started using Sphinx, and having played a little bit more with markdown, I miss some features from https://github.com/yzhang-gh/vscode-markdown, in particular: https://github.com/yzhang-gh/vscode-markdown#list-editing 

For example: writing a element of a list, then hitting "enter" creates a new element in the list. Hitting twice does not. Hitting "tab" creates a new level in the list, etc.

I do not how difficult it is, but it would be very useful for lists, numbered lists and also list-tables.

**Comment by lextm** [comment]
That feature doesn't require complex things like LSP, but simple regular expressions,

https://github.com/yzhang-gh/vscode-markdown/blob/master/src/listEditing.ts

So generally speaking, it should be easy to port the relevant code over.

**Comment by lextm** [comment]
You can test the initial work in release 143.0.0 now. You can create new issues if any bug is found.

**Comment by PierreMarchand20** [comment]
Thanks! it looks good so far, I will keep you updated.

**Comment by justineheritage** [comment]
Great feature for unordered lists, but not working well for me for list-tables or ordered lists. With list-tables I'd expect the auto-bullet to do this:

```
* - some text
  -
```

But it does this:

```
* - some text
*
```

It'd also be nice to be able to leave blank list items in list-tables, or to give the option to allow blank list items entirely. Or an option to disable the list editor entirely would work too - I use list-tables extensively so if it doesn't work for those I'd prefer to just not use it at all and continue to manually edit my lists. As far as I can figure out there's no way to disable or configure the list editor right now but correct me if I'm wrong (relatively new to VSCode).

For unordered lists, it's just not incrementing the number, which is hopefully a more straightforward problem.

```
1. step 1
1. step 2
```

**Comment by PierreMarchand20** [comment]
I agree that it works well, except for list-tables. Note that Lex Li said to open another issue.

Concerning ordered lists (you said unordered, but I think you meant ordered), I had the same thought, but checking the documentation (https://sublime-and-sphinx-guide.readthedocs.io/en/latest/lists.html), it seems that one should actually use `#.` instead of `1.`, `2.` etc.

**Comment by justineheritage** [comment]
@PierreMarchand20 I did mean ordered, thank you :) And I didn't see about opening a new issue but I'll do that now.

I definitely prefer the `#` markup since it's lower maintenance, but it doesn't always work especially when you include other directives like code-block inside of a  list item - the next bullet restarts from 1 when built. So for complex lists I'm typically hard-coding the numbers. Maybe I'm marking it up incorrectly or maybe a Sphinx bug.

**Comment by lextm** [comment]
@justineheritage you should stick to ˋ#ˋ. and resetting to ˋ1.ˋ was caused by a common mistake that you didn't indent the contents between two list items along with the previous list item.
