### ISSUE TITLE
single backquote(grave,`) in a line got incorrect font color even if it's escaped, and snippets can't be used below the line

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#268]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 141.0
- [ ] Visual Studio Code version: 1.52.1
- [ ] Operating System version: Archlinux latest
- [ ] Python version: 3.9.1
- [ ] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

the text area below the line displays normal

**Actual behavior**

they are given a font color like they are still in the backquote's closure:

and, in this area, the rst snippets can't be triggered.

**Detailed Steps to reproduce the problem**
```

aaaaaaaaaaaaaaa \` bbbbbbbbbbbbbbbb

cccccccccccccccccccccccc

cccccccccccccccccccccccc

here, rst snippets can't be actiated and used.

and the font color are rendered as they were still inside the `` pair.

```
![backquote](https://user-images.githubusercontent.com/16525011/105634304-4cb67d00-5e98-11eb-9db8-0cfc580e7429.png)

**Comment by lextm** [comment]
In release 154.0.0 the old grammar file was replaced by the one from https://github.com/trond-snekvik/vscode-rst .

Close this item now as it does not appear with that grammar file.
