### ISSUE TITLE
Error for text role "code" 

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#272]
@David-Cowan

Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 142.0.0
- [x] Visual Studio Code version: 1.52.1
- [x] Operating System version: Ubuntu
- [x] Python version: 3.8.5
- [x] sphinx version: 3.4.3
- [x] A sample of conf.py or its important fragments: N/A

**Expected behavior**

The following is legal syntax in Sphinx and shouldn't produce any error.

```
:code:`foo/bar`
```

**Actual behavior**

```
Unknown interpreted text role "code".
```

![image](https://user-images.githubusercontent.com/2798822/106862332-4493e400-66c7-11eb-8429-802f900d68d4.png)

**Detailed Steps to reproduce the problem**

Paste the example above into an .rst doc.

**Comment by lextm** [comment]
Duplicate to #264
