### ISSUE TITLE
Unknown node type: citation_reference

### ISSUE THREAD

**Issue by n-batalha** [vscode-restructuredtext/vscode-restructuredtext#274]
**Environment**
- [ ] Extension version: v143.0.0
- [ ] Visual Studio Code version: 1.53.0
- [ ] Operating System version: Fedora 31
- [ ] Python version: 3.7.3
- [ ] sphinx version: N/A
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
No error

**Actual behavior**

```
Unknown node type: citation_reference
```

**Detailed Steps to reproduce the problem**

Open a file with:

```
From [ES2009]_.

 .. [ES2009]  Some reference
```

**Comment by lextm** [comment]
Closed as switching to esbonio.
