### ISSUE TITLE
snooty fails to load when the project has a virtualenv inside its directory

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#275]
**Environment**
- Extension version: 143.0.0
- Visual Studio Code version: 1.53.2
- Operating System version: Windows 10.0.19041.0 x64
- Python version: 3.9.1
- sphinx version: 3.5.1

**Expected behavior**
snooty language server loads and works.

**Actual behavior**
It fails to start with the following error in a VS Code notification:
```
NotImplementedError: Unknown node type: doctest_block at C:\Users\Segev\junk\snooty-bug\venv\Lib\site-packages\pytz-2021.1.dist-info\DESCRIPTION.rst:71
```

The cause appears to be snooty trying to load rst files from any random package installed in the virtualenv and not being very fault tolerant (Though even if it was, no user would expect to see errors for such files). This happens whether the `venv ` directory is ignored or not.

**Detailed Steps to reproduce the problem**
1. Create a new empty directory.
2. `virtualenv venv`
3. Activate the virtualenv, e.g. `Scripts/activate.bat` or `Scripts/activate.ps1`.
4. `pip install sphinx`
5. `sphinx-quickstart docs`, answer the prompts.
6. Open `index.rst`, answer the prompt to install snooty.
7. It will error and fail to load with the error listed above.

**Comment by larsoner** [comment]
I get this on a project without a venv, just a bunch of RST in the `doc` folder (which is built fine with Sphinx). For some reason it complains about line 251 [here](https://github.com/mne-tools/mne-python/blame/main/doc/overview/cookbook.rst#L251) which is just a heading:
```
Setting up the boundary-element model
```
This is on Python 3.9, Ubuntu 20.10, docutils 0.16, Sphinx dev.

- [x] Extension version: 145.0.0
- [x] Visual Studio Code version: 1.53.2
- [x] Operating System version: Ubuntu 20.10
- [x] Python version: 3.9
- [x] sphinx version: Latest dev and/or 3.1 (tried both)
- [x] A sample of conf.py or its important fragments: [here](https://github.com/mne-tools/mne-python/blob/main/doc/conf.py), though I'm not sure it matters?

**Comment by lextm** [comment]
@larsoner report a new issue please if yours is not venv related.

**Comment by lextm** [comment]
After some investigation it seems to be duplicate to #261
