### ISSUE TITLE
list editing bugs for list-tables

### ISSUE THREAD

**Issue by justineheritage** [vscode-restructuredtext/vscode-restructuredtext#277]
**Environment**
- [ ] Extension version: 143.0
- [ ] Visual Studio Code version: 1.53.1
- [ ] Operating System version: macOS 10.15.7
- [ ] Python version: 3.7.6
- [ ] sphinx version: 3.3.0
- [ ] A sample of conf.py or its important fragments: n/a

**Expected behavior**
```
.. list-table::

   * - some text
     -
```

**Actual behavior**

```
.. list-table::

   * - some text
   *
```

**Comment by lextm** [comment]
At this moment, I think it is an invalid request.

BTW, the list editing support of this extension mirrors the behaviors of the Markdown extension, https://github.com/yzhang-gh/vscode-markdown/blob/master/src/listEditing.ts

So unless the Markdown extension introduces something new, no plan here to make any change.

**Comment by justineheritage** [comment]
Ok - I don't understand how the request itself is invalid... list-table is a valid directive and the described syntax is also valid so I feel like it should at least be a consideration for future enhancements. But if it's not possible or straightforward based on the current implementation, that's fine.

As an alternate thought, is there a way to disable the list editing feature? If not, would you consider a feature request to add that as a config option? Sorry to be a pain, but I'm stuck on 142 until I can get around this issue and obviously I'd like to keep up with the other enhancements you release. Thanks.
