### ISSUE TITLE
Improvement / Feature request: Allow for a different SOURCEDIR

### ISSUE THREAD

**Issue by aureq** [vscode-restructuredtext/vscode-restructuredtext#278]
**Environment**
- [ ] Extension version: 144.0.0
- [ ] Visual Studio Code version: latest
- [ ] Operating System version: Windows 10 (Latest)
- [ ] Python version: 3.9.2
- [ ] sphinx version: latest

**Description**
By default `sphinx-build` is called with `.` as the source directory. This behavior cannot be changed. In my case, all my `.rst` files are stored `./docs`. As a result, I'm unable to preview any documents written. 
If I execute `sphinx-build` manually with the correct options and my on `SOURCEDIR` the it works just fine.

As a side note, `sphinx-build` has many options, it could be useful to allow extra args like it's already possible for the linter.

Thank you for considering this request.

**Comment by lextm** [comment]
This extension only cares about the file path of `conf.py`, not any other folder,

https://docs.restructuredtext.net/articles/configuration.html#live-preview

**Comment by aureq** [comment]
@lextm Thanks

I'm aware of the page you referenced. Unfortunately, `sphinx-build` doesn't offer ways in `conf.py` to specify both the output directory nor the location of the source documents. Your extension allows to specify the output directory. I was only asking to have a similar feature to specify the location of the source docs.

Cheers

**Comment by lextm** [comment]
Duplicate to #238
