### ISSUE TITLE
Unable to open '/Preview: 'index.rst''

### ISSUE THREAD

**Issue by WLswert** [vscode-restructuredtext/vscode-restructuredtext#28]
不知道是我没配置好还是作者安装过程没太写明白，捣鼓了一下午，全部都是不能打开rst 文件的报错。结果看到安装目录的json文件中有用到node 的命令。安装一下node.js 就可以转换了。

**Comment by lextm** [comment]
![screen shot 2016-08-20 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/425130/17829779/194cfda2-66ec-11e6-8bd4-4d7f5b91af21.png)

When any error appears, you should place the cursor on the notification and wait for a detailed error message to pop up.

Besides, this extension does not depend on node.js, so I don't think installing node.js is "a solution".

**Comment by alexdresko** [comment]
@lextm I'm getting the same error on Windows because 

![image](https://cloud.githubusercontent.com/assets/333022/23436821/e475da92-fdd9-11e6-8b9a-102a1684b3fe.png)

**Comment by lextm** [comment]
@alexdresko Please follow the [new troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide)

**Comment by swustcfl** [comment]
如果系统同时装了python3和python2.7的话，但是只安装了python3版本的sphinx的话，那下面走的流程是python -msphinx -b html . "build/html" 会导致preview不成功。
除了装一个python2版本的sphinx外还有其他办法吗？谢谢
  var python = RstDocumentContentProvider.loadSetting("pythonPath", null, "python");
        var build: string;
        if (python == null) {
            build = RstDocumentContentProvider.loadSetting('sphinxBuildPath', null);
        }
        else {
            build = python + " -msphinx";
        }
