### ISSUE TITLE
snooty fails to parse rst file: unknown node type doctest_block

### ISSUE THREAD

**Issue by larsoner** [vscode-restructuredtext/vscode-restructuredtext#281]
I work on a project with a bunch of RST files in a `doc` folder, which is built fine with Sphinx (plus a bunch of extensions). For some reason snooty complains about line 251 [here](https://github.com/mne-tools/mne-python/blame/main/doc/overview/cookbook.rst#L251) which is just a heading:
```
Setting up the boundary-element model
```
This is on Python 3.9, Ubuntu 20.10, docutils 0.16, Sphinx dev.

- [x] Extension version: 145.0.0
- [x] Visual Studio Code version: 1.53.2
- [x] Operating System version: Ubuntu 20.10
- [x] Python version: 3.9
- [x] sphinx version: Latest dev and/or 3.1 (tried both)
- [x] A sample of conf.py or its important fragments: [here](https://github.com/mne-tools/mne-python/blob/main/doc/conf.py), though I'm not sure it matters?

_Originally posted by @larsoner in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/275#issuecomment-788887476_

**Comment by lextm** [comment]
Duplicate to #261 

Snooty language server at this moment does not support directives from Sphinx extensions.
