### ISSUE TITLE
a line with a single asterisk mark/star mark(*)  will be erased after enter key pressed

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#282]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 145.0
- [ ] Visual Studio Code version: 1.53.2
- [ ] Operating System version: win10
- [ ] Python version: 3.9.1
- [ ] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
don't delete the line
**Actual behavior**

a line with a single asterisk mark/star mark(*)  will be erased after enter key pressed

**Detailed Steps to reproduce the problem**

toc tree directive with global option field *

or a normal line with a *

or indented *

```

.. toctree::
    :glob:
    :maxdepth: 1

    *[enter here, this line will be erased]


*[enter here, this line will be erased]


```

**Comment by lextm** [comment]
Related to #265 . Empty list items are being erased by this new feature, so it is by design.
