### ISSUE TITLE
Can't find snooty language server

### ISSUE THREAD

**Issue by alexreg** [vscode-restructuredtext/vscode-restructuredtext#283]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 146.0.0
- [x] Visual Studio Code version: 1.54.1
- [x] Operating System version: macOS 11.2.1
- [x] Python version: 3.9.2
- [x] sphinx version: 3.5.1
- [ ] A sample of conf.py or its important fragments: n.a.

**Expected behavior**

Extension locates Snooty correctly.

**Actual behavior**

Extension complains that it cannot find Snooty..

**Detailed Steps to reproduce the problem**

* Install Snooty manually using pip (`pip install snooty-lextudio`). The extension is not able to install the package automatically.
* Observe that extension is still unable to locate it on startup.

**Comment by lextm** [comment]
As you might have multiple Python versions installed on the same machine, it is recommended that you check the logs to see which Python installation is being used by this extension to verify snooty version,

https://docs.restructuredtext.net/articles/troubleshooting.html#find-the-logs

**Comment by alexreg** [comment]
Here you go. This looks odd, since it finds Snooty installed, but still tries to install it. There should definitely be an option in settings to let the user completely handle installing and upgrading the Snooty pip package.

```
[Log - 9:01:10 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 9:01:10 PM] OS is darwin
[Log - 9:01:10 PM] Running cmd: "/usr/local/bin/python3" -c "import sys; print(sys.version_info[0])"
[Log - 9:01:10 PM] Successful exec
[Log - 9:01:10 PM] Running cmd: "/usr/local/bin/python3" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.7.0'))"
[Log - 9:01:10 PM] Successful exec
[Log - 9:01:10 PM] Running cmd: "/usr/local/bin/python3" -c "import snooty; from distutils.version import LooseVersion; print(LooseVersion(snooty.__version__) < LooseVersion('1.8.10'))"
[Log - 9:01:10 PM] Successful exec
[Log - 9:01:10 PM] Running cmd: "/usr/local/bin/python3" -c "import pip; from distutils.version import LooseVersion; print(LooseVersion(pip.__version__) < LooseVersion('20.1.2'))"
[Log - 9:01:10 PM] Successful exec
[Log - 9:01:24 PM] Started to install Snooty...
[Log - 9:01:24 PM] Running cmd: "/usr/local/bin/python3" -m pip uninstall snooty -y
[Log - 9:01:26 PM] Successful exec
[Log - 9:01:26 PM] Running cmd: "/usr/local/bin/python3" -m pip install snooty-lextudio --upgrade
[Log - 9:01:38 PM] Error
Command failed: "/usr/local/bin/python3" -m pip install snooty-lextudio --upgrade
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/bin/snooty'
Consider using the `--user` option or check the permissions.


Error: Command failed: "/usr/local/bin/python3" -m pip install snooty-lextudio --upgrade
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/bin/snooty'
Consider using the `--user` option or check the permissions.


	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/bin/snooty'
Consider using the `--user` option or check the permissions.


[Log - 9:01:38 PM] Failed to install snooty-lextudio
[Log - 9:01:38 PM] Use Snooty language server
```

**Comment by lextm** [comment]
Can you try to run `sudo /usr/local/bin/python3 -m pip install snooty-lextudio --upgrade` at terminal and see if that helps?

**Comment by alexreg** [comment]
Yeah, that does the trick; it loads fine then. Can we avoid the requirement that the package be root-owned though? It seems unnecessary. They're owned by another user and everyone-readable, so that should be good enough?

**Comment by lextm** [comment]
It is kind of strange that `\usr\local\bin` on your machine requires `sudo` to modify. I am also using macOS, but I don't face the same issue.

**Comment by alexreg** [comment]
It's owned by the `_homebrew` user, since I use the *brewdo* software.

Generally, I don't think it's fair to assume `/usr/local` is user-*writable*. In general, in fact, it shouldn't be (according to Unix conventions).

**Comment by DmitrySokolov** [comment]
The same error.

OUTPUT: reStructuredText 
```
[Log - 02:09:09] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 02:09:09] OS is win32
[Log - 02:09:09] Running cmd: "python" -c "import sys; print(sys.version_info[0])"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Running cmd: "python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.7.0'))"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Running cmd: "python" -c "import snooty; from distutils.version import LooseVersion; print(LooseVersion(snooty.__version__) < LooseVersion('1.9.1'))"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Use Snooty language server
```

OUTPUT: Snooty Language Client
```
INFO:snooty.main:Snooty 1.9.1.dev0 starting
INFO:snooty.language_server:Started
INFO:snooty.parser:git error getting branch name: fatal: not a git repository (or any of the parent directories): .git
```

And finally NOTIFICATION:
`Couldn't start client Snooty Language Client`
Source: reStructuredText (Extension)

**Comment by lextm** [comment]
@DmitrySokolov That's irrelevant. Opened #302 for it.
