### ISSUE TITLE
emoji insertion

### ISSUE THREAD

**Issue by pur-jus** [vscode-restructuredtext/vscode-restructuredtext#284]
Hi,

Please consider my observation.

**Environment**
- [x] Extension version: 146.0.0
- [x] Visual Studio Code version: 1.54.1
- [x] Operating System version: Windows 10 1909
- [x] Python version: 3.9.1
- [x] sphinx version: 3.5.2
- [x] A sample of conf.py or its important fragments: 
```
extensions = [
    'sphinxemoji.sphinxemoji',
```

**Expected behavior**
Insert an emoji without to trig an error for the reStructuredText extension.

**Actual behavior**
When I insert an emoji within my RST doc (``|:information_desk_person:|``), the reStructuredText extension generates an error:
`(ERROR/3) Undefined substitution referenced: ":information_desk_person:".restructuredtext`

However, the preview translate and show the emoji correctly.

Is it an issue or a bad configuration?
In advance, thank you.

Julien

**Comment by lextm** [comment]
Switching to esbonio resolves this issue. Close it now.

You can upgrade to release 176.0.0.

**Comment by Setol21** [comment]
Hi, I'm having the same issue, yesterday everything was okay.

My specs:

Extension version: 176.0.0
Visual Studio Code version: 1.65.2
Operating System version: Windows 11 21H2
Python version: 3.9.7
sphinx version: 4.4.0
esbonio version: 0.9.0

My error is with any emoji, in this case the emoji :gear: -> ⚙️ :
``(ERROR/3) Undefined substitution referenced: ":gear:".restructuredtext``

Thank you for your time.

Daniel

**Comment by Setol21** [comment]
Hi! I'm having the same issue now, even with esbonio installed.

Esbonio version: 0.9.0
ReStructuredText version: 177.0.0
Python version: 3.9.7
Vscode version: 1.65.2
Sphinx version: 4.4.0

I'm using the same extension, sphinxemoji.

**Comment by lextm** [comment]
@Setol21 did you enable doc8 or rstcheck as linter? Disable them and try again.

**Comment by Setol21** [comment]
I have disabled rstcheck and it solved the problem!

Really really thank you, you are the best!

**Comment by lextm** [comment]
With changes in #359 now it is clearer from which source such messages are coming from.
