### ISSUE TITLE
IntelliSense is not available, as Snooty language server does not support multi-root workspaces right now.

### ISSUE THREAD

**Issue by sergei-dyshel** [vscode-restructuredtext/vscode-restructuredtext#286]
**Environment**
- [x] Extension version: v146.0.0
- [x] Visual Studio Code version: 1.54.1
- [ ] Operating System version: not related
- [ ] Python version: not related
- [ ] sphinx version: not related
- [x] A sample of conf.py or its important fragments: no conf.py in the project

**Expected behavior**

Extension is unobtrusive - it is not nagging about multi-root workspaces not supported by Snooty. Either Snotty should be silently disabled for multi-root workspaces or should give warning just one time.

**Actual behavior**

Each time I open multi-root project with *.rst file somewhere inside it I get this warning which I need to explicitly dismiss - very annoying.

**Comment by ssbarnea** [comment]
It seems that this error is still present in the latest version v167.0.0 of this extension and thus I will be forced to declare this extension as incompatible as current behavior is really awful.

**Comment by lextm** [comment]
Multi-root workspace is a burden for language server authors, and does not come easily in both snooty and esbonio.

Since the actual work will be done by the language server authors, close this issue here.

The restriction will be removed, once esbonio adds multi-root workspace support.

**Comment by ssbarnea** [comment]
@lextm Can you please include a link to the upstream bug, so we can watch its progress? I will be very happy to be able to use this extension again. Nowadays I almost always have multi-root workspaces, so I had to disable it globally, as there is no option to disable an extension per workspace.

**Comment by briantist** [comment]
seconding @ssbarnea's comment, the workspaces where I need this are multi-root... I would like to follow upstream progress as well

**Comment by lextm** [comment]
Alex mentioned multi-root workspace support in this comment, https://github.com/swyddfa/esbonio/issues/304#issuecomment-1059963131 There isn't yet a dedicated issue on esbonio repo to track multi-root workspace support.

**Comment by alcarney** [comment]
@briantist, @ssbarnea there's now an issue to track this swyddfa/esbonio#326.

I'd be interested to know the structure of your multi-root projects, do they contain a single Sphinx project or are there multiple? I imagine adding support for finding a single Sphinx project in a multi-root setup would be much easier than support for setups that contain multiple Sphinx projects

**Comment by jedbrown** [comment]
I work with several inter-dependent libraries that each use Sphinx, but are developed independently by different (albeit sometimes overlapping) communities. Sometimes a high level feature needs PRs to multiple projects in the stack.

**Comment by briantist** [comment]
> @briantist, @ssbarnea there's now an issue to track this [swyddfa/esbonio#326](https://github.com/swyddfa/esbonio/issues/326).
> 
> I'd be interested to know the structure of your multi-root projects, do they contain a single Sphinx project or are there multiple? I imagine adding support for finding a single Sphinx project in a multi-root setup would be much easier than support for setups that contain multiple Sphinx projects

@alcarney ,

@ssbarnea and I both work with several projects that are related to Ansible. I can't speak directly for him, but for me, none of the projects I work on are "sphinx projects" they are just projects that contain RST files, and I wanted better syntax highlighting and such.

My multi-root workspace is for development in [ansible-core](https://github.com/ansible/ansible) and several [Ansible collections](https://github.com/ansible-collections).

**Comment by ssbarnea** [comment]
I often open multiple projects that are related but they each have their own sphinx. think about multi-root workspaces as opening multiple projects.

**Comment by sarina** [comment]
I was using this extension with no problem until the last update, now I cannot use it because of the "multi-root workspace". I have all my git repos in one workspace; that's the way the vscode UI flow has you do it (I just began using vscode a few months ago and am not trying to be a super user, just editing RST). There's no menu option to create another workspace, just an option to add a folder to the (only) workspace you have. Honestly I've done some googling and I cannot figure out how you'd make multiple workspaces through the vscode UI - am I missing something really obvious? I've downgraded to 1.70.0.0 and that's fixed things.

**Comment by lextm** [comment]
I freeze this thread now. Any future discussion please uses https://github.com/swyddfa/esbonio/issues/326. Also make sure you describe clearly what is your environment setup (like how the multi-root workspace looks like), so that Alex can assert whether that's an urgent case to consider.
