### ISSUE TITLE
Unkown directive type "toctree"

### ISSUE THREAD

**Issue by efie45** [vscode-restructuredtext/vscode-restructuredtext#288]
**Environment**
- [x] Extension version: v146.0.0
- [x] Visual Studio Code version: 1.54.3
- [x] Operating System version: MacOS 11.2.3
- [x] Python version: 3.8.5
- [x] sphinx version: 3.5.3
- [ ] A sample of conf.py or its important fragments:

Getting the following error when trying to use ```.. toctree::``` in vscode .rst document:

```Unknown directive type "toctree".```

**Comment by lextm** [comment]
Cannot reproduce it yet.

Can you find anything interesting in the log? https://docs.restructuredtext.net/articles/troubleshooting.html#find-the-logs

**Comment by efie45** [comment]
Here is the output I get when I run ```>reStructuredText: Open Preview```:

```
[Log - 9:59:42 AM] Running cmd: "/usr/local/opt/python@3.8/bin/python3.8" -c "import docutils;"
[Log - 9:59:42 AM] Successful exec
[Log - 9:59:42 AM] [preview] Compiling file: {mypath}/development.rst
[Log - 9:59:42 AM] Running cmd: "/usr/local/opt/python@3.8/bin/python3.8" "/Users/{me}/.vscode/extensions/lextudio.restructuredtext-146.0.0/python-scripts/preview.py" "{myPath}/development.rst" "html" "html_body"
[Log - 9:59:43 AM] Successful exec
```

So it looks like it's successful in the logs but the preview just shows :
```
System Message: ERROR/3 (/Users/ethanfie/Code/IA_Content/Cherwell/_Development/Doc/development.rst, line 4)

Unknown directive type "toctree".

.. toctree::
```

**Comment by lextm** [comment]
By design. When you use `docutils` to preview such files, the errors are desired because `docutils` does not understand sphinx specific items.
