### ISSUE TITLE
High CPU usage sometimes on Mac

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#29]
Sometimes the preview tab takes high CPU usage.

Need to find a way to debug it.

**Comment by lextm** [comment]
Seem to be related to subscription to `onDidChangeTextDocument` event, which fires very often.

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/src/extension.ts#L30

Should investigate better way to minimize performance impact.

**Comment by slaneyrw** [comment]
The extensions spawns multiple python processes which is sending my antivirus system into overdrive.  Can we throttle the rebuild of the docs until a "quiet" time, or maybe cancel the python process if it's already running.
