### ISSUE TITLE
Extension launches many instances of sphinx-build using 100% of CPU and RAM

### ISSUE THREAD

**Issue by zaneselvans** [vscode-restructuredtext/vscode-restructuredtext#292]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

### Environment
- [x] Extension version: 146.0.0
- [x] Visual Studio Code version: 1.55.2
- [x] Operating System version: Ubuntu 20.10
- [x] Python version: 3.9.2
- [x] sphinx version: 3.5.4
- [ ] A sample of conf.py or its important fragments:

### Expected behavior
Sphinx should only rebuild the preview of the file I'm editing when I save and switch focus to the preview pane. This is typically how it behaves.

### Actual behavior
Occasionally, at what appear to be irregular intervals, several (sometimes 10+) `sphinx-build` processes will be launched, using 100% of my CPU, eating up all my RAM, and grinding my computer to a halt. It's unclear to me what is triggering this behavior, as normally only a single page gets re-rendered, and only when I save it. The 100% CPU build process can go on for more than 10 minutes, even though building the documentation from scratch normally only takes a minute or two. Sometimes I resort to quitting out of VS Code or disabling the restructuredtext plugin to make it stop.

### Detailed Steps to reproduce the problem
One thing that does seem to reliably trigger the behavior is recreating the underlying conda environment, but that's not the only time it happens. Sometimes if I stop typing, the CPU activity seems to subside, only to return when I begin editing again. Other times, the CPU keeps grinding for 5-10 minutes even if I stop typing.

**Comment by lextm** [comment]
Similar to #266

**Comment by lextm** [comment]
Resolved after switching to Esbonio.
