### ISSUE TITLE
Disabling the new list editing feature breaks all editing

### ISSUE THREAD

**Issue by wedeluxe** [vscode-restructuredtext/vscode-restructuredtext#294]
Thanks for the option to disable the very annoying list editing feature.
But sadly, doing so breaks all editing.

**Environment**
- Extension version: 149.0.0
- Visual Studio Code version: 1.54.3
- Operating System version: GNU/Linux 5.11.11-arch1-1

**Expected behavior**
Pressing `return` inserts a new line.

**Actual behavior**
Pressing `return` does nothing. Instead, it raises an error 
     "_command 'restructuredtext.extension.onEnterKey' not found_"

**Detailed Steps to reproduce the problem**

1. Set `restructuredtext.editor.listEditing.disabled` to `true`.
2. Open a .rst file.
3. Press `return`.

**Comment by lextm** [comment]
Plan to mark this option as obsolete.
