### ISSUE TITLE
list-table would make the location between editor and preview pane mismatch

### ISSUE THREAD

**Issue by kappa-wingman** [vscode-restructuredtext/vscode-restructuredtext#295]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 147.0.0
- [ ] Visual Studio Code version: 1.55.2 (VScodium)
- [ ] Operating System version: Win10
- [ ] Python version: pypy 3.7 v7.3.4
- [ ] sphinx version: n/a
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
The location of editor and preview pane location matches

**Actual behavior**
The location of editor and preview pane location mismatches

**Detailed Steps to reproduce the problem**

![image](https://user-images.githubusercontent.com/64772920/115963901-293fb480-a511-11eb-91f1-a606922e5473.png)

On the editor pane, it's the end of the doc. On the preview pane, it's still in the middle of the doc.

[sample-article.rst.txt](https://github.com/vscode-restructuredtext/vscode-restructuredtext/files/6370050/sample-article.rst.txt)
A sample article is attached here, please change the extension back to .rst

**Comment by lextm** [comment]
Duplicate to #121
