### ISSUE TITLE
Cannot lint: Linter can't be run when vscode opens a single rst doc instead of open a folder

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#298]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 149
- [ ] Visual Studio Code version: 1.55.2
- [ ] Operating System version: Win10
- [ ] Python version: 3.9.2
- [ ] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments: ...

**Expected behavior**
Linter runs ok even if the vscode edits some single rst docs.

**Actual behavior**
```
Cannot lint c:\xxx\xxx.rst. The executable '"C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\doc8.exe"' was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable

```

**Detailed Steps to reproduce the problem**
right click on some rst doc file, and select 'open with vscode' , or in command line, run code xxx.rst after all previous vscode windows are closed (in order to open the doc in a independent vscode window).

**Comment by lextm** [comment]
Cannot reproduce this, as by default this extension uses rstcheck, not doc8. It is not clear to me how you configured the settings.

**Comment by noisnemid** [comment]
I tried to reproduce this again today.
To avoid unforeseen side effects of any other extensions and settings, I uninstalled any other extensions and left rst extension only, and delete the old vscode settings and local-settings folder:

```
del c:\users\xxx\.vscode
del C:\Users\xxx\AppData\Roaming\Code
```
run a command to open a rst doc alone instead of opening it via workspace or folder:
```
code somefile.rst
```

Here are some screenshots.

![1](https://user-images.githubusercontent.com/16525011/116800645-a2ed2900-ab35-11eb-859a-95cd6f237ec5.png)
![2](https://user-images.githubusercontent.com/16525011/116800647-a680b000-ab35-11eb-95a1-eb38f36cd07b.png)

**Comment by noisnemid** [comment]
Uh...I just noticed that the screenshot's error popup windows gives a different message from the previous...
But they are just something similar, which occurs only when opening a rst doc directly with command code xxx.rst
(make sure no vscode window is opened or the rst doc will be opened in a opened vscode window)

**Comment by noisnemid** [comment]
After the cleaning, I do the next testing step:

Add the rstcheck.exe to settings:

settings.json(yep, because it's clean, so it has only these lines. The ipynb lines are generated by the python extension because I installed the python extension for I thought maybe the screenshot's error is because of python executable path, but it's not...)
```
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "restructuredtext.linter.executablePath": "C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\rstcheck.exe",
    "files.autoSave": "afterDelay"
}
```


but it errored:

```
Cannot lint c:\Users\xxx\Desktop\rstdemo\demo.rst. The executable '"C:\Users\a\AppData\Local\Programs\Python\Python39\Scripts\rstcheck.exe"' was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable
```

**Comment by lextm** [comment]
The popup on `"python"` is expected. The Microsoft Python extension seems to return an invalid value back to this extension when users make no selection on Python interpreter, and I plan to fire a bug report to them.

The extra steps you mentioned seem to be useful and I will later try them to see if I can reproduce the same issue.

**Comment by noisnemid** [comment]
A detail is:
Whether do I set the Python.exe's path, the error still occurs.
After I config the python.exe  path, snooty also errored:
settings.json
```
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "restructuredtext.linter.executablePath": "C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\rstcheck.exe",
    "files.autoSave": "afterDelay",
    "python.defaultInterpreterPath": "C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python39\\python.exe"
}
```

snooty's error
```
Snooty language server is not installed.
```
of course, the linter's error is still there.
```
Cannot lint c:\Users\xxx\Desktop\rstdemo\demo.rst. The executable '"C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\rstcheck.exe"' was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable
```
so this time there are two errors.

all these are all done when opening a single doc.


If you open a workspace, no matter you set or not set the python.exe's path or linter's path, all are ok, no errors.
All errors only when opening single doc in a single vscode window.

**Comment by lextm** [comment]
snooty is frequently updated, so "Snooty language server is not installed" sometimes indicates you are using an old version. Just modified that error message to make it clearer.

What `settings.json` are you modifying? If you open a single file (not a folder nor a workspace), there isn't a configuration file like that.

**Comment by noisnemid** [comment]
I re-installed everything, it's ok now.
