### ISSUE TITLE
docstrings render/don't render in documentation depending on module imports.

### ISSUE THREAD

**Issue by Piranha688** [vscode-restructuredtext/vscode-restructuredtext#299]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 149.0.0
- [x ] Visual Studio Code version: 1.55.2
- [ x] Operating System version: Windows
- [ x] Python version: 3.7.9
- [ x] sphinx version: 3.5.4
- [ x] A sample of conf.py or its important fragments:

```
import os
import sys

sys.path.insert(0, os.path.abspath('..'))

extensions = ['sphinx.ext.autodoc']

emplates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
autodoc_member_order = 'bysource'

```

**Expected behavior**
I expect to see docstrings from several .py scripts being shown in the generated documentation.

**Actual behavior**
Docstrings show up depending on the module imports present in the respective scripts. E.g. in below example directory tree **test.py** might contain this code:

```
import os
from src.data_science import scripts

def some_function(y):
    """
    Some docstring

    :param some_param: bla
    """

    x = 2+y
    return x

if __name__ == '__main__':
    # Something happens here
    some_function(4)
    scripts.script_utils.read_input_data() 
    3+6
```
and the documentation will be rendered successfully. Alternatively, **train_serial_LR.py** might contain the following code:

```
import os
from src.data_science.scripts.script_utils import read_input_data

def some_function(y):
    """
    Some docstring

    :param some_param: bla
    """

    x = 2+y
    return x

if __name__ == '__main__':
    # Something happens here
    some_function(4)
    read_input_data() 
    3+6
```

which leads to no docstrings being displayed in the resulting documentation.
The .rst-file integrates the docstrings using the following:

.. automodule:: src.data_science.scripts.train.test
   :members:

and

.. automodule:: src.data_science.scripts.train.train_serial_LR
   :members:

, respectively.

**Detailed Steps to reproduce the problem**
Directory Tree:
| -src
|---- data_science
|---------scripts
|---------script_utils.py
|-------------train
|-----------------test.py
|-----------------train_serial_LR.py 

Any help would be much appreciated. I'm absolutely out of ideas.

**Comment by lextm** [comment]
Can you share a small but complete GitHub repo that can reproduce this issue? I am not a Python developer myself, so it is rather difficult to follow the steps above.

**Comment by lextm** [comment]
Live preview feature has been removed from this extension, so close this issue now.
