### ISSUE TITLE
snooty not installed error but it's installed, and after I clicked 'install' button, it's ok for 1 time

### ISSUE THREAD

**Issue by noisnemid** [vscode-restructuredtext/vscode-restructuredtext#300]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 151
- [ ] Visual Studio Code version: 1.55.2
- [ ] Operating System version: win10
- [ ] Python version: 3.9.2
- [ ] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments:
- [ ] Snooty 1.9.0

**Expected behavior**
Snooty no errros, idle

**Actual behavior**
Snooty not installed error popup.

**Detailed Steps to reproduce the problem**
Snooty not installed error but it's installed, and after I clicked 'install' button, it's ok for this session: Snooty shows idle.
But next time I restart the vscode and opens a workspace, it says the error again.

**Comment by lextm** [comment]
Cannot reproduce.

**Comment by noisnemid** [comment]
I re-installed everything, it's ok now.
