### ISSUE TITLE
preview shows [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kele14x** [vscode-restructuredtext/vscode-restructuredtext#301]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: v152.0.0
- [x] Visual Studio Code version: 1.55.2
- [x] Operating System version: Windows 10
- [x] Python version: 3.9.4
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
After open a .rst file, and click preview. The preview windows shows the rendered document.

**Actual behavior**
The preview windows opens but shows blank.

**Detailed Steps to reproduce the problem**
Open a .rst file, and click preview button. 

**Additional log**
c:\users\xxx\appdata\local\programs\python\python39\python.exe: can't open file 'c:\Users\xxx\.vscode\extensions\lextudio.restructuredtext-152.0.0\out\python-scripts\preview.py': [Errno 2] No such file or directory

**Comment by kele14x** [comment]
@lextm won't you provide further information before close?

**Comment by lextm** [comment]
The simple convention is that if an issue was closed by a commit, it is fixed in the next release.

153.0.0 is live a few hours ago, so you probably already have it on your machine.

**Comment by kele14x** [comment]
@lextm wow, that's a quick fix. Thanks.
