### ISSUE TITLE
A request has failed; NotImplementedError: Unknown node type: doctest_block at .venv/lib/python3.9/site-packages/pytz-2021.1.dist-info/DESCRIPTION.rst:71

### ISSUE THREAD

**Issue by jbarlow83** [vscode-restructuredtext/vscode-restructuredtext#303]
**Environment**
- [x] Extension version: 153.0.0
- [x] Visual Studio Code version: 1.56.1
- [x] Operating System version: Ubuntu 21.04 and macOS 10.14.5
- [x] Python version: 3.9.4
- [x] sphinx version: 4.0.1
- [x] conf.py: https://github.com/jbarlow83/OCRmyPDF/blob/master/docs/conf.py

**Expected behavior**

No error when extension loads.

**Actual behavior**

When loading, two error messages appear:

1. A request has failed. See the output for more information.
2.  NotImplementedError: Unknown node type: doctest_block at .venv/lib/python3.9/site-packages/pytz-2021.1.dist-info/DESCRIPTION.rst:71

The output log for Snooty Language Client is empty.

The output log for reStructuredText is the following:

```
[Log - 11:42:57 p.m.] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 11:42:57 p.m.] OS is linux
[Log - 11:42:57 p.m.] dist: ubuntu
[Log - 11:42:57 p.m.] Running cmd: "/home/jb/src/ocrmypdf/.venv/bin/python3.9" -c "import sys; print(sys.version_info[0])"
[Log - 11:42:57 p.m.] Successful exec
[Log - 11:42:57 p.m.] Running cmd: "/home/jb/src/ocrmypdf/.venv/bin/python3.9" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.7.0'))"
[Log - 11:42:57 p.m.] Successful exec
[Log - 11:42:57 p.m.] Running cmd: "/home/jb/src/ocrmypdf/.venv/bin/python3.9" -c "import snooty; from distutils.version import LooseVersion; print(LooseVersion(snooty.__version__) < LooseVersion('1.9.1'))"
[Log - 11:42:57 p.m.] Successful exec
[Log - 11:42:57 p.m.] Use Snooty language server
```

The offending DESCRIPTION.rst block is:
```
>>> from datetime import datetime, timedelta
>>> from pytz import timezone
>>> import pytz
>>> utc = pytz.utc
>>> utc.zone
'UTC'
>>> eastern = timezone('US/Eastern')
>>> eastern.zone
'US/Eastern'
>>> amsterdam = timezone('Europe/Amsterdam')   <--- this is line 71
>>> fmt = '%Y-%m-%d %H:%M:%S %Z%z'
```

**Detailed Steps to reproduce the problem**

Something like:

Install the restructuredtext plugin in VSCode.
git clone https://github.com/jbarlow83/OCRmyPDF
open VScode in that project
`pip install -e .`
`pip install sphinx_rtd_theme`

**Comment by lextm** [comment]
Try to open just the `docs` folder as a temp workaround. I need to investigate how to ignore files in `.venv` automatically.

**Comment by AndreHorst** [comment]
+1 I am having the same issue

**Comment by lextm** [comment]
Closed as switching to esbonio.
