### ISSUE TITLE
Causes very high CPU load

### ISSUE THREAD

**Issue by kappe-cgnx** [vscode-restructuredtext/vscode-restructuredtext#304]
Issue Type: <b>Bug</b>

I see n threads of 'python -m snooty language-server' where n is the number of CPU cores. Those threads occupy 100% CPU load and don't close down for hours.

Extension version: 153.0.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a2256616772616e74227d' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.37GB free)|
|Process Argv|--crash-reporter-id 049c3f29-1441-461c-af67-56ab05a756d6|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a2256616772616e74227d' timed out.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by LiveFreeAndRoam** [comment]
I am seeing the same issue.  When `restructuredtext` starts on load, it creates more than 20 instances that run near 100% CPU.

Disabling `restructuredtext` avoids the issue.

```
$ ps -eo pcpu,pid,user,args | sort -k 1 -r  | grep user
99.8 66961 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
98.5 66959 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
96.7 67007 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
95.6 67015 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
95.1 67017 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
94.1 66985 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
93.0 67002 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
92.3 66971 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
91.4 67018 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
88.1 67026 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
87.4 66994 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
87.2 66988 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
85.9 67001 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
85.8 66992 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
84.0 67013 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
83.1 66967 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
82.7 67014 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
82.6 66981 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
78.9 67012 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
78.2 67023 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
76.6 66975 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
75.2 66989 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
74.9 67019 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
74.2 66995 user /home/user/.pyenv/versions/3.10.1/bin/python -m snooty language-server
```

Since I'm running vscode using remote-SSH to a shared system, other users are 👀 .

**Comment by lucasrangit** [comment]
I also see this. Worse. Exiting VS Code doesn't stop the processes.
