### ISSUE TITLE
Synch-scrolling of Preview pointing to wrong position

### ISSUE THREAD

**Issue by Chikuwaq** [vscode-restructuredtext/vscode-restructuredtext#305]
The synchronized scrolling feature of Preview displays a different part of the image than the code I am looking at.

**Environment**
- [ ] Extension version: v153.0.0
- [ ] Visual Studio Code version: 1.57.1
- [ ] Operating System version: Windows 10 Pro Windows_NT x64 10.0.19041
- [ ] Python version: 3.9.5
- [ ] sphinx version: 4.0.2
- [ ] A sample of conf.py or its important fragments:
extensions = [
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
]

**Expected behavior**
The preview window should scroll automatically to show a final image of the part of the code that I am looking at. 

**Actual behavior**
The preview window scrolls automatically, but too fast compared to my scroll in the code pane, thereby showing a wrong position of the preview. The preview reaches the bottom when I look at somewhere aroung the middle of the code, and it then starts moving upwards. As I approach the bottom of the code, the preview arrives at the top of the image.

**Detailed Steps to reproduce the problem**
Open an .rst source file in Visual Studio Code, press Ctrl+K Ctrl+R, and scroll in the code pane.

**Comment by lextm** [comment]
Duplicate to #121
