### ISSUE TITLE
svg image is not rendered

### ISSUE THREAD

**Issue by Kxuan** [vscode-restructuredtext/vscode-restructuredtext#307]
**Environment**
- [ ] Extension version: 155.0.0
- [ ] Visual Studio Code version: 1.58.1
- [ ] Operating System version: ArchLinux
- [ ] Python version: 3.9.6
- [ ] sphinx version: 4.0.3
- [ ] A sample of conf.py or its important fragments: No conf.py needed

**Expected behavior**
svg image successfully displayed

**Actual behavior**
svg is not rendered, leaving a blank area.

**Detailed Steps to reproduce the problem**

1. Disable HTML preview security settings
2. create a new file named `test.rst`
3. fill the content as below:
``` rst
.. raw:: html
    
    <object data="https://github.githubassets.com/pinned-octocat.svg" type="image/svg+xml">
    </object>
```
4. open preview tab

**Comment by lextm** [comment]
I cannot reproduce the issue, so you have to explain a little bit more on "Disable HTML preview security settings".

What I observed is as below,

1. When the preview tab gives you a warning message like `Some content has been disabled in this document`, you have to click the warning itself.
1. Select from the security options popped up at top, in order to change security settings.

In your case, choose `Disabled` from that list and reopen the preview tab. Then the remote svg should render properly.

**Comment by Kxuan** [comment]
> I cannot reproduce the issue, so you have to explain a little bit more on "Disable HTML preview security settings".
> 
> What I observed is as below,
> 
> 1. When the preview tab gives you a warning message like `Some content has been disabled in this document`, you have to click the warning itself.
> 2. Select from the security options popped up at top, in order to change security settings.
> 
> In your case, choose `Disabled` from that list and reopen the preview tab. Then the remote svg should render properly.

Thanks for your quick response.

It seems that my internet connection has some problems to load the remote resources. But this issue can also be reproduce using a local svg.
 
Could you please try this?

1. Download the svg image to local folder. e.g. "/tmp/test/pinned-octocat.svg"
2. Open "/tmp/test" in vscode
3. Create a file named `test.rst`, and fill the content as below:
```rst
.. raw:: html
    
    <object data="./pinned-octocat.svg" type="image/svg+xml">
    </object>

```
4. preview the `test.rst`

I have test this on another system with clean installed vscode and a Ubuntu 16.04. Both of the two system can reproduce this issue.

**Comment by lextm** [comment]
Sounds like an issue with VSCode WebView, which this extension won't be able to help much.

But you should be able to link to the SVG file using `<img src="./pinned-octocat.svg" alt="test image">` as a workaround.
