### ISSUE TITLE
Highlight Sphinx-related directives and info fields

### ISSUE THREAD

**Issue by jgcodes2020** [vscode-restructuredtext/vscode-restructuredtext#309]
**Environment**
- [x] Extension version: 155.0.0
- [x] Visual Studio Code version: 1.58.2
- [x] Operating System version: Windows 10, update 20H2
- [x] Python version: 3.8
- [ ] sphinx version: irrelevant
- [ ] A sample of conf.py or its important fragments: irrelevant

**Expected behavior**
Sphinx directives and info fields should be highlighted.
**Actual behavior**
They aren't.
**Detailed Steps to reproduce the problem**
A sample from the documentation I'm working on:
```rst
  .. cpp:function:: const m64::frame& at(uint32_t index) const
    
    Returns a reference to the :cpp:expr:`index`\th input frame of this M64.  
    Unlike :cpp:func:`m64::operator[]()`, :cpp:expr:`at()` checks input bounds.
    
    :param index: The index of the frame to get
    :return: the requested frame
    :throws std::out_of_range: if :cpp:expr:`index >= this->size()`
````
As you might have noticed, GitHub is able to syntax-highlight Sphinx directives and info fields. Your extension does not.
**Possible fix**
I messed around in the TextMate grammar, and managed to get Sphinx directives to be highlighted:
```json
		"block": {
			"begin": "^(\\s*)(\\.{2}\\s+(?:[\\w-]+:)?[\\w-]+::)(.*)",
			"end": "^(?!\\1[ \\t]|$)",
			"beginCaptures": {
				"2": {
					"name": "keyword.control"
				},
				"3": {
					"name": "variable"
				}
			},
			"patterns": [
				{"include": "#block-param"},
				{"include": "#inline-markup"},
				{"include": "#blocks"},
				{"include": "#simple-table"}
			]
		},
```

**Comment by lextm** [comment]
You might discuss this in https://github.com/trond-snekvik/vscode-rst/issues because the syntax file here is copied from that upstream.

**Comment by trond-snekvik** [comment]
A fix for this has now been implemented and released in upstream. 

@lextm Perhaps it would be simpler to use the [`extensionDependencies` field in extension manifest](https://code.visualstudio.com/api/references/extension-manifest) to let VS Code pull in the syntax highlighting instead? Currently, the two extensions will be competing for the rst files inside VS Code's language resolution engine when both are installed, and people will probably keep posting suggestions like these in downstream. 

This could be achieved by adding 
```json
"extensionDependencies": [
    "trond-snekvik.simple-rst"
]
```
to package.json, and VS Code will automatically install the syntax highlighting extension when the update is pushed.

Up to you though, the current setup also works for me :slightly_smiling_face:

**Comment by lextm** [comment]
@trond-snekvik Thanks for the message. I tried to use `extensionDependencies` but the two extensions (even removing syntax highlighting from this extension) do not work well together last time. I didn't dig further then, but copied the syntax file for quick resolution.

Will see later if a better way can be found.
