### ISSUE TITLE
Preview seems to be cached (do not show changes of rst code)

### ISSUE THREAD

**Issue by tomigaprv** [vscode-restructuredtext/vscode-restructuredtext#31]
Please provide the following information,

**Environment**
- [x] Extension version: 0.0.18
- [x] Visual Studio Code version: 1.7.1
- [x] Operating System version: Windows 7
- [x] Python version: 2.7.12
- [x] sphinx version: 1.4.8
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
1. Run preview (CTRL+K r or CTRL+SHIFT+R) 
2. Modify RST file
3. Run preview (CTRL+K r or CTRL+SHIFT+R) to see changes made after step 2

**Actual behavior**
1. Run preview (CTRL+K r or CTRL+SHIFT+R) 
2. modifiy rst file 
3. Run preview (CTRL+K r or CTRL+SHIFT+R) no modification of file are visible in preview

(Looks like cached version of file is used)

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
Can you try to upgrade to 0.0.19? Please let me know if the issue remains.

**Comment by tomigaprv** [comment]
There are still some problems... but now it looks that after some time as 1 minute after reload the page (which is still old) the content is refreshing itself. I am sure the source of delay (something in my environement or just something wrong with plugin).

**Comment by lextm** [comment]
Temp close. If it happens again we should do more troubleshooting.

**Comment by minerllabs** [comment]
If this happens to anyone, just delete the `_build` folder in your sources directory.
