### ISSUE TITLE
Erroneous linting error 'hyperlink target is not referenced'

### ISSUE THREAD

**Issue by SturmB** [vscode-restructuredtext/vscode-restructuredtext#310]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ✔ ] Extension version: v155.0.0
- [ ✔ ] Visual Studio Code version: 1.59.0
- [ ✔ ] Operating System version: Windows 10 20H2 (build 19042.1151)
- [ ✔ ] Python version: 3.8.10 64-bit
- [ ✔ ] sphinx version: 4.1.2
- [ ✔ ] A sample of conf.py or its important fragments:
```py
project = 'New PC Setup'
copyright = '2021, Chris McGee'
author = 'Chris McGee'

release = '1.0.0'

extensions = [
]

templates_path = ['_templates']

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme = 'sphinx_rtd_theme'

html_static_path = ['_static']
```

**Expected behavior**

No linting error as I am using the correct syntax.

**Actual behavior**

A linting error appears:

```
(INFO/1) hyperlink target "update-windows" is not referenced. restructuredtext
```

![image](https://user-images.githubusercontent.com/6216224/128657155-3ea82660-98be-49c8-8856-f53c0ccf9c9d.png)

**Detailed Steps to reproduce the problem**

1. Install this extension.
2. Create a `.rst` file that has an [internal reference](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role).
3. Witness the linting error above.

To be clear, the compiled HTML output works just fine. I don't know why the linter thinks there are no references.

**Workaround**

Following [this answer](https://github.com/myint/rstcheck/issues/19#issuecomment-567105828), create a `.rstcheck.cfg` file with the contents:

```
[rstcheck]
report=warning
```

Surely this mustn't be necessary, though?

---

Just in case it is needed, the restructuredtext log just has the following three lines repeating:
```log
[Log - 11:05:22 PM] Running cmd: "/bin/python3" -c "import rstcheck;"
[Log - 11:05:22 PM] Successful exec
[Log - 11:05:22 PM] [linter] Execute: "/bin/python3" -m rstcheck "/home/sturm/ansible-dotfiles/docs/update-software.rst" in /home/sturm/ansible-dotfiles.
```

**Comment by lextm** [comment]
Can you reproduce the issue merely at command line with rstcheck? If so, such issues should be reported to rstcheck developers via GitHub, https://github.com/myint/rstcheck/issues

**Comment by SturmB** [comment]
You are correct, @lextm. I've posted on their issue board now and, while I doubt anything will be done about it, at least there's another voice asking for a fix.

I am, however, having another issue that _isn't_ related to `rstcheck`, but I'll open a new issue for that since it's unrelated to this one AFAIK.

Thanks!
