### ISSUE TITLE
Feature Request: Add support for multiple restructuredtext.confPath

### ISSUE THREAD

**Issue by siyb** [vscode-restructuredtext/vscode-restructuredtext#312]
We have multiple reStructuredText directories within our repository that do not share the same configuration. It would be extremely helpful if the configuration would support multiple `restructuredtext.confPath` with project mappings. If this is already possible, please let me know.

**Comment by lextm** [comment]
If you do have multiple `conf.py` files, then you can select which one is active for the live preview engine to use,

https://docs.restructuredtext.net/articles/configuration.html#live-preview

Currently you cannot make multiple files active at the same time (as that might require a total rewrite of the live preview engine).
