### ISSUE TITLE
Backspace key does not work when editing

### ISSUE THREAD

**Issue by AndrewShepherd** [vscode-restructuredtext/vscode-restructuredtext#317]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: v161.0.0
- [ ] Visual Studio Code version: 1.59.1
- [ ] Operating System version: Windows 10
- [ ] Python version: 3.8.5
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

I press backspace in the code editor. I expect the cursor to go back one, deleting the character as it goes

**Actual behavior**

A message prompt appears:

    command 'restructuredtext.editor.listEditing.onBackspaceKey' not found

**Detailed Steps to reproduce the problem**

Bring up visual studio code, and create a file with a .rst extension. Write some text and press Backspace.
Observe that the backspaceKey does not work.

It seems to have broken "Enter" as well.

**Comment by lextm** [comment]
See the solution in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/314#issuecomment-909623401
