### ISSUE TITLE
Suggestion: Show section header breadcrumbs for the entire section

### ISSUE THREAD

**Issue by trond-snekvik** [vscode-restructuredtext/vscode-restructuredtext#318]
The extension adds section headers as document symbols, but only marks the section header itself as the symbol range, which limits the breadcrumbs navigation to only show when the cursor is in a section header:

![image](https://user-images.githubusercontent.com/7857838/131634382-74d7c316-4cf4-4e2d-950a-cfcc3591cc6d.png)

(notice how the breadcrumbs at the top just say `...`)

VS Code's built-in Markdown extension shows breadcrumbs for the entire section, so that wherever you are in the section, you can always see the current section hierarchy at the top of the editor:

![image](https://user-images.githubusercontent.com/7857838/131633467-fbc484fd-7042-41ff-b61f-528a6df62066.png)

I find this very useful, and would love to see this for reStructuredText as well. 

The syntax highlighting extension does this, but the feature is now disabled when this extension is active to avoid duplicating section symbol info.

**Comment by lextm** [comment]
Thanks. Plan to remove breadcrumbs navigation from this extension so that you can enable yours.

Will keep you updated.

**Comment by lextm** [comment]
- [ ] Wait for the pull request to be accepted.
- [ ] Wait for a new release of simple-rst.
- [ ] Release 162.0.0.
