### ISSUE TITLE
Make underline section adornment characters configurable

### ISSUE THREAD

**Issue by pwm1234** [vscode-restructuredtext/vscode-restructuredtext#319]
The list of characters used for section adornment underlines should be configurable. If it is too hard to make configurable, could you make the default follow the python documentation convention from [7. Documenting Python — Python Developer's Guide](https://devguide.python.org/documenting/#sections) which is

* ``#`` with overline, for parts
* ``*`` with overline, for chapters
* ``=`` for sections
* ``-`` for subsections
* ``^`` for subsubsections
* ``"`` for paragraphs

I have looked at ``underline.js`` and it says it is following the recommended items from http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections, but I believe that documentation is simply listing the valid set of characters and is not really recommending the order. (Even if it is, I believe the ordering from python conventions are more popular than what is listed on the rst page.) Note: if you are willing to accept the python conventions, I will gladly make a pull request with the change to underline.js. But I am not skilled enough to make the choice configurable.

Thanks for making this extension available!

**Comment by lextm** [comment]
Thanks for suggesting this. It is quite easy to implement by me, so just give me a little more time.

**Comment by lextm** [comment]
Will be shipped in vNext.
