### ISSUE TITLE
Activation failed with Japanese Language Pack Extension

### ISSUE THREAD

**Issue by noku22** [vscode-restructuredtext/vscode-restructuredtext#320]
### Expected behavior

Can be used with Japanese Language Pack extension.

### Actual behavior

No feature available.
e.g., I get an error when I click on the Preview icon.

> command 'restructuredtext.showPreviewToSide' not found

### Detailed steps

- Update 158.0.0 or later.
- Install Japanese Language Pack Extension; `ms-ceintl.vscode-language-pack-ja`

### Extension information

162.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Ubuntu 20.04.3 LTS (Windows 10 x64 WSL remote)

### Python information

3.8.10

### Sphinx information

1.6.7

### Relevant log output

```shell
Developer tools Console tab shows:

> Activating extension 'lextudio.restructuredtext' failed: Cannot find module './../../package.nls.ja.json'
> Require stack:
> - /home/xxx/.vscode-server/extensions/lextudio.restructuredtext-162.0.0/out/editor/i18n.js
(snip)
```

**Comment by lextm** [comment]
Thanks. Fixed in 163.0.0.
