### ISSUE TITLE
No module named snooty

### ISSUE THREAD

**Issue by coyoteshkw** [vscode-restructuredtext/vscode-restructuredtext#322]
I successfully installed the plug-in, but the "snooty not found" always appears when installing the real-time preview. I tried to replace the python version, but 3.9 and 3.8 were useless. There is no problem with my network
When I try to install with PIP, I will also report an error. Attempting to switch Python version is not resolved
![2021-09-06_12-23](https://user-images.githubusercontent.com/39244695/132160759-aa8b7afe-ed26-4a33-aeba-b018bcf3c6de.png)
![2021-09-06_12-29](https://user-images.githubusercontent.com/39244695/132160809-7087a8e2-d5d8-4f19-abc7-3a78d4bf1a89.png)

**Comment by lextm** [comment]
If this is not reproducible elsewhere in the world, I have no plan to investigate further.

You can set `restructuredtext.languageServer.disabled` to `true` and then restart VSCode to permanent disable snooty empowered features.
