### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BlackZork** [vscode-restructuredtext/vscode-restructuredtext#323]
### Expected behavior

I expected this, when "preview to the side is open" and I am scrolling .rst file it should show part of the file when the scroll ended

### Actual behavior

But a bug happened like this: just after scroll ended both preview and rst file is srolled back at the top.

See: https://youtu.be/y0nUWEwOalM

### Detailed steps

The steps are:
 - open preview to the side
 - scroll down using mouse wheel
 - 

### Extension information

147.0.0

### Visual Studio Code information

code-oss 1.58.0 (from repo)

### Operating system information

Arch Linux 

### Python information

python 3.9.6

### Sphinx information

sphinx-build 4.1.2

### Contents of conf.py

```python
import os
import sys
project = 'Project X'
copyright = '2021, X'
author = 'X'
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinxcontrib.plantuml',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.graphviz'
]
templates_path = ['_templates']
language = 'pl'
exclude_patterns = []
html_theme = 'furo'
```

**Comment by lextm** [comment]
Duplicate to #121
