### ISSUE TITLE
Backspace does not perform delete operation

### ISSUE THREAD

**Issue by KarthikKenny** [vscode-restructuredtext/vscode-restructuredtext#325]
Issue Type: <b>Bug</b>

I get below error when I click backspace button in keyboard while working with RST files in Code. 
I would expect delete backward operation to be performed just similar to any other editors

`command 'restructuredtext.editor.listEditing.onBackspaceKey' not found`

Extension version: 165.0.0
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by laszukdawid** [comment]
Having the same issue. Here's a related ticket https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/314.
