### ISSUE TITLE
[Bug]: smart tables: small issue with list embedded in cells

### ISSUE THREAD

**Issue by Nadano** [vscode-restructuredtext/vscode-restructuredtext#329]
### Expected behavior

for new rows generated by 'alt' + 'enter' the table looks like this (with double '|' )
+------+-------+
| a    | b     |
+------+-------+
|| - 1 || text |
|| - 1 ||      |
+------+-------+
| text | text  |
+------+-------+
 
If we place a list in these cells I'd expect them to render as a list

### Actual behavior

the list is rendered like normal text

### Detailed steps

if we modify the table and remove the double '|' from the new cell the list renders properly.
+------+-------+
| a    | b     |
+------+-------+
| - 1 | text |
| - 1 |      |
+------+-------+
| text | text  |
+------+-------+

### Extension information

v166.0.0

### Visual Studio Code information

1.61.2

### Operating system information

windows 10

### Python information

3.8

### Sphinx information

4.0.1

**Comment by lextm** [comment]
It turns out that `||` is an important syntax to allow multiple lines inside a cell, so when alt+enter generates

```
+------+-------+
| a | b |
+------+-------+
|| - 1 || text |
|| - 1 || |
+------+-------+
| text | text |
+------+-------+
```

it makes perfect sense. What's missing there is you need to go into a cell and then press tab to reformat the whole table.
