### ISSUE TITLE
Workspace settings warning: Unknown configuration setting

### ISSUE THREAD

**Issue by ottopaulsen** [vscode-restructuredtext/vscode-restructuredtext#33]
Please provide the following information,

**Environment**
- [x] Extension version: 0.0.19
- [x] Visual Studio Code version: 1.8.1
- [x] Operating System version: Windows 8.1 Pro
- [x] Python version: 3.5.1
- [x] sphinx version: 1.4.5
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

I expect to have the following in settings.json:

```
{
    "restructuredtext.confPath" : "conf.py",
    "restructuredtext.builtDocumentationPath" : "../app/help/",
    "restructuredtext.updateOnTextChanged" : "false"
}
```

**Actual behavior**

When entering the above settings, I get warnings: `Unknown configuration setting` for all three rows.

**Detailed Steps to reproduce the problem**

* Select File -> Preferences -> Workspace settings
* Paste the above settings.
* Save

**Comment by lextm** [comment]
The settings.json should be saved as `.vscode/settings.json` under the root of your Explorer tab (like other VSCode json files for debugging or tasks). Then it would be recognized.

Sorry if the original paragraph was not clear enough, and here is a updated version,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

**Comment by lextm** [comment]
Duplicate to #11.
