### ISSUE TITLE
[Feature]: Respect Inline Suggestion to improve compatibility with GitHub Copilot

### ISSUE THREAD

**Issue by benjivesterby** [vscode-restructuredtext/vscode-restructuredtext#330]
### Is your feature request related to a problem? Please describe.

Yes. Github Copilot offers inline suggestions. This plugin should deactivate when inline suggestions are made so that `Tab` can be used to accept the suggestion, similar to this issue with the markdown plugin: https://github.com/yzhang-gh/vscode-markdown/issues/1011#issuecomment-954838366

### Describe the solution you'd like

Github Copilot inline suggestions should work using `Tab`

### Describe alternatives you've considered

There is a workaround for the markdown plugin here: https://github.com/yzhang-gh/vscode-markdown/issues/1011#issuecomment-954838366 That I was not able to figure out for this plugin.

**Comment by lextm** [comment]
Should have been resolved after merging #345 .
