### ISSUE TITLE
[Feature]: note to end-users what rst documentation to check

### ISSUE THREAD

**Issue by swestlake** [vscode-restructuredtext/vscode-restructuredtext#334]
### Is your feature request related to a problem? Please describe.

the sphinx' rst site has its differences with the docutils one(which rst originates from).

should users be concerned which document to follow?

there's differences between them, 
for eg,
"::" , by itself means to add a preformatted text.

The implementation of vscode-restructuredtext does not implement this (snooty gives an error), and the sphinx site does not mention this as an option.

The other difference is the "code-block" directive, and there are other differences.
(code-block is nowhere on the docutils site)

Which reference should users apply, so they know whether their syntax is correct?

perhaps a little quick note added to a readme can help users determine where a bug or feature may reside... since it is unclear whether we should file bugs on directives that are not planned to be supported.

should we users consult
a) docutils site of rst
or
b) sphinx site of rst

-- it seems like it is b), but there's syntax supported on a) that is not in b), and the snooty parser is supporting it.

yet there is syntax not yet recognized, but I do not know if this is due to a limitation of the parser, or a developer's choice for supporting more of the "sphinx" version of rst.

### Describe the solution you'd like

a quick readme note can help users determine whether they are looking at a bug, limitation of the parser, or that their syntax will not be supported because they are referring to the docutils rst rather than sphinx's version of rst.

there should be a little note about this, otherwise we could be filing and wasting time for directives that are not planned to be implemented due to technical limitations and so on.

thanks

**Comment by lextm** [comment]
As Snooty is no longer used by this extension, close it now.
