### ISSUE TITLE
Why preferring rstcheck instead of doc8?

### ISSUE THREAD

**Issue by ssbarnea** [vscode-restructuredtext/vscode-restructuredtext#335]
I observed that this extensions supports two linters, `rstcheck` and `doc8`. The first one is the default one and doc8 can be reconfigured by user.

While I am one of the maintainers of doc8, it is not hard to observe that rstcheck repository was not touched in more than two years, no release, no merge.

Ideally this extension should work with both linters at the same time but I am not sure how easy it would be for you to resolve this.

I could add a feature to call rstcheck from inside doc8 as I already used this trick to join two other linters (ansible-lint and yamllint) but the status of rstcheck worries me, mostly because if is unmaintained I would endup having a dependency (soft or not) which may affect the useability of doc8 itself.

Please let me know what you think about this and which path we should take to improve the user experience in general.

I will take this opportunity to also suggest mentioning both `rstcheck` and `doc8` as part of extension description as at this moment if someone is searching for doc8 on marketplace, they will not find anything, even if your extension has support for it. Even reading the entire description of the extension nobody will figure it out that it supports both rstcheck and doc8. In fact it only mentions linting support related to a ruby in acknowledgments, likely a source of confusion for the average marketplace lurker.

**Comment by lextm** [comment]
1. For an extension like this, one default must be made.
2. Initially doc8 was the default and only support linter, but it had been idle for quite a while and even bugs reported by me were not fixed.
3. Switched to rstcheck, but it became idle some time afterwards.
4. snooty language server also includes linting (though not configurable).

I won't mind reevaluating which linter to be configured as default in the coming weeks.

Thanks for the suggestion on extension description. I will try to revise that in the next release.

**Comment by lextm** [comment]
Both linters (as well as other alternatives) are not well maintained (becoming idle after a few active months), so no plan to make any change here.

In the long run, it will be beneficial to move all linting rules to esbonio language server instead, which can be maintained by a group of core developers.

**Comment by lextm** [comment]
Before esbonio improves in its linting functionalities, this extension allows multiple linters to run side by side. More details can be found in #359 . The changes will be shipped in the upcoming release.
