### ISSUE TITLE
show a lot of error after i install ext reStructuredText Syntax highlighting

### ISSUE THREAD

**Issue by AITosee** [vscode-restructuredtext/vscode-restructuredtext#336]
### Expected behavior

Hi,

I use `rst` with `sphinx` to write documents.

But after I install ext `reStructuredText Syntax highlighting`, it shows a lot of error in current writting.

### Actual behavior

For example:

```rst
.. image:: xxx.png
```

It shows error : `"image" requires the following options: altsnooty(DocUtilsParseError)`

And:

```rst
xxxx

    xxxx
```

It shows error : `Unexpected indentationsnooty(UnexpectedIndentation)`

And so on...

But I checked the [rst documentation](https://docutils.sourceforge.io/rst.html) and found that my writing was correct, and there were no error or warning after compiling.

### Detailed steps

see `Actual behavior`

### Extension information

v167.0.0

### Visual Studio Code information

1.62.2

### Operating system information

linux

### Python information

3.7.7

### Sphinx information

2.1

**Comment by lextm** [comment]
Linting is an important step to tell you what's the best practice to write documentation, so snooty reports those issues to you.

If you don't want to be bothered, you can disable snooty by following https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/261
