### ISSUE TITLE
Failure to install docutils with useless error message 

### ISSUE THREAD

**Issue by markshannon** [vscode-restructuredtext/vscode-restructuredtext#338]
### Expected behavior

I expected this,
A useful error message that would help fix the problem

### Actual behavior

But a bug happened like this,

"Could not install docutils. Please run `pip install docutils` to use this extension, or check your Python path."

Don't throw away information. Provide full error code, backtrace or whatever you have.

There is no one pip, or unique Python path. At least tell which Python you are using.

### Detailed steps

The steps are,

I tried to use your extension.

### Extension information

Released on 24/11/2015, 13:45:16 Last updated 06/11/2021, 19:34:53 Identifier lextudio.restructuredtext

### Visual Studio Code information

?

### Operating system information

Ubuntu linux

### Python information

How is this relevant? I'm trying to view a rst file.

### Sphinx information

I have no idea. Again, why is this relevant?

**Comment by lextm** [comment]
https://docs.restructuredtext.net/articles/prerequisites.html

**Comment by markshannon** [comment]
Just adding a link telling me to "install docutils" is not helpful. Install where, for which Python?

I don't know which Python your plugin is using. You do.
If you are relying on VSCode to do the install, then feel free to forward this issue to them.

Would it be that difficult to include the full path to the Python you are using in the error message?
The message should not be `pip install docutils` but `$PATH_TO_PYTHON -m pip install docutils`.

**Comment by lextm** [comment]
You see most Python discussions (even PyPI) only say `pip install docutils`. People do know what Python they are using and I also made it very clear under point 2 of "Install Python for Most Features" section in the Prerequisites article that Python path is either selected by users like you explicitly or default by the Python extension.

If you do need some extra help yourself, reading the logs should be enough, https://docs.restructuredtext.net/articles/troubleshooting.html#find-the-logs

Python and reStructuredText is a huge ecosystem to study and this extension or related extensions (the Python one from Microsoft) can only help a little, not much. Microsoft also wrote about Python interpreter selection in https://code.visualstudio.com/docs/languages/python#_install-python-and-the-python-extension
