### ISSUE TITLE
Unknown configuration setting

### ISSUE THREAD

**Issue by ychab** [vscode-restructuredtext/vscode-restructuredtext#34]
**Environment**
- [ ] Extension version: 0.0.19
- [ ] Visual Studio Code version: 1.8.1
- [ ] Operating System version: ubuntu 16.04
- [ ] Python version: 3.5
- [ ] sphinx version: 1.5.1

I know this is a duplicate of https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/33 but my workspace setting conf file is in the proper path ``.vscode/settings.json`` at the root project directory (the opened folder in vscode).

These 3 settings are still mark as unknown : 

* ``restructuredtext.builtDocumentationPath``
* ``restructuredtext.makefilePath``
* ``restructuredtext.updateOnTextChanged``

I have try to restart vscode but no way, these settings are still underline by the linter with the popup message 

> Unknown configuration setting

Obvisouly, there is something missing to inform VScode what these settings are... no?

Thanks

**Comment by lextm** [comment]
The settings are announced in package.json, but I am not sure why VSCode does not recognize them.

**Comment by rkumarrb** [comment]
Facing the same issue.

**Comment by rkumarrb** [comment]
I had a look into package.json and I hope properties should come inside "configuration": { but I don't see any configuration node in package.json. Once I have added it I was able to resolve missing configuration issue. However I'm still getting the error saying "Unable to open 'Preview 'setup.rst'': Error" but it seems different issue and not related to this bug.
