### ISSUE TITLE
[Bug]: Extension parses non-documentation files in the workspace directory, causing errors to be raised

### ISSUE THREAD

**Issue by motor-dev** [vscode-restructuredtext/vscode-restructuredtext#340]
### Expected behavior

Snooty language client should only parse documentation files in my Docs folder

### Actual behavior

Snooty language client seems to parse a lot of file that are inside the workspace although they are not rst files. The language service fails to boot properly because it trips on a UnicodeDecodeError while parsing a file that is not part of my documentation folder. The exception is launched while analyzing some txt files that are downloaded by my build system; as a dependency, I sync Bullet engine and the file https://github.com/bulletphysics/bullet3/blob/master/data/widowx/bsd_license.txt is dragged into my workspace somewhere. This file is encoded in Latin1 and will trip the language server. I also suspect it is trying to parse CMakeFiles.txt and CMakeList.txt

### Detailed steps

Download the mentioned file and out it anywhere in a workspace, see Snooty raise an exception and trip.
Worth mentioning, the problem still happens if the files is excluded from the workspace in VSCode, as long as it is on disc.

### Extension information

167.0.0

### Visual Studio Code information

1.62.3

### Operating system information

Linux Debian bookworm (testing)

### Python information

3.9

### Sphinx information

4.3

### Relevant log output

```shell
Log output is missing information about the exception since it happens during the initialization of the language client. If I am not mistaken, the language server has been booted properly but the language client is sending it all files to parse and that crashes the language server without log.
The exception is:

"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1762: invalid continuation byte"

last log "[Log - 10:36:24 am] Use Snooty language server" in reStructuredText
no log in Snooty Language Client

If I manually ask Snooty to check the file, I get a more complete backtrace:

INFO:snooty.main:Snooty 1.11.5 starting
WARNING(bullet3-2.87/src/CMakeLists.txt:3ish): Definition list ends without a blank line; unexpected unindent.
ERROR(bullet3-2.87/src/CMakeLists.txt:12ish): Unexpected indentation.
ERROR(bullet3-2.87/src/CMakeLists.txt:16ish): Unexpected indentation
    Did you mean: .. blockquote::
WARNING(bullet3-2.87/src/CMakeLists.txt:16ish): Definition list ends without a blank line; unexpected unindent.
WARNING(bullet3-2.87/src/CMakeLists.txt:17ish): Block quote ends without a blank line; unexpected unindent.
WARNING(bullet3-2.87/src/CMakeLists.txt:18ish): Definition list ends without a blank line; unexpected unindent.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/parser.py", line 1023, in parse_rst
    visitor, text = parser.parse(path, text)
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/rstparser.py", line 1206, in parse
    text, diagnostics = self.project_config.read(path, text)
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/types.py", line 209, in read
    text = path.read_text(encoding="utf-8")
  File "/usr/lib/python3.9/pathlib.py", line 1267, in read_text
    return f.read()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1762: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/__main__.py", line 3, in <module>
    main()
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/main.py", line 299, in main
    project.build()
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/parser.py", line 1664, in build
    self._project.build(max_workers, postprocess)
  File "/home/yngwe/.local/lib/python3.9/site-packages/snooty/parser.py", line 1434, in build
    for sequence in results:
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1762: invalid continuation byte
```

**Comment by motor-dev** [comment]
I took a quick look at it, I think there are two problems:
- I can't seem to restrict which files get scanned by the language server, so it tries to scan many files in the workspace folder that have nothing to do with documentation at all
- If there is an exception while parsing a file, the exception propagates up to the python multiprocessing library where it gets re-thrown into the language server again and crashes it. I injected a local fix for this and verified that if the exception is caught on time (snooty/parser.py, line 1023, in parse_rst) then the language server will work just fine.

**Comment by lextm** [comment]
Switching to esbonio seems to have resolve this (at least one user reported back). So close it now.

You can upgrade to release 176.0.0 to see if everything works well.
