### ISSUE TITLE
[Bug]: add Show Source button to RST preview

### ISSUE THREAD

**Issue by WebFreak001** [vscode-restructuredtext/vscode-restructuredtext#341]
### Is your feature request related to a problem? Please describe.

Preview editors don't change the starting directory when pressing Ctrl-O to open a file, so it can be a little annoying to navigate from them. In the builtin Markdown extension there is a Show Source button in the preview:

![show source button from markdown extension](https://wfr.moe/f60EAL.png)

Additionally viewing the source may provide other benefits other than being able to edit the file.

### Describe the solution you'd like

I'd like to have a Show Source button in the rst preview like in the markdown extension, to quickly be able to open files relative to the .rst files.

### Describe alternatives you've considered

Opening both the source file and a preview side by side would work, but I would prefer only showing the preview because how I show the preview is mainly intended as read-only view with the source file not opened.

### Additional context

I'm not editing rst files myself or use this extension myself, but I'm using the `restructuredtext.showPreview` command in my extension ([code-d](https://github.com/Pure-D/code-d)) when this extension is installed to preview README files from code dependencies. Navigating with ctrl-o is a very convenient way to navigate around.

So when my extension's users have the reStructuredText extension installed and look at dependency READMEs that use .rst files they currently can't navigate to the .rst source code or open files relative to it easily.

(currently I checked the entire ecosystem of my extension and there are 16 out of 2128 packages or 0.75% using .rst files as READMEs but I think the file format is pretty useful so I'd like fully supporting it in my extension)

**Comment by lextm** [comment]
Turned out to be a bug. It will be fixed in the next release.
