### ISSUE TITLE
[New Feature] Support of PlantUML syntax highlight

### ISSUE THREAD

**Issue by tomigaprv** [vscode-restructuredtext/vscode-restructuredtext#35]
This is not an issue but new change request.

I am working with Sphinx and apart from restructuredText we are using also plantUML diagrams in the same files. Are you able to provide syntax highlight also for PlantUML which is embedded in reStructuredText file?

There are separate plugins for this (like Yog PlantUML Highlight) but it would be nice to have support it in the same file (without need to change file type - which is very annoying).

**Comment by lextm** [comment]
VSCode does not provide a way to embed one language syntax into another. I don't plan to support this request, as it would require changes to `restructuredtext.tmLanguage`.

Can you try to put PlantUML lines in a separate file (so it can be highlighted by the other extension), and then include it in the .rst file?

**Comment by tomigaprv** [comment]
Yes I working in such mode but it is not convinient. Ok, thank you for answer... then I will have to write my own plugin in some free time.

**Comment by tomigaprv** [comment]
One more comment I think the easiest way for supporting this request is just extension file with rules of syntax coloring of RST to include plantUML specific keyword (without need to support two independent files)
