### ISSUE TITLE
[Bug]: Doesn't work out of the box, no documentation on how to make it work

### ISSUE THREAD

**Issue by weegreenblobbie** [vscode-restructuredtext/vscode-restructuredtext#350]
### Expected behavior

I expected to see a rendered preview when click on the rendered preview button or pressing CTRL+SHIFT+R.

### Actual behavior

Does nothing.

### Detailed steps

Open a file and type:

```
Title
=====

Subtitle
--------

1. Item 1.
1. Item 2.
1. Item 3.
```

Then press CTRL+SHIFT+R to see the rendered preview.  Note that nothing happens.

### Extension information

v172.0.0

### Visual Studio Code information

Version: 1.64.2 (user setup) Commit: f80445acd5a3dadef24aa209168452a3d97cc326 Date: 2022-02-09T22:02:28.252Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Operating system information

Windows

### Python information

N/A

### Sphinx information

N/A

### Contents of conf.py

```python
N/A
```

### Relevant log output

```shell
Where can one find the logs?  This would be good information to put in the documentation!
```

**Comment by lextm** [comment]
Can you check #349 ?

**Comment by weegreenblobbie** [comment]
#349 does not include any documentation on how to use this extension.

**Comment by lextm** [comment]
The actual documentation site is at https://docs.restructuredtext.net

This weekend huge changes were introduced by integrating with Esbonio, so the documentation site is being updated and more to come.
