### ISSUE TITLE
[Bug]: Constant notification "No IntelliSense. Language server is disabled." when the language server is disabled in the settings

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#352]
### Expected behavior

I expected that it will simply disable it.

### Actual behavior

I get an annoying "No IntelliSense. Language server is disabled."/

### Detailed steps

1. Disable the language server in the settings.
2. Start VS Code and open an `.rst` file.

### Extension information

174.0.0

### Visual Studio Code information

1.65.0

### Operating system information

Windows 10.0.19044.0

### Python information

3.10.2 (64-bit)

### Sphinx information

4.4.0

**Comment by lextm** [comment]
Thanks for reporting this.

As the integration with esbonio is tighter and tighter, this setting is going away soon and there should be no way to disable the language server in a future release.

**Comment by segevfiner** [comment]
I hope esbonio will be really good go that extent, haven't got around to try it yet. Couldn't ever get snotty to work due to its issue with in project venv directories messing with my workflow.

**Comment by lextm** [comment]
Snooty is more of an internal project by MongoDB to serve its own scenarios, so venv support won't come easily.

Esbonio is fully driven by the community (Alex Carney) and we expect closer collaboration to improve its stability and usability for this extension.

If you check out the latest release 175.0.0, you will notice that without esbonio running properly (no error compiling your sphinx files) the whole live preview is completely disabled. That prevents many previous issues from ever happening. Again, soon it will be impossible to disable esbonio.

You should try it out as early as possible and report any bug on venv. Then we will see how to resolve them separately.

**Comment by segevfiner** [comment]
Trying it now it seems to work correctly with a venv unlike snotty, not trying to scan files inside it, correctly using the Sphinx installed in it, and so on. I think you might want to simply improve the wording on the notification to clarify that the extension is now dependent on the language server and it is a new one that should be re-enabled by users.

**Comment by lextm** [comment]
Release 175.0.0 and above actually generates a warning that live preview relying on esbonio, which might help some users to enable the language server.

One of the future releases (preferred 180.0.0 if everything goes well) will force enabling the language server for all users, so no plan to change wording at this moment.
