### ISSUE TITLE
Investigation on Python virtual environment support

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#354]
Several issues were reported over the years around Python virtual environment, including but not limited to #353, #333, #236

|      | Status | Comment |
| ---- | ------ | ------- |
| venv | up-for-grab | `activate` required |
| virtualenv | up-for-grab | `activate` required |
| conda | up-for-grab | `activate` required |
| Pipenv | preferred, in-progress | `activate` not required |

Create this task so that relevant investigation and code change can be prioritized.

**Comment by lextm** [comment]
Reported one issue to esbonio https://github.com/swyddfa/esbonio/issues/321

**Comment by beutlich** [comment]
What are the direct requirements on the Python virtual environment? Is it just esbonio?

```
esbonio==0.10.0
```

**Comment by alcarney** [comment]
For intellisense and the preview it will be `esbonio` and any other sphinx extensions, themes etc required to build your docs.

If you want to use the linters like `doc8` or `rstcheck` then they will also need to be installed.

**Comment by lextm** [comment]
Current result of this investigation is that Pipenv is the preferred option.
