### ISSUE TITLE
[Feature]: add vscode remote preview support

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#355]
### Is your feature request related to a problem? Please describe.

If you use vscode in remote mode, there is just a blank page in preview.

### Describe the solution you'd like

I would like preview to work the same in vscode remote. This means the preview must be rendered on the remote machine and transmitted to the client somehow...

**Comment by lextm** [comment]
Please use the bug template to open a bug report with enough details for investigation.
