### ISSUE TITLE
[Bug]: Preview is blank or doesn't open with Visual Studio Code Remote

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#356]
### Expected behavior

I expected Sphinx preview to work with Visual Studio Code Remote, just like I do locally:

![image](https://user-images.githubusercontent.com/2798822/157675242-9836a5ef-d3f7-434d-a860-87c1fa2b03a7.png)

### Actual behavior

First I get an error that the right version of Python is not installed, even if the workspace remotely sets up the right path to Python:

![image](https://user-images.githubusercontent.com/2798822/157677412-c6e30faf-a816-4d99-93f8-63a17e9124c5.png)

When I click on "Preview", nothing happens. There's no preview window opened.

### Detailed steps

1. Run sphinx-quickstart to create a project on a remote machine. Open .rst w/preview, works.
2. Open with Visual Studio Code remote locally and connect to the remote machine and open project created above
3. Open folder w/project created above.
5. Open .rst file w/preview, the preview is blank or it doesn't open at all.

### Extension information

v176.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Ubuntu

### Python information

3.9.7

### Sphinx information

4.4.0

### Contents of conf.py

```python
Created with sphinx-quickstart.
```

**Comment by lextm** [comment]
Can you share logs from VSCode OUTPUT panel under reStructuredText?

**Comment by oharboe** [comment]
![image](https://user-images.githubusercontent.com/2798822/157759764-b77bf4e8-64ec-47d3-b09a-0df30c8a283f.png)

```
[Log - 10:42:05 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 10:42:05 PM] OS is linux
[Log - 10:42:05 PM] dist: ubuntu
[Log - 10:42:06 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import sys; print(sys.version_info[0])"
[Log - 10:42:06 PM] Successful exec
[Log - 10:42:06 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
[Log - 10:42:06 PM] Successful exec
[Log - 10:42:06 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.9.0'))"
[Log - 10:42:07 PM] Successful exec
[Log - 10:42:52 PM] [preview] set config to [deleted]/architecture
[Log - 10:42:52 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import rstcheck;"
[Log - 10:42:52 PM] Successful exec
[Log - 10:42:52 PM] [linter] Execute: "[deleted]/.tox/py3/bin/python3" -m rstcheck "[deleted].rst" in [deleted]/architecture.
[Log - 10:42:53 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import rstcheck;"
[Log - 10:42:53 PM] Successful exec
[Log - 10:42:53 PM] Running cmd: "[deleted]/.tox/py3/bin/python3" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.9.0'))"
[Log - 10:42:53 PM] Successful exec
```


```
Trace - 10:46:16 PM] Sending request 'textDocument/codeAction - (6)'.
Params: {
    "textDocument": {
        "uri": "file://[deleted].rst"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 10:46:16 PM] Received response 'textDocument/codeAction - (6)' in 9ms.
Result: []
```

![image](https://user-images.githubusercontent.com/2798822/157760204-7b37d4ae-be3e-472b-91bd-8c5cb9415269.png)

**Comment by oharboe** [comment]
aha!

This tells me what is going on. This build is running on the client (where the vscode remote GUI runs) and not on the remote machine, hence the file can't be found. The solutin is to run the Sphinx build on the remote machine, not the machine that runs vscode remote GUI.

```
[esbonio.lsp] Traceback (most recent call last):
  File "[deleted]/.tox/py3/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 327, in build
    self.app.build()
    [deleted]
  File "[deleted]/.tox/py3/lib/python3.9/site-packages/sphinxcontrib/datatemplates/loaders.py", line 115, in load_json
    with open(absolute_resolved_path, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '[deleted]foo.json'
[Trace - 10:52:12 PM] Received notification 'window/showMessage'.
Params: {
    "type": 1,
    "message": "Unable to build documentation, see output window for details."
}
```

**Comment by oharboe** [comment]
Actually... It's working now.

I'm closing this github issue and reopening if I find that I didn't just confuse myself.
