### ISSUE TITLE
virtualenv is not used

### ISSUE THREAD

**Issue by therealmarv** [vscode-restructuredtext/vscode-restructuredtext#36]
Please provide the following information,

**Environment**
- [x] Extension version: 0.0.21
- [x] Visual Studio Code version: 1.8.1
- [x] Operating System version: macOS 10.12.3
- [x] Python version: 2.7.13
- [x] sphinx version: Sphinx (sphinx-build) 1.5.1

**Expected behavior**
sphinx builds and I see a preview

**Actual behavior**
Error message, no preview

**Detailed Steps to reproduce the problem**
I do not want to install sphinx globally but I have no problem installing it in a VirtualEnv.
I already use the [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode) Plugin and in my `.vscode/settings.json` is already the alternative virtualenv python interpreter set:

```
{
    "python.pythonPath": "/Users/auser/.virtualenvs/pybossa/bin/python",
}
```

would be nice to be able to set virtualenv globally or project wide for this plugin. Thanks.

**Comment by lextm** [comment]
https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

You have to set the required environment variable as Extra Notes suggests. 

I am not quite familiar with virtualenv yet, so I might do some investigation later.

**Comment by therealmarv** [comment]
oh no problem. Here some useful information:
Virtualenv is something which modifies the shell environment so that an encapsulated python is used. The problem with this when looking at VSCode: VSCode is not a python program and lives outside Virtualenv so it cannot see itself if there is an VirtualEnv activated.

This is why the famous pythonVSCode plugin uses the `python.pythonPath` environment. My shinx binaries are in my case here:
```
/Users/marvin/.virtualenvs/pybossa/bin/sphinx-build
/Users/marvin/.virtualenvs/pybossa/bin/sphinx-autobuild
```

So if your plugin would provide a variable which I can modify globally and project wide which defines where the sphinx-binaries are located I would be fine. Additionally, if they not exist you can also check additionally `python.pythonPath` and if there are the sphinx binaries. If nowhere found: error :)

(just a suggestion)

**Comment by lextm** [comment]
Thanks for the info.

Can you try at terminal to set environment variable `SPHINXBUILD` to `/Users/auser/.virtualenvs/pybossa/bin/python /Users/marvin/.virtualenvs/pybossa/bin/sphinx-build`? And then you use `code` at terminal to launch Visual Studio Code. Then this extension should be able to work.

Will see if I can make this a setting to set in config file.

**Comment by lextm** [comment]
`restructuredtext.sphinxBuildPath` is introduced in 25.0 release to support what you want. No plan to use Python's setting yet, as I am not quite sure how it works.

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

**Comment by lextm** [comment]
Since release 26.0, if you set `python.pythonPath`, this extension will load sphinx build from there. This should completely match your expectation of running in VirtualEnv.
