### ISSUE TITLE
[Bug]: POSIX path of confPath is changed to Win path

### ISSUE THREAD

**Issue by beutlich** [vscode-restructuredtext/vscode-restructuredtext#362]
### Expected behavior

I expected that the POSIX path in the `"restructuredtext.confPath"` setting of settings.json is not touched.

Configuration is:

```json
{
    "restructuredtext.confPath": "${workspaceFolder}/Docs/source"
}
```

but after usage it is changed to

```json
{
    "restructuredtext.confPath": "${workspaceFolder}\\Docs\\source"
}
```

### Actual behavior

But a bug happened like this! See above.

### Detailed steps

The steps are:

* Open VS Code
* Open RST file
* Open Preview and wait until snooty/esbonio build is finised.

### Extension information

1.170.0 or 1.178.0

### Visual Studio Code information

```
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

### Operating system information

Windows

### Python information

3.7.3 64-bit

### Sphinx information

2.1.12

**Comment by beutlich** [comment]
Any comment please?

**Comment by pgerell** [comment]
I see the same behaviour with the "esbonio.sphinx.confDir" setting.
"esbonio.sphinx.confDir": "${workspaceFolder}/docs"
is changed to 
"esbonio.sphinx.confDir": "${workspaceFolder}\\docs"

**Comment by alcarney** [comment]
I haven't debugged this yet to confirm, but my guess this is happening due to the [confiuration logic](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/82c4a3d5cec5b4cc4be397be63b9dfc4719819f9/src/util/configuration.ts#L243) making use of the `fsPath` field of the URI object (which I believe localises a path to backslashes on Windows) rather than the `path` field.

**Comment by lextm** [comment]
Deep down inside, Node.js has its own messy (incompatible/inconsistent) API surface around `fs` and `path` that only `fsPath` works consistently on different platforms. So I don't want to waste time on something out of my control.

Pull requests are welcome though, in case anyone does have the time to work on that.

**Comment by ebbez** [comment]
Haven't really worked with JS or this project for very long, but would [this](https://github.com/ebbez/vscode-restructuredtext/commit/e0109ec032b3a366a9b7fb42f7217e1464d0c478) solve this issue?

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.
