### ISSUE TITLE
[Bug]: The status bar has two nits

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#363]
### Expected behavior

1. The status bar should stop showing "Preview is loading" after esbonio has failed
2. The Esbionio part of the status bar will disappear after it has failed.

![image](https://user-images.githubusercontent.com/2798822/158756649-4298ff74-a4bb-4fc6-b27c-3c38127c777c.png)

### Actual behavior

1. The status bar continus to show "Preview is loading"
2. I have to restart visual studio code to start up Esbonio again.

### Detailed steps

1. Create a sphinx project that fails to build
2. Open preview

### Extension information

v178.0.0

### Visual Studio Code information

1.63.2

### Operating system information

Ubuntu 20.10

### Python information

3.8.10

### Sphinx information

4.4.0

**Comment by lextm** [comment]
Resolved in release 180.0.0.
