### ISSUE TITLE
[Bug]: reSTructuredText complains about out of date esbonio if default python path does not have esbonio

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#366]
### Expected behavior

If I specify a virtualenv with Esbonio, I should not have to specify the default python path.

```
{
    "esbonio.server.pythonPath": "/home/oyvind/ascenium/ascenium/workflow/.tox/py3/bin/python",
    "esbonio.sphinx.srcDir": "source/"
}
```

### Actual behavior

Unless I add defaultInterpreterPath, I get an error that Esbonio is out of date.

```
{
    "esbonio.server.pythonPath": "/home/oyvind/ascenium/ascenium/workflow/.tox/py3/bin/python",
    "esbonio.sphinx.srcDir": "source/",
    "python.defaultInterpreterPath": "/home/oyvind/ascenium/ascenium/workflow/.tox/py3/bin/python"
}
```

![image](https://user-images.githubusercontent.com/2798822/159254944-817e1369-d5df-4269-9d9c-97acbe14f0d7.png)

### Detailed steps

As above.

### Extension information

v180.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Ubuntu 21

### Python information

3.9.7

### Sphinx information

4.4.0

**Comment by lextm** [comment]
`esbonio.server.pythonPath` is not yet supported by this extension.

To support it, more changes are required but not enough time to work on that right now.

**Comment by lextm** [comment]
Revised how virtual environments should be set up and configured for this extension,

https://docs.restructuredtext.net/articles/prerequisites#virtual-environments
