### ISSUE TITLE
How to see extended logs

### ISSUE THREAD

**Issue by tomigaprv** [vscode-restructuredtext/vscode-restructuredtext#37]
This maybe related not necessary to plugin itself but maybe to Visual Studio Code.

How can I see detailed problems which are behind the error.
As you can see preview is not working because some problem. Unfortunately exception stack is truncated and cannot be easy copy/paste.

![error](https://cloud.githubusercontent.com/assets/23699395/22589230/87de1328-ea09-11e6-995b-b7ba72e0690b.png)

Do you have some kind of debug window which detailed information about exception is displayed / logged? If not maybe it is good idea to put it somwhere in output window.

**Comment by lextm** [comment]
This extension simply executes `make html` at the makefile folder. So if you run the same command at terminal (command prompt) you should be able to reproduce the same error message.

**Comment by tomigaprv** [comment]
Unfortunately it work on command line: make html do provide any error. Maybe the problem is that ther are a lot of logs/warnings put into the console and maybe some internal buffers are not able to handle this. It would be nice to have some some log to be put in the output/console/debug window. (I am not sure which of it suits the best for this kind of tracing)

**Comment by tomigaprv** [comment]
Just for future reference... It was necessary to install additinal component (I think my friends didn't read documentation).
pip install sphinx-autobuild

**Comment by lextm** [comment]
Thanks for sharing the solution.
