### ISSUE TITLE
"intellisense and live preview are not available. Esbonio language server does not support multi-root workspaces" In VSC , when I click the preview button, there's nothing but this hint.

### ISSUE THREAD

**Issue by Kimtaehung123** [vscode-restructuredtext/vscode-restructuredtext#371]
### Expected behavior

In VSC , when I click the preview button, I can see the preview.

### Actual behavior

when I click the preview button, there's nothing but this hint. And I don't know how to solve this.

### Detailed steps

1.write a "xx.rst" file;
2.click the "preview" button in VSC;

### Extension information

reStructuredText.183.0.0

### Visual Studio Code information

visual studio code.1.65.2

### Operating system information

Windows10  19043.1586

### Python information

python.3.7.4

### Sphinx information

sphinx-build.3.5.3

**Comment by lextm** [comment]
Duplicate to #286
