### ISSUE TITLE
[Feature]: new built-in restructuredText syntax highlightning

### ISSUE THREAD

**Issue by blaylockbk** [vscode-restructuredtext/vscode-restructuredtext#372]
### Is your feature request related to a problem? Please describe.

This topic is not an issue, but I wanted to point out that the March 2022 VS Code update comes with built-in restructuredText syntax highlighting.

https://code.visualstudio.com/updates/v1_66#_restructuredtext-grammar

### Describe the solution you'd like

Does this update to VS Code mean anything can be updated in this extensions or it's docs?

Thanks for providing this extension.

**Comment by lextm** [comment]
Thanks. I am already aware of that change, but installing vscode-rst is still preferred,

* It's the master source of syntax highlighting right now (VSCode repo copies from the same place).
* It also provides section navigation.
