### ISSUE TITLE
[Bug]: "esbonio: Failed" / "Unable to start language server." on Windows 

### ISSUE THREAD

**Issue by rainerth** [vscode-restructuredtext/vscode-restructuredtext#377]
### Expected behavior

I expected the esbonio server to start successfully to see rst preview as a feature of the reStructuredText extension. 

### Actual behavior

But a bug happened like this: When starting vscode or when reloading after extension up-/downgrade the error "Unable to start language server. See output window for more details" shows up. In the status line "esbonio: failed" shows up immediately. No helpfull error messages can be found. Just "RESTARTING SERVER".

On a similar system unter Linux the server runs fine. 

Starting esbonio from Windows terminal shows no errors. 

### Detailed steps

Start vscode reStructuredText 184.0.0 installed. 

I have a Linux and an Windows system with similar settings. On my Linux system with the same settings vscode starts esbonio correct.

On Windows vscode displays "esbonio: Failed" / "Unable to start language server. See output window for more details". There no further details in the output window except "RESTARTING SERVER".

Starting esbonio within an vscode terminal (Windows) there are no issures.

### Extension information

v0.10.3

### Visual Studio Code information

1.66.1

### Operating system information

Windows 10

### Python information

3.10.2 64-bit

### Sphinx information

4.5.0

### Contents of conf.py

```python
import os
import sys
from datetime import datetime
from os import environ

sys.path.append(os.path.abspath("./_ext"))

extensions = [
	'sphinx.ext.imgconverter',
	'sphinx.ext.graphviz',
	'sphinx.ext.todo',
	'sphinx.ext.ifconfig',
	'releases',
	'userlevel',
	'myst_parser'
]


tls_cacerts = '_static/trumpf.pem'

def setup(app):
	from sphinx.util.texescape import tex_replacements
	tex_replacements += [(u'♮', u'$\\natural$'),
						 (u'ē', u'\=e'),
						 (u'♩', u'\quarternote'),
						 (u'↑', u'$\\uparrow$'),
						 (u'❌',u'X'),
						 (u'❗',u' !! '),
						 (u'▸', u'$\\triangleright$'),
						 (u'➥', u'$\\rightarrow$'),
						 (u'±',u'$\\pm$'),
						 (u'α', u'$\\alpha$'),
						 (u'β', u'$\\beta$'),
						 (u'γ', u'$\\gamma$'),
						 (u'Δ', u'$\\delta$')
						]
	app.add_config_value('releaselevel', '', True)
	app.add_config_value('isTPC', '', True)
	app.add_config_value('isOCT', '', True)


project = '22-50-12-A4-CR'

templates_path = ['_templates']

language = 'de'
smartquotes = True

html_theme = 'sphinx_book_theme'
html_static_path = ['_static']
html_logo = '_static/logo.jpeg'
html_favicon = "_static/trumpf_logo.ico"

html_css_files = [
    'css/trumpf.css',
]

locale_dirs = ['./_locales']
latex_engine = 'xelatex'
latex_logo = '_static/logo.jpeg'

latex_elements = {
	'inputenc': '',
	'utf8extra': '',
	'papersize': 'a4paper',
	'extraclassoptions': 'openany,oneside',
	'pointsize': '11pt',
	'figure_align': 'H',
	'fontpkg': r'''
\setlength{\headheight}{13.8pt}
\setmainfont{Gillius ADF}
\setmonofont{FreeMono}
''',
	'preamble': r'''
\renewcommand*\sfdefault{ugq}
\usepackage{fontspec}

\usepackage[T1]{fontenc}
\usepackage[default]{gillius}
\usepackage{enumitem}\setlistdepth{99}

\setlength{\tymin}{40pt}
\setlength{\tabcolsep}{1.6em}
\renewcommand{\arraystretch}{1.5}

\usepackage[titles]{tocloft}
\cftsetpnumwidth {2.25cm}\cftsetrmarg{2.5cm}
\setlength{\cftchapnumwidth}{1.75cm}
\setlength{\cftsecindent}{\cftchapnumwidth}
\setlength{\cftsecnumwidth}{2.25cm}

''',

	'printindex': r'\footnotesize\raggedright\printindex',

}

gettext_uuid = True
gettext_compact = False

docscope = os.getenv('DOCSCOPE') or 'internal'

exclude_patterns = [
	'_build', 'Thumbs.db', '.DS_Store', '_input', 'node_modules'
]
```

### Relevant log output

```shell
C:\Users...>python -m esbonio --version
v0.10.3

C:\Users...>esbonio --version
v0.10.3
```

**Comment by lextm** [comment]
You will have to debug the source code and see what's wrong there,

https://docs.restructuredtext.net/articles/development.html#build-from-source

(No need to debug esbonio)

The break point can be set on line 179, https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/src/language-server/client.ts#L179

**Comment by thclark** [comment]
Same thing occurring (well same symptoms appearing) on OSX so may not be a purely windows thing. I'll debug if I get time, but have some much more critical stuff to fix so doing docs the old fashioned way for now!

**Comment by thclark** [comment]
OK, it may be to do with duplicate conflicting settings. I had identical symptoms to the OP... I also had a notice about `restructuredtext.confPath` being deprecated in favour of `esbonio.sphinx.confDir`... but in my `.devcontainer.json` file I had already made that change... so was irritated but passively ignoring it.

However, I just noticed that in my `.vscode.settings.json` file I had a duplicate... It looked like this:
```js
{
  "restructuredtext.confPath": "${workspaceFolder}/docs/source",
  "restructuredtext.languageServer.disabled": true, // I had the same issue in two projects, this was in only one so I don't think it was this, but who knows...
  "esbonio.sphinx.confDir": "${workspaceFolder}/docs/source"
}
```

I deleted all three of these (.devcontainer now the single source of truth), restarted esbonio and it's now working... So there's something there about deprecated settings causing a conflict. So @rainerth the best thing to do is make sure to clean up your settings then reload, before getting into more serious debugging.

**Comment by nightduck** [comment]
I got a similar issue on Ubuntu 22.04. Following a trail of breadcrumbs, I noticed the esbonio failed to start because "module attrs is missing". Running the following command on a terminal outside of vscode rectifies the issue

    python3.10 -m pip install --force-reinstall --upgrade attrs

Reload vscode and rst files can now be successfully previewed.

**Comment by lextm** [comment]
@nightduck That's tracked in swyddfa/esbonio/issues/147. Sadly no good solution than manually fixing the dependency.

**Comment by illume** [comment]
Reinstalling attrs like [nightduck](https://github.com/nightduck) says in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/377#issuecomment-1485541164 fixed it for me. cheers! 🍺

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.
