### ISSUE TITLE
[Feature]: Support setting to provide any sphinx parameter

### ISSUE THREAD

**Issue by twodrops** [vscode-restructuredtext/vscode-restructuredtext#379]
### Is your feature request related to a problem? Please describe.

Sphinx run is currently not configurable. It would be nice to provide any sphinx parameter to the sphinx run of the extension,
This is required to ensure incremental behavior between the esbonio build and any sphinx build that is run outside of esbonio on the same project (if the same build folder is used). If the parameters of both builds are same sphinx will reuse the doctree and can ensure incremental build between esbonio and external build.

### Describe the solution you'd like

It would be nice to have a setting as text field where any sphinx parameter can be configured. For example, 
'-t <tag> -j auto'

### Additional context

On the user side the command line parameters of sphinx could be supported. Parameter translation  to Sphinx APIs might be needed for implementing this.

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.
