### ISSUE TITLE
[Feature]: Support parallel build

### ISSUE THREAD

**Issue by twodrops** [vscode-restructuredtext/vscode-restructuredtext#380]
### Is your feature request related to a problem? Please describe.

Does not make use of the `-j auto` feature when starting sphinx build. Make it available as a configurable UI setting or a configurable parameter setting for any sphinx parameter. See https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/379

### Describe the solution you'd like

For large projects, build takes too long

**Comment by lextm** [comment]
Release 186.0.0 enables the new setting `esbonio.sphinx.numJobs`.
