### ISSUE TITLE
Broken in Code 1.9

### ISSUE THREAD

**Issue by waynebrantley** [vscode-restructuredtext/vscode-restructuredtext#39]
Please provide the following information,

**Environment**
- [ 0.0.21] Extension version:
- [1.9.0 ] Visual Studio Code version:
- [ Win 10] Operating System version:
- [3.5.2 ] Python version:
- [ 1.4.5] sphinx version:
- [ ] A sample of conf.py or its important fragments:

VS Code updated to 1.9 Jan release.
Ctrl+K+R opens the preview window, but it does not show anything.  No errors, just an empty window.
Further investigation shows the _build folder was create and all files generated.

I installed 1.8.1 and it worked again.
I exited 1.8.1 and it updated itself to 1.9 and it was broken once again.

**Comment by lextm** [comment]
Related to #38 

It seems that VSCode 1.9.0 introduces many changes that I do not yet fully understand. It would be a difficult issue to fix too, as I could not get the debugger working either.

**Comment by waynebrantley** [comment]
Sounds messy.  Worst thing is it automatically updates...so going back a version is impossible (unless autoupdate can be turned off somehow).   Everything seems to work except for the display!  Good luck on the debugger!

**Comment by dlech** [comment]
Looks like it is working again in vscode 1.9.1

**Comment by waynebrantley** [comment]
Agree!  Thx.

**Comment by lextm** [comment]
Related to https://github.com/Microsoft/vscode/issues/20229
