### ISSUE TITLE
Depend on upstream Esbonio extension?

### ISSUE THREAD

**Issue by alcarney** [vscode-restructuredtext/vscode-restructuredtext#391]
### Is your feature request related to a problem? Please describe.

I think it would be worth trying to get to a state where the vscode-rst extension can rely on the Esbonio extension for its integration with the language server. This way the VSCode client can be developed in lockstep with the server and vscode-rst gets the latest developments 'for free'. There's quite a few changes coming in swyddfa/esbonio#382 and it would make sense for this kind of thing to only be implemented once.

### Describe the solution you'd like

- The `EsbonioClient` already exposes a number of [hooks](https://github.com/swyddfa/esbonio/blob/37dc99c4b15ce8c6e17647649d0a5576e41d7132/code/src/lsp/client.ts#L364) that vscode-rst can use to react to events such as buildComplete etc.
 It would be easy enough to extend these to cover what might be missing a well as a command like `esbonio.client.getInstance` that vscode-rst can call to get a reference to the `EsbonioClient`
- The Esbonio extension can drop its preview implementation in favour of the one provided by vscode-rst. This way the Esbonio extension can focus purely on the integration with the language server.
- It should be possible for the Esbonio extension to check for the existence of any newer VSCode APIs (such as language status items) before their use, allowing for the extension to still work under older VSCode installs. 
- VSCode now supports [pre-releases](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions) for extensions, which we could use to verify things still work before pushing any big updates.

Let me know your thoughts :smile:

**Comment by lextm** [comment]
Thanks for the advice. There are a few things under the way,

1. This repo started to utilize the pre-release support in VS Code plus Rollbar to collect analytics from VS Code Insider users. More to come in that direction in the coming weeks.
2. The live preview in this repo is going away gradually, but a few things need to be planned in advance. More to track separately regarding the migration.
3. This repo uses a customized version of `EsbonioClient`, which is also going away in the long term.

**Comment by lextm** [comment]
Close this issue now. Remaining tasks will be tracked in swyddfa/esbonio/issues/708
