### ISSUE TITLE
[Bug]: Esbonio builds forever

### ISSUE THREAD

**Issue by argideritzalpea** [vscode-restructuredtext/vscode-restructuredtext#393]
### Expected behavior

I expected:
Esbonio server tab to discontinue “building” and finally render pages.

Settings.json:

{
    “esbonio.server.enabled”: True,
    “esbonio.sphinx.buildDir”: “${workspaceFolder}/docs/build/html”,
    “esbonio.sphinx.confDir”: “${workspaceFolder}/docs/source”
}

VSCode Project structure:
[projdir]
->docs
->->build
->->->html
->->source

### Actual behavior

But:
The esbonio server tab in the bottom right “builds” forever - it never renders the preview. The preview page says that it’s “busy”.  The link to the troubleshooting guide does not give information on reading the “Diagnostics information [that] has been written to OUTPUT | Esbonio Language Server Panel” to determine if Esbonio is actually doing anything. 

When I click to restart esbonio server tab in VSCode after several minutes of it hanging, the tab / button just vanishes.

### Detailed steps

I set up settings.json as listed in the instructions on the website.

How do I debug the esbonio server as it is integrated in this extension? It would be great to help and contribute but there are not documented steps for debugging the esbonio extension in VsCode as it is embedding in restructuredText.

### Extension information

189.0.0

### Visual Studio Code information

1.67.2

### Operating system information

Linux

### Python information

3.8

### Sphinx information

4.5.0

**Comment by alcarney** [comment]
In the Esbonio Language Server output window do you see any build output from Sphinx? By default the server should at least be sending that information.

You can also set the `esbonio.server.logLevel` option to `debug` to (hopefully) start seeing message about what the server is doing internally.

**Comment by andlessa** [comment]
Hi,

I'm having the same exact issue. It seems to just get stuck. I've checked the debug and it is not very telling (see below).
Do you have any suggestions on how to fix it?

I'm running VSCode (v1.80.1) with reStructuredText (v189.3.0).


[Log - 7:46:39 AM] Server start command: /bin/python -m esbonio
[Log - 7:46:39 AM] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"${workspaceFolder}/docs/manual/source","forceFullBuild":true,"numJobs":"auto","buildDir":"${workspaceFolder}/docs/manual/source/_build"},"server":{"logLevel":"debug","logFilter":[],"hideSphinxOutput":true,"enableScrollSync":true}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 7:46:39 AM] Starting Language Server
[esbonio.lsp] Loaded extension 'esbonio.lsp.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.roles'
[esbonio.lsp] Loaded extension 'esbonio.lsp.rst.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.rst.roles'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.autodoc'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.codeblocks'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.domains'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.images'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.includes'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.roles'
[esbonio.lsp] Workspace root 'file:///home'
[esbonio.lsp] User Config {
  "buildDir": "${workspaceFolder}/docs/manual/source/_build",
  "confDir": "${workspaceFolder}/docs/manual/source",
  "forceFullBuild": true,
  "numJobs": "auto"
}
[esbonio.lsp] Sphinx Args {
  "buildername": "html",
  "confdir": "/home/docs/manual/source",
  "confoverrides": {},
  "doctreedir": "/home/docs/manual/source/_build/doctrees",
  "freshenv": true,
  "keep_going": false,
  "outdir": "/home/docs/manual/source/_build/html",
  "parallel": 8,
  "srcdir": "/home/docs/manual/source",
  "status": null,
  "tags": [],
  "verbosity": 0,
  "warning": null,
  "warningiserror": false
}
WARNING in warnings._showwarnmsg() in 109: <unknown>:580: DeprecationWarning: invalid escape sequence '\ '

WARNING in warnings._showwarnmsg() in 109: <unknown>:2: DeprecationWarning: invalid escape sequence '\ '

Cancel notification for unknown message id "1"
Cancel notification for unknown message id "2"

**Comment by MatteoSchiavinato** [comment]
Same issue here.

**Comment by lextm** [comment]
No plan to work on 189.0.0 any more. If you can reproduce the same issue with 190.1 release, please open a new issue and share details.
