### ISSUE TITLE
[Bug]: The preview button can't be used

### ISSUE THREAD

**Issue by mendax1234** [vscode-restructuredtext/vscode-restructuredtext#395]
### Expected behavior

l expect: When l click the preview button , it will show the preview page.

![image](https://user-images.githubusercontent.com/62934294/175935046-4ea1ceae-9bcd-4cb4-a0e3-31b74c0e8fb4.png)

The python extension seems to be loading all the time . l don't know why , l guess that this extension just doesn't load at all!

Can anybody help me with it? @vscode-restructuredtext

Best
Daniel

### Actual behavior

But a bug happened like this. This prevew button just doesn't work!

### Detailed steps

The steps are.

No steps . At the beginning the extension can't be used

### Extension information

v189.0

### Visual Studio Code information

1.68.1

### Operating system information

windows10

### Python information

python 3.9

### Sphinx information

forget

### Contents of conf.py

```python
# Configuration file for the Sphinx documentation builder.

# -- Project information

project = '6940 Swerve Documentation'
copyright = '2022, Wenbo Zhu (mendax1234)'
author = 'Wenbo Zhu (mendax1234)'

release = '0.1'
version = '0.1.0'

# -- General configuration

extensions = [
    'sphinx.ext.duration',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx_panels',
    'sphinx_search.extension',
    'sphinx.ext.mathjax',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}
intersphinx_disabled_domains = ['std']

templates_path = ['_templates']

# List of languages that frc-docs supports
localization_languages = [
    "en",
    "zh_CN",
]

# multi-language docs
language = 'en'
locale_dirs = ['../locales/']   # path is example but recommended.
gettext_compact = False  # optional.
gettext_uuid = True  # optional.

# -- Options for HTML output

html_theme = 'sphinx_rtd_theme'

# Sidebar logo
html_logo = "assets/6940violetz-transparent.png"

# -- Options for EPUB output
epub_show_urls = 'footnote'

# Required to display LaTeX in hover content
hoverxref_mathjax = True

# Use MathJax3 for better page loading times
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
```

**Comment by EricThomson** [comment]
I am experiencing this on Windows 10. @mendax1234 what made it go away for you?

**Comment by lextm** [comment]
Python extension issues belong to its own repo, https://github.com/microsoft/vscode-python, not here.

@EricThomson If you experience something similar, then you might want to review the settings mentioned in https://docs.restructuredtext.net/articles/prerequisites

**Comment by EricThomson** [comment]
Sorry @lextm lextm I didn't even notice that was for Python extension, I was seeing this with restructured text preview. 

Note I installed the extension pack for rst, and upon restart was prompted to install a few things and it works now.
