### ISSUE TITLE
Issue with preview on VScode after updating .json files 

### ISSUE THREAD

**Issue by sistia01** [vscode-restructuredtext/vscode-restructuredtext#399]
I was given a warning on my VSCode that the restructured text extension that I was using was obsolete and that I should update to esbonio. I've done this but now my preview is no longer working (I cannot visually see the rst files that I have as I used to be able to). Is there a workaround for this?

GitHub repo: https://github.com/sistia01/Giotto-Sphinx-Website

**Comment by lextm** [comment]
After switching to Esbonio language server, the check on your reStructuredText files are stricter.

In your case, you should be able to see from Esbonio Language Server log channel on what's exactly wrong. Very likely that `sphinx_toolbox` and `sphinx_design` are not installed.
