### ISSUE TITLE
Error when trying to open the preview

### ISSUE THREAD

**Issue by masbicudo** [vscode-restructuredtext/vscode-restructuredtext#40]
Please provide the following information,

**Environment**
- [ ] Extension version: 0.0.21
- [ ] Visual Studio Code version: 1.9.1
- [ ] Operating System version: Windows 10
- [ ] Python version: 2.7.10
- [ ] sphinx version: 1.3.2
- [ ] A sample of conf.py or its important fragments: ???

**Expected behavior**

Should open something... a window to display the preview.

**Actual behavior**

An error:

![image](https://cloud.githubusercontent.com/assets/1653710/23064915/e868128e-f4f9-11e6-91cd-b52e4266fe6b.png)

**Detailed Steps to reproduce the problem**

Just click the preview button when inside a rst file.

![image](https://cloud.githubusercontent.com/assets/1653710/23065153/2df7ff5c-f4fb-11e6-992b-5120215a93ce.png)

**Comment by lextm** [comment]
Please open Integrated Terminal, and run `make html`. Then we can see what happens.

**Comment by masbicudo** [comment]
Where should I execute that? There is no make here.

**Comment by lextm** [comment]
Can you get started with this link?

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

And then move to your customized scenario? You have to understand what this extension expects before moving on.

**Comment by masbicudo** [comment]
Ok, I see... I thought it worked out of the box.
I followed the steps and now it's working.
Thanks!
