### ISSUE TITLE
[Bug]: tab not working in list editing

### ISSUE THREAD

**Issue by PierreMarchand20** [vscode-restructuredtext/vscode-restructuredtext#401]
### Expected behavior

As mentioned in #265, the list editing features come from this [markdown extension](https://github.com/yzhang-gh/vscode-markdown#list-editing). One of them is to use `tab` to create a nested list.

### Actual behavior

It does work in markdown, but in a `.rst` file, it triggers autocompletion:
![image](https://user-images.githubusercontent.com/15056323/184140329-0a3b4843-ce68-4bd9-9d2d-10b633728dd3.png)

### Detailed steps

Just create a list, from one item, type <enter> and then <tab>.

### Extension information

190.1.4

### Visual Studio Code information

1.70.1

### Operating system information

Darwin arm64 21.3.0

### Python information

3.9.13

### Sphinx information

4.4.0

**Comment by lextm** [comment]
Fixed in 189.1.0 stable release, but not in 190.x preview releases.

The workaround is to dismiss any VS Code notifications triggered by this extension, as they are blocking the tab key event handler from registering.

**Comment by tierriminator** [comment]
Unfortunately I'm still having issues with this on 189.3.0
