### ISSUE TITLE
Initial venv support

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#409]
Related to #354

While there are many virtual environment solutions out there for Python, Pipenv shows a good enough architecture and a clean way to integrate. However, venv is widely used and part of Python standard.

* Microsoft Python extension can identify its virtual environment.
* The existing code of this extension can identify installed/missing Python packages (esbonio/sphinx) without any change.

If a user follows the prompts to install missing dependencies, newly installed packages are at the right place.

But esbonio might report problems of all .rst files inside `venv` folder, which is very annoying.

**Comment by lextm** [comment]
The typical workflow is,

* pip install --user venv. This installs venv on the machine.
* Navigate to the existing project folder, and use `python -m venv venv` to initialize the environment and store files in `venv` folder.
* Open the project folder in VS Code and select the virtual environment in Microsoft Python extension.

Then this extension picks up all installed packages (esbonio and so on) from this virtual environment. If anything is missing, the user can follow the prompts to acquire the dependencies.

**Comment by goyalyashpal** [comment]
> * select the virtual environment in Microsoft Python extension.
>   > Use `View | Command Palette...` menu to locate `Python: Select Interpreter`.
> 
> Then this extension picks up all installed packages (esbonio and so on) from this virtual environment.

this is nice and all, but i wish there was an option to specify the python environment separately. as i am using reStructuredText based files as standalone documents.

**Comment by lextm** [comment]
@goyalyashpal This extension starts to require sphinx and is moving away from supporting standalone documents in prerelease versions. You might switch to other extensions if you like.

**Comment by goyalyashpal** [comment]
> moving away from supporting standalone documents in prerelease version

hollllly molly. anyhow, thanks for letting me know. glad i asked.

----------
just saying though, even if i were using a python project (as python also uses rst files for doc generation); i would never install these docutil packages in the projects environment.

so, giving separate option for python path may still make sense?

**Comment by lextm** [comment]
@goyalyashpal Not quite sure what's your personal preference, but what I am using for my projects is,

1. Use poetry to manage dependencies and virtual environment.
2. sphinx is added to dev dependencies. It is required by CI/CD to publish documentation site, and also enable you to verify locally if the documentation breaks sometimes.

An example is PySNMP, https://github.com/lextudio/pysnmp

**Comment by goyalyashpal** [comment]
> 1. Use poetry to manage dependencies and virtual environment 

but `esbonio`, `docutils` (& i guess sphinx too) etc are not "dependency" so to say, the code of a project aint `import`ing it. 

it's more like a "common tool" to aid in development which is how i installed it (with [`pipx`]) which says "Install and Run Python Applications in Isolated Environments"

[`pipx`]: https://pipx.pypa.io/ "Install and Run Python Applications in Isolated Environments"

**Comment by lextm** [comment]
> but `esbonio`, `docutils` (& i guess sphinx too) etc are not "dependency" so to say, the code of a project aint `import`ing it.

There are two kinds of dependencies if you didn't notice,

* Normal dependencies are the ones your package really depends on https://github.com/lextudio/pysnmp/blob/v5.0.37/pyproject.toml#L28. They are also visible on PyPI when someone consumes the package.
* Dev dependencies are the ones required during development (as you wished). They are not visible on PyPI, because package consumers won't need them, https://github.com/lextudio/pysnmp/blob/v5.0.37/pyproject.toml#L38

**Comment by inigohidalgo** [comment]
Hello @lextm I know this is an old issue but I got here through the docs.

I would also like to be able to specify a python interpreter for the extension to use: I am happy to install the dependencies required and to track them as dev dependencies in my `pyproject.toml` but I would like to avoid having to pollute my main dev virtual environment with doc dependencies, to keep my dependencies as closely-aligned with my production dependencies. The virtual environment I select in VSCode is the one I want to use for my codebase's language server and debugging sessions, but not necessarily for other extension-specific tasks.
