### ISSUE TITLE
[Bug]: esbonio Sphinx build error

### ISSUE THREAD

**Issue by abergmeier** [vscode-restructuredtext/vscode-restructuredtext#412]
### Expected behavior

I expected whatever is needed to get correctly set up by the VS extension or at least report a meaningful error in case of a problem.

### Actual behavior

But a bug happened that everytime it tries to build the text, I get the error message of the title.
There don't seem more details

### Detailed steps

The steps are,

### Extension information

189.2.0

### Visual Studio Code information

1.70.2

### Operating system information

Ubuntu 22.04

### Python information

3.10

### Sphinx information

4.3.2-1

**Comment by lextm** [comment]
Esbonio has its log entries on the actual build error,

https://docs.restructuredtext.net/articles/troubleshooting#find-the-logs

Check it out and you will see how to resolve the problem (most likely that you missed some Python packages).
