### ISSUE TITLE
Feedbacks for 190.1.5+

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#415]
Published 190.1.5 and above via VS Code Marketplace as preview builds.

Release notes can be found at https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/190.1.4.

Please post your comments below if you meet any issues.

**Comment by ExaneServerTeam** [comment]
Hello, can't test on my end as #406 issue is still around & have to run a Corporate Python3 installation.

**Comment by lextm** [comment]
Release 190.1.17 and above took a different turn, so this issue is no longer needed.
