### ISSUE TITLE
[Feature]: Adaptive nested list types

### ISSUE THREAD

**Issue by tierriminator** [vscode-restructuredtext/vscode-restructuredtext#418]
### Is your feature request related to a problem? Please describe.

When creating nested lists of different types (*, -, numbered), switching from a higher level to a lower one currently does not adapt the list type.
For example, if we write
```
- l1
  * l2
```
and put the cursor after "l2" and press `Enter`, a new `*` item appears. If we then press `Backspace`, the `*` item will be lowered by one level.

### Describe the solution you'd like

In the above example, I would like the `*` item to turn into a `-` item when pressing `Backspace`.
This would also be very useful when working with list tables.

**Comment by lextm** [comment]
Knowing which actual list is at the current cursor place requires complex state tracking that usually is part of a language server, so likely esbonio might be able to support it, but not this extension.
