### ISSUE TITLE
[Feature]: Support preview of multiple documents with Esbonio/Sphinx

### ISSUE THREAD

**Issue by lieser** [vscode-restructuredtext/vscode-restructuredtext#421]
### Is your feature request related to a problem? Please describe.

We have multiple Sphinx documents in the same repository. It would be good to be able to preview different rst files from different documents without having to manually change between the different `conf.py`.

### Describe the solution you'd like

An option to tell the extension to use the Esbonio/Sphinx with the "nearest" `conf.py` (i.e. look in the current folder for a `conf.py`, if found use, if not go one folder up, repeat until reaching the root).

### Describe alternatives you've considered

Allow to set the `esbonio.sphinx.confDir` on a per folder level.

**Comment by lextm** [comment]
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.
