### ISSUE TITLE
"Sphinx[undefined]" in status bar

### ISSUE THREAD

**Issue by Gliptal** [vscode-restructuredtext/vscode-restructuredtext#426]
Everything seems to be working fine with the extension, but I get `undefined` instead of `html` in the status bar.

![status bar](https://github.com/vscode-restructuredtext/vscode-restructuredtext/assets/3907646/d20e7247-e321-4f7e-9d08-bcfd3f66645b)

Looking in the code the `sphinxConfig` object is expecting a `builderName` property: where and how is this set by the user?

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/c6a6b46a5168492cd30d4244ed547cda0cf56275/src/language-server/client.ts#L337

**Comment by lextm** [comment]
The language server evolves faster than this extension, so not a surprise that minor things might break. An update is expected once something major occurs on the language server side.
