### ISSUE TITLE
[Bug]: The extension is incompatible with redhat.ansible

### ISSUE THREAD

**Issue by kunaltyagi** [vscode-restructuredtext/vscode-restructuredtext#427]
### Expected behavior

No conflict between extension

### Actual behavior

VS Code wants me to uninstall either one of these 2

### Detailed steps

* Install redhat.ansible and lextudio.restructuredtext in any order
* Edit a YAML file

### Extension information

v189.3.0

### Visual Studio Code information

1.82.0 (insider)

### Operating system information

Fedora 36 (Linux)

### Python information

3.10.6

### Sphinx information

unknown

### Contents of conf.py

```python
NA
```

### Relevant log output

```shell
NA
```

**Comment by lextm** [comment]
Thanks for the report, but no plan to further investigate this.

Pull requests are welcome if the root cause can be found.

**Comment by koeppe-at-pdtec** [comment]
Here is the reason:
https://github.com/ansible/vscode-ansible/pull/366
So this is the root cause.
