### ISSUE TITLE
Unable to open 'Preview 'filename.rst'':Cannot read property 'document' of undefined.

### ISSUE THREAD

**Issue by vairamsvsjdo** [vscode-restructuredtext/vscode-restructuredtext#43]
Please provide the following information,

**Environment**
- [x ] Extension version:0.0.22
- [ x] Visual Studio Code version:1.1.2
- [ x] Operating System version:windows 7
- [ x] Python version:3.6
- [x ] sphinx version:
- [x ] A sample of conf.py or its important fragments:

**Expected behavior**
show preview for an reStructuredText page
**Actual behavior**
Unable to open 'Preview 'filename.rst'':Cannot read property 'document' of undefined.
**Detailed Steps to reproduce the problem**
python 3.6
pip sphinx, 
pip sphinx-autobold 
install vscode 1.1.2
install extension
reopen code .
ctr+shift+r

**Comment by lextm** [comment]
The troubleshooting guide is there,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide

**Comment by lextm** [comment]
VSCode recently changed its extension API so some object this extension relies on becomes `undefined` unexpectedly. 

Changed some code as workaround.
