### ISSUE TITLE
[Bug]: ValueError: Position.character should be in range [0:2147483647], but was -1

### ISSUE THREAD

**Issue by oglops** [vscode-restructuredtext/vscode-restructuredtext#431]
### Expected behavior

I expected preview to work and esbonio server start

### Actual behavior

can not preview and esbonio server never starts

### Detailed steps

The steps are,

### Extension information

190.1.16

### Visual Studio Code information

1.83.1

### Operating system information

CentOS 7.9

### Python information

3.9.7

### Sphinx information

7.2.6

### Relevant log output

```shell
Failed to handle request 1 textDocument/documentSymbol DocumentSymbolParams(text_document=TextDocumentIdentifier(uri='file:///path/to/repo/source/test.rst'), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/path/to/my-env/lib/python3.9/site-packages/pygls/protocol.py", line 400, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/path/to/my-env/lib/python3.9/site-packages/pygls/protocol.py", line 322, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/path/to/my-env/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 350, in on_document_symbol
    doctree.walkabout(visitor)
  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 191, in walkabout
    visitor.dispatch_visit(self)
  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 2033, in dispatch_visit
    return method(node)
  File "/path/to/my-env/lib/python3.9/site-packages/esbonio/lsp/symbols.py", line 81, in visit_title
    symbol.range.end.character = len(name) - 1
  File "/path/to/my-env/lib/python3.9/site-packages/attr/_make.py", line 1068, in __setattr__
    nval = hook(self, a, val)
  File "/path/to/my-env/lib/python3.9/site-packages/attr/setters.py", line 23, in wrapped_pipe
    rv = setter(instance, attrib, rv)
  File "/path/to/my-env/lib/python3.9/site-packages/attr/setters.py", line 52, in validate
    v(instance, attrib, new_value)
  File "/path/to/my-env/lib/python3.9/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
[Error - 11:41:37 PM] Request textDocument/documentSymbol failed.
  Message: ValueError: Position.character should be in range [0:2147483647], but was -1.
  Code: -32603 
{'traceback': ['  File "/path/to/my-env/lib/python3.9/site-packages/pygls/protocol.py", line 400, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/pygls/protocol.py", line 322, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/path/to/my-env/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 350, in on_document_symbol\n    doctree.walkabout(visitor)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout\n    if child.walkabout(visitor):\n', '  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout\n    if child.walkabout(visitor):\n', '  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout\n    if child.walkabout(visitor):\n', '  [Previous line repeated 1 more time]\n', '  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 191, in walkabout\n    visitor.dispatch_visit(self)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/docutils/nodes.py", line 2033, in dispatch_visit\n    return method(node)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/esbonio/lsp/symbols.py", line 81, in visit_title\n    symbol.range.end.character = len(name) - 1\n', '  File "/path/to/my-env/lib/python3.9/site-packages/attr/_make.py", line 1068, in __setattr__\n    nval = hook(self, a, val)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/attr/setters.py", line 23, in wrapped_pipe\n    rv = setter(instance, attrib, rv)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/attr/setters.py", line 52, in validate\n    v(instance, attrib, new_value)\n', '  File "/path/to/my-env/lib/python3.9/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator\n    raise ValueError(\n']}
[Log - 11:42:41 PM] ConfigurationChangeEvent
Ignoring notification for unknown method "$/setTraceNotification"
Cancel notification for unknown message id "6"
```
my virtual env

```shell
> pip freeze
alabaster==0.7.13
annotated-types==0.6.0
attrs==23.1.0
Babel==2.13.0
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.1
click==8.1.7
colorama==0.4.6
doc8==0.11.2
docutils==0.18.1
esbonio==0.16.2
exceptiongroup==1.1.3
idna==3.4
imagesize==1.4.1
importlib-metadata==6.8.0
Jinja2==3.1.2
linkify-it-py==2.0.2
lsprotocol==2023.0.0b1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdit-py-plugins==0.4.0
mdurl==0.1.2
myst-parser==2.0.0
packaging==23.2
pbr==5.11.1
platformdirs==3.11.0
pydantic==2.4.2
pydantic_core==2.10.1
pygls==1.1.1
Pygments==2.16.1
pyspellchecker==0.7.2
PyYAML==6.0.1
requests==2.31.0
restructuredtext-lint==1.4.0
rich==13.6.0
rstcheck==6.2.0
rstcheck-core==1.1.1
shellingham==1.5.4
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinx-epytext==0.0.4
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-mermaid==0.9.2
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sphinxcontrib-video==0.2.0
stevedore==5.1.0
tomli==2.0.1
typeguard==3.0.2
typer==0.9.0
typing_extensions==4.8.0
uc-micro-py==1.0.2
urllib3==1.26.18
zipp==3.17.0
```

**Comment by lextm** [comment]
@alcarney This seems to be a bug in esbonio,

https://github.com/swyddfa/esbonio/blob/8381ac41278b3c7b8630a059afa33f4bb6dff5e0/lib/esbonio/esbonio/lsp/symbols.py#L81

where you assume `name` can never be an empty string.

**Comment by alcarney** [comment]
@lextm ah, good spot thanks.

@oglops do you know what might be in your `file:///path/to/repo/source/test.rst` file that might trigger this? I'm looking for something that would result in an empty `title` node in the doctree.... I've tried a few ways to write an empty section header with no luck so far :/

While the fix itself is fairly straightforward, I'd like to make sure I can write a test case to make sure it stays fixed :)

**Comment by oglops** [comment]
Thanks for the reply! That rst file is long, but I can gradually delete stuff to find the culprit.  One thing I did not mention in original issue was it is hard to test, as I always get esbonio not installed warning when I open vscode, and I have to click the install button at lower right corner, then server will start ( I have to do this every time when vscode launches, if I do it too slow, when it says esbonia start failed, clicking the lower right corner to restart it won't work, I have to relaunch vscode)

**Comment by lextm** [comment]
@oglops There are several red flags in your description so hope you can address them first and try again.

1. If you use any virtual environment options, the steps mentioned in https://docs.restructuredtext.net/articles/prerequisites#virtual-environments must be followed. Aka, any dependencies including esbonio must be preconfigured and you cannot use the popup to install esbonio. That's why this extension cannot find esbonio.
2. `python.defaultInterpreterPath` shouldn't even be there, as this extension relies on Microsoft Python extension to detect which interpreter to use when inside a virtual environment.

**Comment by oglops** [comment]
> 1. you cannot use the popup to install esbonio.

I never intended to `use the popup to install esbonio`, I am pretty sure I manually installed esbonio already in my env, and yet the prompt keeps poping up, I had to click on install button then server would start, if I do not click on it, server hangs at starting phase forever, and a few seconds later says, can't start server, and restart does not help ( I have described this scenario in last comment)

> 2. `python.defaultInterpreterPath` shouldn't even be there
 
I could remove it, but iirc, the only reason I explicitly set it to be the very interpreter in my virtualenv is becasuse as you said. 
` this extension relies on Microsoft Python extension to detect which interpreter to use`, it did not work, that's why I explicitly set it.

**Comment by lextm** [comment]
> it did not work, that's why I explicitly set it.

I think that's the very top priority here, that how to get Microsoft Python extension works for your virtual environment setup. However, that extension is not in scope of this repo, and I won't be able to guide you further.

**Comment by oglops** [comment]
> Microsoft Python extension works for your virtual environment setup

Microsoft Python extension works perfectly well for my virtual environment setup,   when I say `it did not work` I mean the `restructuredText` extension does not work, so I suspect I need to set it.  In my last reply I described the latest experiment I did, removing the `python.defaultInterpreterPath` from workspace setting, but still `restructuredText` extension does not work as expected.

**Comment by lextm** [comment]
So if you delete `python.defaultInterpreterPath` and restart VS Code, what happens? When you claim this extension does not work, what's being recorded in the log? I am afraid I cannot comment further without knowing more. This extension has 536k active users/installs, so I don't believe many experience this issue (or they simply uninstall it).
