### ISSUE TITLE
[Bug]: Esbonio Server not starting

### ISSUE THREAD

**Issue by shadowfax65** [vscode-restructuredtext/vscode-restructuredtext#434]
### Expected behavior

Preview of the .rst file

### Actual behavior

Fresh install of VSC (1.82.2) on Linux Mint 21.2, followed the resStructuredText extension (189.3) installation to the t but no preview possible. Error message is "Esbonio language server is not installed or out of date. Source: reStructuredText (Extension)". Clicking on the "Install" button does nothing. I have tried ``pip install --force-reinstall esbonio`` and the same for ``attrs`` but to no avail.
The Output for Esbonio Language Server shows this:
[Log - 14:52:24] Server start command: /bin/python -m esbonio
[Log - 14:52:24] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"}],"initializationOptions":{"sphinx":{"srcDir":"/home/bernd/docs-kdenlive-org/docs-kdenlive-org","confDir":"${workspaceFolder}","forceFullBuild":true,"numJobs":1,"buildDir":"/home/bernd/docs-kdenlive-org/docs-kdenlive-org/_build/html"},"server":{"logLevel":"error","logFilter":[],"hideSphinxOutput":true,"enableScrollSync":true}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 14:52:24] Starting Language Server
/bin/python: No module named esbonio
[Info  - 14:52:25] Connection to server got closed. Server will restart.
/bin/python: No module named esbonio
[Info  - 14:52:25] Connection to server got closed. Server will restart.
/bin/python: No module named esbonio
[Info  - 14:52:25] Connection to server got closed. Server will restart.
/bin/python: No module named esbonio
[Info  - 14:52:25] Connection to server got closed. Server will restart.
/bin/python: No module named esbonio
[Error - 14:52:25] Connection to server got closed. Server will not be restarted.

Output for reStructuredText:
[Log - 14:51:55] Successful exec
[Log - 14:52:05] Started to install Esbonio...
[Log - 14:52:05] Running cmd: "/bin/python" -m pip install esbonio --upgrade
[Log - 14:52:24] Successful exec
[Log - 14:52:24] Finished installing esbonio

### Detailed steps

Regardless of what .rst file I open, the preview is not possible because of the Esbonio Server not being available

### Extension information

189.3

### Visual Studio Code information

1.82.2

### Operating system information

Linux Mint 21.2 fresh install

### Python information

3.10

### Sphinx information

7.2.6

**Comment by lextm** [comment]
In general this extension isn't able to teach users on how to configure Python.

When you use `/bin/python`, there are drawbacks to accept (such as `pip install` won't work by default without `sudo` or `--user`).

You might consider using virtual environments, but that also has its own pains,

https://docs.restructuredtext.net/articles/prerequisites#virtual-environments

**Comment by shadowfax65** [comment]
Thanks @lextm for your reply. I did try to install esbonio with ``sudo pip install esbonio`` but same result. The funny thing is that from withing VSC I can click on `Install` when the error message comes up that esbonio is not installed or out of date. It then launches the command:
```
[Log - 11:50:28] Running cmd: "/bin/python" -m pip install esbonio --upgrade
[Log - 11:50:36] Successful exec
[Log - 11:50:36] Finished installing esbonio
```
But still esbonio does not start.

So, what am I doing wrong? What am I missing?

Yes, I admit I do not know 

> how to configure python

 but don't think I should have to when installing an extension through VSC following the given instructions. Perhaps you can enlighten me as you seem to have plenty of experience and knowledge. Thank you very much for your patience ...

**Comment by lextm** [comment]
It might be too complicated for Python beginners to figure out what's wrong, but if you only use `/bin/python`, you can try the following

```bash
sudo /bin/python -m pip install esbonio
/bin/python -m pip list | grep esbonio
```
If this prints out the esbonio version you installed, then this extension should work.

**Comment by shadowfax65** [comment]
Thanks @lextm for your reply. I did try to install esbonio with ``sudo pip install esbonio`` but same result. The funny thing is that from withing VSC I can click on `Install` when the error message comes up that esbonio is not installed or out of date. It then launches the command:
```
[Log - 11:50:28] Running cmd: "/bin/python" -m pip install esbonio --upgrade
[Log - 11:50:36] Successful exec
[Log - 11:50:36] Finished installing esbonio
```
But still esbonio does not start.

So, what am I doing wrong? What am I missing?

Yes, I admit I do not know 

> how to configure python

 but don't think I should have to when installing an extension through VSC following the given instructions. Perhaps you can enlighten me as you seem to have plenty of experience and knowledge. Thank you very much for your patience ...

**Comment by lextm** [comment]
Please don't post the same thing multiple times.

**Comment by shadowfax65** [comment]
> If this prints out the esbonio version you installed, then this extension should work.

I followed your suggestion and the `install` comes back with a whole list of `Requirement already satisfied` messages for several modules (?). The `grep` command results in `esbonio                       0.16.2`

So as far as I can see the correct version of esbonio is installed, `\bin\python` and `\bin\python3` work but the extension still does not ...

**Comment by shadowfax65** [comment]
> The output of `/bin/python -m pip list | grep esbonio` should tell more about what might be wrong.

This is the output: `esbonio                       0.16.2`

I hope this doesn't count as posting something multiple times ;-)

**Comment by lextm** [comment]
You'd better find someone locally who is familiar with Python to help  further in this case, or debug into the source code yourself, https://docs.restructuredtext.net/articles/development
