### ISSUE TITLE
[Bug]: Automatic table formatting does not work for unicode strings

### ISSUE THREAD

**Issue by pavelbrych** [vscode-restructuredtext/vscode-restructuredtext#435]
### Expected behavior

When table cells contains non-ascii characters, expected output for simple table is:

```
+-----+---+
| č  | č  |
+-----+---+
```

### Actual behavior

But currently, when table cells contains non-ascii characters, text-length is calculated incorrectly, resulting in shifted table:

```
+-----+-----+
| č  | č  |
+-----+-----+
```

I checked the code: There is countTextWidth() method in /editor/util.js. This method counts every non-ascii character as two for some reason.

When modified to return simple text.length, table is formatted correctly.

### Detailed steps

Try to auto-format rst table with non-ascii character, for example "č".

### Extension information

v189.3.0

### Visual Studio Code information

1.85.0

### Operating system information

Linux

### Python information

3.11

### Sphinx information

7.2.6

**Comment by lextm** [comment]
While this is a valid bug report, the pull request didn't resolve the issue for all typical scenarios.

More investigation is needed.

**Comment by pavelbrych** [comment]
Thank you for explanation, some links for future reference from quick google search:

CJK width in unicode:
https://unicode.org/reports/tr11/

Simple hack that visual studio code use to deal with it - method isFullWidthCharacter():
https://github.com/microsoft/vscode/blob/4500bff058ad93a1901521e7a345b9abe24ca2a4/src/vs/base/common/strings.ts#L669
