### ISSUE TITLE
[Bug]: No module named rstcheck.__main__

### ISSUE THREAD

**Issue by tempookian** [vscode-restructuredtext/vscode-restructuredtext#441]
### Expected behavior

I expect that `rstcheck` detects issues in my rst file. Please note that no bug is reported in OUTPUT. I also manually ran the command and got the same error

```bash
python3 -m rstcheck testfile.rst
```

### Actual behavior

But a bug happened like this,

> No module named rstcheck.__main__; 'rstcheck' is a package and cannot be directly executed

### Detailed steps

rstcheck 6.2.0
rstcheck-core 1.2.0

The problem is resolved if the entry point is defined for `rstcheck`. Check this [pull request](https://github.com/rstcheck/rstcheck/pull/206) to see what I mean. 

### Extension information

190.1.18

### Visual Studio Code information

1.85.2

### Operating system information

Linux/Ubuntu

### Python information

3.11.4

### Sphinx information

7.2.6

**Comment by lextm** [comment]
Thanks for the report. There is a pull request being reviewed.

**Comment by tempookian** [comment]
Ah, OK. Sorry I just saw your comment. I realized that  the problem could be solved with the following, and created a pull request. Feel free to ignore it :smile: 

```bash
python -m rstcheck._cli
```

**Comment by lextm** [comment]
Slightly improved your pull request and shipped 190.1.19 prerelease build.
