### ISSUE TITLE
[Bug]: Reference related warnings don't disappear until file is saved

### ISSUE THREAD

**Issue by Mrcubix** [vscode-restructuredtext/vscode-restructuredtext#444]
### Expected behavior

After referencing a page in a toctree, i expected the warning `document isn't included in any toctree` to disappear in the referenced file.
When i create the file 'page' in 'some/page', i expect the `toctree contains reference to nonexisting document 'some/page` to disappear.

These are only two example of many, those warnings does disappear when the file is saved, but it shouldn't be required.

### Actual behavior

Any reference related warnings persist until the referenced or the referent page file is saved.

### Detailed steps

1. Create a toctree,
2. Start referencing a file that doesn't exist yet & save
3. Create this file, write its identifier as well as its top level header & save.
4. Warning  `toctree contains reference to nonexisting document 'some/page` persist in toctree,
5. Remove reference from toctree & save,
6. Warning `document isn't included in any toctree` appear & persist until saved.

### Extension information

189.3.0

### Visual Studio Code information

1.87.2

### Operating system information

Windows

### Python information

3.10.4 (msys)

**Comment by lextm** [comment]
1. We in general no longer support 189.x.x releases. You are welcome to upgrade to the prerelease.
2. You didn't describe clearly what gave you that message, the linter or the language server. Linters are controlled by [this setting](https://docs.lextudio.com/restructuredtext/articles/configuration#lint-ontype-or-onsave-or-not-at-all), which you can reveal what value you configured. If the message was from the language server, however, the configuration will be different.

**Comment by Mrcubix** [comment]
1. It's weird that you wouldn't offer support for the latest stable release, and instead only offer support for a pre-release (that is broken on 4 different machines, including a clean VM (but that's for another issue)).

2. The doc does imply that it is onType by default & the vscode settings are set to that, but it is srill not updating until i save

**Comment by lextm** [comment]
190.x.x has been out for quite a while, which we have been using ourself and consider stable. We mark them as prerelease, simply because esbonio isn't ready to fully take over the responsibilities like live preview and others.

Thus, we will do nothing on 189.x.x.
