### ISSUE TITLE
[Feature]: Make clickable paths to .uml files (for the uml directive)

### ISSUE THREAD

**Issue by annetre** [vscode-restructuredtext/vscode-restructuredtext#446]
### Is your feature request related to a problem? Please describe.

The extension works fine and makes clickable paths and open files with their paths for common directives (figure, image,literalinclude and so on) with Ctrl + Click.

![image](https://github.com/vscode-restructuredtext/vscode-restructuredtext/assets/112639217/fad1646a-0e1e-4090-8095-d19008a83688)

Please, introduce the same behavior for the uml directive.

![image](https://github.com/vscode-restructuredtext/vscode-restructuredtext/assets/112639217/59c41ebf-2b6c-4888-a4c3-12ad87f89d3d)

### Describe the solution you'd like

Described above

**Comment by lextm** [comment]
Thanks for leaving your feedback. This is a language server feature so should be reported to the esbonio repo instead.
