### ISSUE TITLE
[Bug]: Hitting enter or backspace result in command not found

### ISSUE THREAD

**Issue by pluyckx** [vscode-restructuredtext/vscode-restructuredtext#448]
### Expected behavior

When hitting enter, the editor goes to a new line and continues in the context you were working in. For example, if you are writing a list, it automatically starts the next line with the list symbol you were using.

When hitting backspace, the character left or the cursor should get removed.

### Actual behavior

I get the error:
```
command 'restructuredtext.editor.listEditing.onEnterKey' not found
```

### Detailed steps

1. Install the latest version of the extension.
2. Start a new file with the extension `rst`.
3. Try to hit `enter`, you do not need to write anything else.
4. The error 'command not found' is shown at the bottom right as a notification.

Installing v189.3.0 solves the issue.

### Extension information

190.3.0

### Visual Studio Code information

1.90.0

### Operating system information

Windows 10

### Python information

3.12.0

**Comment by lextm** [comment]
Interesting that with your steps, the extension is initialized differently in VS Code with Microsoft Python extension, so the `activate` method doesn't finish completely.

Release 190.4.0 tries to defer the problematic code in `activate` which might help remediate such issues. But more investigation is needed to see what exactly are the differences when VS Code calls `activate` with a single file.

**Comment by lextm** [comment]
Related to #445
