### ISSUE TITLE
[Bug]: rst preview not working at all

### ISSUE THREAD

**Issue by MartinCupak** [vscode-restructuredtext/vscode-restructuredtext#450]
### Expected behavior

In MS VS code, I expect functionality as per the animated gif on reStructuredText main page.

### Actual behavior

no preview displayed.

### Detailed steps

Just open the .rst file and click on icon to "Open preview to the side", that does nothing.
When I click on "Preview HTML" icon, I get the error 

Error
The html file corresponding to the .rst document could not be found.
Save the file and try to run the build.

Not found...
/home/martin/src/CIC/ADACS2/IMOS/NDRI-IMOS/html/doc/Documentation.html

### Extension information

v190.4.1

### Visual Studio Code information

Version: 1.92.0 Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124 Date: 2024-07-31T23:26:45.634Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Linux x64 5.15.0-117-generic

### Operating system information

Linux Ubuntu 20.04LTS

### Python information

3.9.19

### Relevant log output

```shell
For side preview, I get nothing pronted in the terminal window.

For the HTML preview I get theis - but not sure it is relevant

 *  Executing task: "./make html" 

/usr/bin/bash: ./make html: No such file or directory

 *  The terminal process "/usr/bin/bash '-c', '"./make html"'" failed to launch (exit code: 127).
```

**Comment by lextm** [comment]
Issues about esbonio should be posted to https://github.com/swyddfa/esbonio/issues

**Comment by MartinCupak** [comment]
Additional info:
After installing reStructureText extension (plus the two dependecies, Esbonio and reStructureText syntax higlighting) it is no longer possible to edit .rst files.
I get these errors:
command 'restructuredtext.editor.listEditing.onEnterKey' not found
command 'restructuredtext.editor.listEditing.onBackspaceKey' not found

I did not have this problem before.

When I disable reStructureText and Esbonio and reStructureText syntax higlighting, I can edit the .rst file again.

**Comment by MartinCupak** [comment]
> Issues about esbonio should be posted to https://github.com/swyddfa/esbonio/issues

Not sure this is esbonio issue. esbonio is a required dependency installed with reStructureText, as per instructions here:
https://docs.lextudio.com/restructuredtext/
