### ISSUE TITLE
[Bug] Backspace and Enter key do not work

### ISSUE THREAD

**Issue by Zufallszahl** [vscode-restructuredtext/vscode-restructuredtext#451]
### Expected behavior

I expect pressing Backspace to delete characters, and pressing Enter to create a new line.

### Actual behavior

Pressing Backspace returns "command 'restructuredtext.editor.listEditing.onBackspaceKey' not found". No characters are deleted.
Pressing Enter returns "command 'restructuredtext.editor.listEditing.onEnterKey' not found". No new lines are created.
![image](https://github.com/user-attachments/assets/95d8e0d6-6b58-4778-9b02-dbb04d1a9846)

### Detailed steps

1. Enable the extension. 
2. Create an .rst file.
3. Try to press Enter or Backspace.

I've tried disabling and reenabling the extension, reloading the window and restarting VSC as per #445, but it didn't help. 

I have (briefly) managed to resolve the issue by disabling the reStructuredText Syntax higlighting extension, but after another restart the issue came back again even with that extension disabled. 

### Extension information

190.4.4

### Visual Studio Code information

1.95.3

### Operating system information

Windows 10

### Python information

3.13.0

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by Zufallszahl** [comment]
After looking into the logs, I noticed that the extension failed to automatically activate upon creating or opening an .rst file. Using an extension-specific shortcut (specifically, `Ctrl + K Ctrl + =`,  `Ctrl + K Ctrl + -`, `Alt + L` or `Shift + Alt + L`) successfuly forced it to activate.

**Comment by lextm** [comment]
Release 190.4.5 starts to activate when VS Code switches to reStructureText language, so it should have fixed this issue.

We appreciate your thorough investigation and the comprehensive information provided.
