### ISSUE TITLE
Error without details - is there a log?

### ISSUE THREAD

**Issue by cknaap** [vscode-restructuredtext/vscode-restructuredtext#47]
Hi, 

Thanks for providing this VSCode extension. I am encountering an error and actually I would like to investigate what could be wrong before submitting an issue to you. But I don't see how to get more details about the error. Is there any way to get to that info?

Currently don't have the time to create a minimal project to reproduce the error. I encountered it in https://github.com/simplifhir/simplifier-docs.git.

Regards, Christiaan

Please provide the following information,

**Environment**
- [v26.0.0 ] Extension version:
- [1.12.2 ] Visual Studio Code version:
- [Windows 10 64 bit (winver.exe: version 1607)] Operating System version:
- [2.7.13 ] Python version:
- [1.5.5 ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

extensions = [
    'sphinx.ext.intersphinx',
]
intersphinx_mapping = {'https://docs.python.org/': None}

**Expected behavior**
An error occurs, and I am directed to a log or other means of determining the actual problem.

**Actual behavior**
An error occurs, and vscode just shows: Unable to open 'Preview 'index.rst'': Error

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
You simply missed `makefile` and `make.bat`. You can see example repos like this,

https://github.com/lextm/obfuscar_docs

**Comment by ffes** [comment]
I run into a similar situation. Unfortunately there is nothing in the `Output` panel. When this is used by the extension, it would make debugging the problems when building a preview much easier.

**Comment by davidfraser** [comment]
I have a similar situation; I have been adding `Makefile`, `conf.py`, etc and ensuring that the specified `sphinx-build` correctly builds my file; I have even hacked sphinx-build so that it logs its output to a file, and I can see that the extension is running it successfully, but it gives a *Unable to open Preview* error message as above.

Some log messages would be exceedingly helpful.

**Comment by lextm** [comment]
There is already some work in progress. Not yet ready to be published though.

**Comment by lextm** [comment]
Fixed in 460f9f37cdf048e4c30d2705ff9b89ebd03f535b

Starting from release 31.0 three lines are written to the reStructuredText tab under OUTPUT panel for each preview operation. You can review the `Compiler` line and `HTML file` line to see if anything is not right.
