### ISSUE TITLE
SPHINXBUILD, sphinxBuildPath and python.pythonPath does not work with Makefile

### ISSUE THREAD

**Issue by olt** [vscode-restructuredtext/vscode-restructuredtext#48]
SPHINXBUILD, sphinxBuildPath and python.pythonPath does not work with Makefile.

**Environment**
- [ ] Extension version: 26.0.0
- [ ] Visual Studio Code version: 1.12.2
- [ ] Operating System version: 10.10.5
- [ ] Python version: 2.7.9
- [ ] sphinx version: 1.6.1

**Expected behavior**

`make html` called from this extension should find `sphinx-build` when `SPHINXBUILD`, `sphinxBuildPath` or `python.pythonPath` is set.

**Actual behavior**

`Error: Unable to open 'Preview 'file.rst''`

**Detailed Steps to reproduce the problem**

The sphinx-build binary is passed as an environment variable to the `make html` call [1]. This is only supported for the Windows `make.bat`. For the `Makefile` it needs to be passed as an additional argument:

    make html SPHINXBUILD=/path/to/sphinx-build

[1] https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/c6db222a5fb7c8700141e3058364184be0df4746/src/extension.ts#L220...L239

**Comment by lextm** [comment]
Can you now test with release 27.0? Since makefile is no longer used, I think now environment variables are not needed either.
