### ISSUE TITLE
sphinx separate source and build

### ISSUE THREAD

**Issue by pasquinadeus** [vscode-restructuredtext/vscode-restructuredtext#49]
When editing a sphinx project, created using the quickstart option to separate source and build:

> You have two options for placing the build directory for Sphinx output.
> Either, you use a directory "_build" within the root path, or you separate
> "source" and "build" directories within the root path.
 > Separate source and build directories (y/n) [n]: y

the documentation tree ends up as:

ROOT/make.bat
ROOT/Makefile
ROOT/source/*
ROOT/build/html/*

then I add the following code configuration file for code in ROOT/.vscode/settings.json:
```
{
    "restructuredtext.builtDocumentationPath" : "build/html",
    "restructuredtext.makefilePath"           : ".",
    "restructuredtext.updateOnTextChanged"    : "false",
    "restructuredtext.sphinxBuildPath"        : null
}
```

I then start code in the ROOT directory, but when I try to preview one of the FILE.rst files inside "source" it fails with the dreaded "Error" seen in other posts. 

Using the Console output I see that the extension is trying to open:
'ROOT/build/html/source/FILE.html'
where the extra "source" in the pathname is incorrect (the build ends up in ROOT/build/html/FILE.html).

I do not see how to correct this in the settings.json file with the 4 configuration options available. As a workaround I added a "source" link to "." inside the ROOT/build/html folder and the preview immediately started working. 

Thanks for the great plugin, hope this might help someone...

**Environment**
- [ ] Extension version: 26.0.0
- [ ] Visual Studio Code version: 1.11.2
- [ ] Operating System version: Linux debian stretch
- [ ] Python version: 2.7.13
- [ ] sphinx version: 1.4.9
- [ ] A sample of conf.py or its important fragments: NOT RELEVANT (I think)

**Comment by lextm** [comment]
Thanks for sharing the workaround.

The long term plan is to get rid of makefile and make.bat in the extension so that this extension itself handles the call to `conf.py`.

**Comment by lextm** [comment]
Can you now test release 27.0? By setting `confPath` to `"source"` you should be able to get the result you want.

**Comment by pasquinadeus** [comment]
Hi lextm, 

I changed the .vscode/settings.json to the following:

```
{
    "restructuredtext.builtDocumentationPath" : "build/html",
    "restructuredtext.makefilePath"           : ".",
    "restructuredtext.updateOnTextChanged"    : "true",
    "restructuredtext.sphinxBuildPath"        : null,
    "restructuredtext.confPath"                 : "source"
}
```

But now the error is quite different. It seems to not handle spaces in the path up to the build folder (which now seems to be in the correct path):

> extensionHost.ts:284[Extension Host] Error
> Command failed: python -msphinx -b html . /home/ricardo/work/PATH1/DOCUMENTS/PATH2 - PATH3/build/html
> Error: Cannot find file '-'.
> Error: Cannot find file 'PATH3/build/html'.


sorry, I had to edit the path due to client privacy issues, (I replaced with "PATHx' above), but it seems to not like the space around the hyphen. 

Hope it helps,
Ricardo

**Comment by lextm** [comment]
Thanks. I think quoting the output path might help.

Can you now test release 28.0.

**Comment by pasquinadeus** [comment]
28.0 seems to be flawless. Thanks for the effort!

Best,
Ricardo
