### ISSUE TITLE
url highlight error with Chinese Character

### ISSUE THREAD

**Issue by qin-nz** [vscode-restructuredtext/vscode-restructuredtext#5]
\`你好 \<http://hello.example.com>`_

the word after this url will be highlight as the url and end with another url.

**Comment by lextm** [comment]
It is a bug of the imported syntax highlighting file, which I don't plan to fix.

I am now trying to build a language parser/server, and then move the syntax highlighting to be upon that. Ultimately it should solve this problem and many others.

Thanks for reporting.

**Comment by lextm** [comment]
It has been proven to be a bug in VSCode and fixed in recent releases. No work on my side.
