### ISSUE TITLE
Help me with configure restruturedtext preview for docs folder

### ISSUE THREAD

**Issue by rajasimon** [vscode-restructuredtext/vscode-restructuredtext#50]
If I have the project folder like below then the preview not working...

```
.vscode
|__ settings.json
|__ docs/
    |__ config.py
```

**Environment**
- [x] Extension version: 29.0.0
- [x] Visual Studio Code version: 1.13.0
- [x] Operating System version: Ubuntu 16
- [x] Python version: 2.7.12
- [x] sphinx version: 1.3.6
- [x] A sample of conf.py or its important fragments:

```
// Place your settings in this file to overwrite default and user settings.
{
    "restructuredtext.builtDocumentationPath" : "docs/_build/html",
    "restructuredtext.confPath"               : "docs",
    "restructuredtext.updateOnTextChanged"    : "true", 
    "restructuredtext.sphinxBuildPath"        : "sphinx-build"
}
```

**Expected behavior**
Ctrl + Shift + r to open preview window

**Actual behavior**
>Unable to open 'Preview 'index.rst'': Error

**Detailed Steps to reproduce the problem**
Follow [Sample Project](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#sample-project) and make sure the preview work. Then move all the files and folder to `docs/` then create a .vscode/settings.json with above configuration. 

Am I missing something? It should show the preview. Please help.

**Comment by lextm** [comment]
You only need below in `settings.json`
```
{
    "restructuredtext.confPath": "docs"
}
```
However, due to a bug you have to close the folder in VSCode and then reopen it so as to trigger a configuration update.

**Comment by rajasimon** [comment]
Okay. That's working. But my `virtualenv` inside my project folder and `pythonVSCode` needs `python.pythonPath` for better understanding. When I put the pythonPath again it's throwing error. Do you know why? And also I have the sphinx package installed in `virtualenv` so shall I point that virtualenv `sphinx-build`

**Comment by lextm** [comment]
Just published release 30.0.0 to fix that. Please try it out.

**Comment by rajasimon** [comment]
Okay I tried with this settings but no luck

```
// Place your settings in this file to overwrite the default settings
{
    "python.pythonPath": "${workspaceRoot}/env/bin/python",
    "restructuredtext.confPath": "docs",
    "restructuredtext.sphinxBuildPath": "${workspaceRoot}/env/bin/sphinx-build"
}
```

**Comment by lextm** [comment]
Does the Python extension accept "$(workspaceRoot)"?

This extension requires absolute paths for `python.pythonPath` and `restructuredtext.sphinxBuildPath`, and the paths cannot contain such.

**Comment by rajasimon** [comment]
Yes [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode) accepts `"$(workspaceRoot)"`.  I was configured this using `ctrl + shift + p` and `Python: Select workspace interpreter option`. 

Anyway I hard coded pythonPath to use absolute path like `/home/simon/env/python` and now it's working. 

Can you change this extension to use `$(workspaceRoot)` python path. Then we will close this issue?

**Comment by lextm** [comment]
Definitely I can. Let me work on it in the next few days.

**Comment by lextm** [comment]
You can now upgrade to 32.0.0 release, which supports the `${workspaceRoot}` macro. However, this release requires all path settings to be set using absolute paths. Thus, your `settings.json` should look like,
```
// Place your settings in this file to overwrite the default settings
{
    "python.pythonPath": "${workspaceRoot}/env/bin/python",
    "restructuredtext.confPath": "${workspaceRoot}/docs",
    "restructuredtext.sphinxBuildPath": "${workspaceRoot}/env/bin/sphinx-build"
}
```

**Comment by rajasimon** [comment]
That's quick response. Let me check and get back to you.

**Comment by rajasimon** [comment]
Thanks. It's working now.
