### ISSUE TITLE
Does not work well with VSCode 1.14.0 Insider

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#52]
This insider build introduced “Multi-Root Workspaces”, which breaks this extension. 

When a preview is required for source files in a newly added folder, VSCode API still returns the previous folder root. This leads to errors.

**Comment by jsmedmar** [comment]
Oh, this was last updated in 2017. No plans to update multi-root?

**Comment by lextm** [comment]
Once #92 is merged, it is possible to move on to this.

**Comment by lextm** [comment]
Closed by #92.
