### ISSUE TITLE
Wrong settings key for the linter executable in error message

### ISSUE THREAD

**Issue by yuki-p** [vscode-restructuredtext/vscode-restructuredtext#55]
The following error message "Cannot lint /Users/admin/papervoucher_revised/index.rst. The executable was not found. Use the 'restructuredtext.executablePath' setting to configure the location of the executable" (see attached screenshot)

![screen shot 2017-07-24 at 12 05 09](https://user-images.githubusercontent.com/30065536/28508982-14d23c1a-7069-11e7-9a8d-f48eb6dfaecb.png)

The key for the settings has a typo, it says `restructuredtext.executablePath` instead of `restructuredtext.linter.executablePath`.

**Comment by lextm** [comment]
Fixed in release 35.0.0.
