### ISSUE TITLE
[Feature request] Display preformatted text in dedicated color

### ISSUE THREAD

**Issue by rnixx** [vscode-restructuredtext/vscode-restructuredtext#58]
Hi,

it would be great if preformatted sections gets displayed in a different color. The color may be the same for general code samples starting with ``::`` or dedicated language samples starting with ``.. code-block:: python`` for example.

If it further would be possible to syntax highlight language dedicated code samples the way sphinx does this would be perfect - but i suppose this implies a lot of work...

Thanks for this plugin 👍

**Comment by lextm** [comment]
In release 154.0.0 the old grammar file was replaced by the one from https://github.com/trond-snekvik/vscode-rst .

Close this item now as it does not appear with that grammar file.
