### ISSUE TITLE
Theme not being applied in preview

### ISSUE THREAD

**Issue by rtgoodwin** [vscode-restructuredtext/vscode-restructuredtext#67]
Please follow [the troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 38
- [x] Visual Studio Code version: 1.17.2
- [x] Operating System version: macOS High Sierra 
- [x] Python version: 2.17.3
- [x] sphinx version:Sphinx (sphinx-build) 1.5.6
- [x] A sample of conf.py or its important fragments:
`if sphinx_rtd_theme:
    html_theme = 'sphinx_rtd_theme'
else:
    html_theme = 'default'`
**Expected behavior**
Preview renders with RTD theme. Was working for weeks, just seemed to change last week. AFAICT the only change was a VSCode update. 

**Actual behavior**
Renders with default theme. But "make html" in the doc dir renders in the RTD theme.

**Detailed Steps to reproduce the problem**
Clone a repo using RTD theme as above, and use the extension to Preview-Right pane.

**Comment by rtgoodwin** [comment]
Another note: if I "make html", and then use the extension to preview a file, that single previewed file  (as opened from the output build directory) ends up using the default theme even though the rest of the document structure is in the right theme. So something is happening during preview generation.

**Comment by rtgoodwin** [comment]
Ok, this could be my issue...when trying to `cd ${workspaceRoot}` in the terminal it was sending me to `~`. So I guess somehow the build was working even if it wasn't finding the `conf` file? Re-opening my virtualenv folder in VSCode seems to have fixed it. Maybe an opportunity for better error logging?

**Comment by rtgoodwin** [comment]
Honestly I'm not sure, I don't know Sphinx well enough to know if there is
some kind of verbose logging that can be turned on. I'm also not sure how
it was finding the replace directives in the conf.py but not the theme. If
we knew that, maybe the logging could be decided?

At the very least also maybe this could go in the troubleshooting guide,
like ways to figure out if your workspace root is off or something?

**Comment by lextm** [comment]
The workspace root part is feasible. I will see how to quickly provide an update.

The theme/directive related parts are also a misery I am trying to understand (though I have been maintaining this extension for long), so let's keep an eye on it and hope a way can be found some time in the future.

**Comment by lextm** [comment]
Release 39.0 and above has three more logging entries generated (for `$(workspaceRoot)`, `confPath`, and `builtDocumentationPath`. I hope temporarily that would be enough for troubleshooting.

Close this item now and we might reopen it or create new items if new issues happen.
