### ISSUE TITLE
restructuredtext.confPath setting dosen't work on Windows

### ISSUE THREAD

**Issue by zzqcn** [vscode-restructuredtext/vscode-restructuredtext#69]
My code directory is D:\dev\hds, and restructuredText doc is in subdirecory D:\dev\hds\doc. I open D:\dev\hds with VSCode, and make settings in D:\dev\hds\.vscode\detting.json as follows:

``` json
    "restructuredtext.builtDocumentationPath" : "${workspaceRoot}/doc/_build/html",
    "restructuredtext.confPath"               : "${workspaceRoot}/doc",
    "restructuredtext.updateOnTextChanged"    : "true",
    "restructuredtext.sphinxBuildPath"        : "C:\\Python27\\Scripts\\sphinx-build.exe"
```

Then I try to preview a rest file but error occured. The output messages as follows:

```
$(workspaceRoot): d:\dev\hds
confPath: d:\dev\hds
builtDocumentationPath: d:\dev\hds/doc/_build/html
Source file: d:\dev\hds\doc\prog_guide\flow.rst.rendered
Compiler: C:\Python27\Scripts\sphinx-build.exe -b html . "d:\dev\hds/doc/_build/html"
HTML file: d:\dev\hds\doc\_build\html\doc\prog_guide\flow.html
Error: Error
Command failed: C:\Python27\Scripts\sphinx-build.exe -b html . "d:\dev\hds/doc/_build/html"
Error: Config directory doesn't contain a conf.py file.

Error: Command failed: C:\Python27\Scripts\sphinx-build.exe -b html . "d:\dev\hds/doc/_build/html"
Error: Config directory doesn't contain a conf.py file.

	at ChildProcess.exithandler (child_process.js:217:12)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error: Config directory doesn't contain a conf.py file.
```

Line 2 shows that confPath is ${workspaceRoot}, i.e. D:\dev\hds, so I doubt restructuredtext.confPath didn't work, the sphinx-build still treats the root directory `.` as the source direcory.

PS: My another project (docs only) which has conf.py in root direcory works well in same environment.

**Environment**
- [ ] Extension version: 40.0.0
- [ ] Visual Studio Code version: 1.17.2
- [ ] Operating System version: Windows10 Home (10.0.14393)
- [ ] Python version: 2.7.14
- [ ] sphinx version: 1.6.5
- [ ] A sample of conf.py or its important fragments: None

**Comment by zzqcn** [comment]
I check source code and  find  line 33 in commit 81578b1 may be a mistake: 
```
 -        this._input = RstDocumentContentProvider.loadSetting("confPath", root);
 +        this._input = RstDocumentContentProvider.loadSetting("confconfPathPath", root);
```

It may be a typing error.

**Comment by zzqcn** [comment]
I changed "confconfPathPath" to "confPath" in line 33 in /src/features/rstDocumentContent.ts, and re-build & re-install it, then this issue resolved.

**Comment by lextm** [comment]
Thanks for the report. Release 41.0 contains the fix.

**Comment by aytekinar** [comment]
Hey

I am running
```
> code --version
1.20.0
c63189deaa8e620f650cc28792b8f5f3363f2c5b
x64
```
with `reStructuredText 49.0.0` and I have the following settings:
```
{
  // reStructuredText Settings
  "restructuredtext.builtDocumentationPath": "${workspaceRoot}/docs/_build/html",
  "restructuredtext.confPath": "${workspaceRoot}/docs",
  "restructuredtext.updateOnTextChanged": "false"
}
```
When I try to render the `.rst` file, I get the following:
```
$(workspaceRoot): /home/aytekin/Documents/My_Gits/Research/policy-based-design
confPath: /home/aytekin/Documents/My_Gits/Research/policy-based-design
builtDocumentationPath: /home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/_build/html
Source file: /home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/index.rst.rendered
Compiler: python -m sphinx -b html . "/home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/_build/html"
HTML file: /home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/_build/html/docs/index.html
Error: Error
Command failed: python -m sphinx -b html . "/home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/_build/html"
Error: Config directory doesn't contain a conf.py file.

Error: Command failed: python -m sphinx -b html . "/home/aytekin/Documents/My_Gits/Research/policy-based-design/docs/_build/html"
Error: Config directory doesn't contain a conf.py file.

	at ChildProcess.exithandler (child_process.js:217:12)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error: Config directory doesn't contain a conf.py file.
```
`confPath` does not seem to respect my user settings :(

**Comment by lextm** [comment]
@aytekinar on which OS?

**Comment by aytekinar** [comment]
Arch Linux,
```
> uname -a
Linux KTH-5435 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux
```

**Comment by lextm** [comment]
@aytekinar I think you didn't put the `settings.json` file in the right place. I tested on a Debian machine and I could not reproduce the issue.

Besides, don't post such under a closed issue. You can see that yours has nothing to do with the initial discussion.

**Comment by aytekinar** [comment]
> @aytekinar I think you didn't put the `settings.json` file in the right place. I tested on a Debian machine and I could not reproduce the issue.

Actually, I just added the aforementioned settings excerpt under my user settings in VSCode. Then, it seems that the corresponding part, *i.e.*, `"restructuredtext.confPath": "/home/aytekin/Documents/My_Gits/Research/policy-based-design/docs"`, seems to have been pasted under my `.vscode/settings.json` file in the project folder.

On a different machine, with the same configuration, I don't seem to have any problems. I will try to dig deep in the other machine to see what's wrong.

Thanks anyways, for the support.

> Besides, don't post such under a closed issue. You can see that yours has nothing to do with the initial discussion.

It does not have to do anything with Windows, but I think it does have something regarding the plugin not obeying the user settings. That's why I didn't want to create yet another issue, but just kept posting here. If the error persists in the other machine, and if I cannot get around with it, I will open a new issue this time.

Best,
