### ISSUE TITLE
restructuredtext.linter.executablePath Is Ignored if python.pythonPath Is Set

### ISSUE THREAD

**Issue by tagatac** [vscode-restructuredtext/vscode-restructuredtext#71]
**Environment**
- [ ] Extension version: 43.0.0
- [ ] Visual Studio Code version: 1.18.1
- [ ] Operating System version: Mac OS 10.13.1
- [ ] Python version: 2.7.14
- [ ] sphinx version: 1.3.6

**Expected behavior**
If `restructuredtext.linter.executablePath` is set, `restructuredtext` ignores `python.pythonPath`.

**Actual behavior**
If `python.pythonPath` is set, `restructuredtext` ignores `restructuredtext.linter.executablePath`.

**Detailed Steps to reproduce the problem**
1. Set `python.pythonPath` to an invalid value and `restructuredtext.linter.executablePath` to a valid value.
1. Open a .rst file.
1. `restructuredtext` gives an error because it's trying to find Python at `python.pythonPath`.

**Comment by lextm** [comment]
This is by design.

**Comment by lextm** [comment]
Related to #72 . Just noticed that virtualenv requires the path detection priority to be reversed.

Please try to use 45.0.0.
