### ISSUE TITLE
linter.executablePath does not work as expected - no support for virtualenv

### ISSUE THREAD

**Issue by schlamar** [vscode-restructuredtext/vscode-restructuredtext#72]
**Environment**

- Extension version: 44.0.0
- Visual Studio Code version: 1.19.0
- Operating System version: Windows 7
- Python version: 2.7
- sphinx version: not relevant
- A sample of conf.py or its important fragments: not relevant

**Expected behavior**

Linting works when pointing linter.executablePath to the rst-lint.exe in a virtualenv.

**Actual behavior**

Linting does not work. Instead of using the specified rst-lint.exe, the extension tries to import `restructuredtext_lint` with the default Python. (C:\Python27\python.exe: No module named restructuredtext_lint)

**Detailed Steps to reproduce the problem**

* Set default Python path to C:\Python27\python.exe
* Install `restructuredtext_lint` in a virtualenv
* Point`linter.executablePath` to the rst-lint.exe in the virtualenv directory

**Comment by lextm** [comment]
Just published a new release 45.0.0.

It would prefer `linter.executablePath` to default Python path (reverse of what 44.0.0 does).

Please upgrade and let me know if that works better for virtualenv.

**Comment by schlamar** [comment]
Yes, 45.0.0 works for me. 👍 

Thank you for the very fast fix :)
