### ISSUE TITLE
httpdomain directives in sphinxDirectives are ignored

### ISSUE THREAD

**Issue by schlamar** [vscode-restructuredtext/vscode-restructuredtext#74]
httpdomain directives (e.g. `http:get`) in sphinxDirectives are ignored because your [regular expression](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/8b42650554343fefd0db166881e2084ae05eefae/src/features/rstLinter.ts#L68) doesn't support colons in directives.

**Comment by lextm** [comment]
Pull request is welcome.

**Comment by lextm** [comment]
Fixed via #75 . Shipped in release 46.0.0. Thanks.
