### ISSUE TITLE
Investigation on table generator

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#76]
[ReSTinPeace](http://kib2.free.fr/reSTinPeace/) has a dialog based generator for tables.

**Comment by PaulWen** [comment]
I just had a look at the [RST extension for Sublime](https://github.com/mgaitan/sublime-rst-completion#magic-tables). In my opinion, they support tables in a pretty good way. I like especially that it is always possible to reformat the table via a keyboard shortcut.

**Comment by lextm** [comment]
@PaulWen reStructuredText ecosystem is based on Python, a language I am not familiar with. It would take a long time for this extension to catch up.

**Comment by acsr** [comment]
@PaulWen I suggest you to take a look at the .. csv-table:: ReST directive at http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4

code looks like

```
.. csv-table:: Title
   :header: "Header", "Header"
   :widths: 50, 50

    "Data", "Data" 
    "Data", "Data"
```
and even can load the csv data from external files.

It took me some time to discover that.

Drawback is the lesser readability in source code text form for simple tables. That changes with long cells very fast if you do not switch word wrap.
You can convert this to classic ReST tables e.g. using the "make text" command and grab it off there.

**Comment by Nadano** [comment]
This extension works ok, although it has some bugs for rst while resizing the cells:

https://github.com/shuGH/vscode-table-formatter

Sadly it seems abandonend
