### ISSUE TITLE
.txt files having rst in first line do not activate the extension

### ISSUE THREAD

**Issue by rpuntaie** [vscode-restructuredtext/vscode-restructuredtext#78]
version 49.0.0

If in the first line of the current buffer there is ``\.\..* rst``
the text should be colored according rst, even if the extension is `.txt`.

**Comment by lextm** [comment]
You can switch language to reStructuredText manually by clicking the language area in the right bottom corner. No plan to handle `.txt` file extension, as most source files should end with `.rst` or `.rest`.
