### ISSUE TITLE
extension modifies .vscode/settings.json in non-portable way

### ISSUE THREAD

**Issue by BlackZork** [vscode-restructuredtext/vscode-restructuredtext#80]
Please follow [the troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 50.0.0
- [x] Visual Studio Code version: code-oss build on arch linux
- [x] Python version: 3.6.x (venv)
- [x] sphinx version: 1.6.6

My myproject/.vscode/settings.json (working directory):
"restructuredtext.builtDocumentationPath": "${workspaceRoot}/docs/build",
"restructuredtext.confPath": "${workspaceRoot}/docs/source",
"python.pythonPath": "${workspaceRoot}/app/venv/bin/python",

**Actual behavior**
1. I do "hg clone" of my project
2. Open first rst file in VSCode
3. After that one line is added to my myproject/.vscode/settings.json:
    **"restructuredtext.workspaceRoot": "/home/user/sources/myproject"**
    *this path is wrong, my rst files and conf.py are in myproject/docs/sources subdirectory*
4. I change this line to: **"$(workspaceRoot}"** or **"$(workspaceRoot}/docs/sources"**
5. I reopen VSCode and "restructuredtext.workspaceRoot" is set back to "/home/user/sources/myproject"

Now everyone working on myproject have to revert myproject/.vscode/settings.json after opening first rst file in VSCode to prevent commiting unwanted changes.

**Expected behavior**
Do not touch .vscode/settings.json when opening rst file.

**Comment by BlackZork** [comment]
If this is an extension private data then it should be kept in a file that could be excluded from source control.

**Comment by Yajo** [comment]
There's something I don't understand...

> restructuretext.workspaceRoot is a write-only setting [...] there should be no side effect on another machine (as the extension would write to it only).

So, basically, the setting does nothing and is completely useless. OK, every project has its bugs...

> This is by design right now.

So, polluting your git history with a completely useless setting is considered a "feature"...

> ![captura de pantalla de 2018-02-26 11-13-23](https://user-images.githubusercontent.com/973709/36667537-1a8b0f9c-1ae6-11e8-8a1a-1be2539cdbd8.png)

So do you mean that, since that is a feature, it will never get fixed?

Sorry but I cannot understand your standpoint, could you elaborate please? I must be missing something... :confused:

**Comment by lextm** [comment]
@Yajo The language server and the extension requires a way to share the workspace root, which can be quite simple to achieve by using the configuration item. The observed behavior is the side effect of that part. So it is definitely part of a "feature", just you don't realize yet.

In 51.0.0 release, I slightly changed the code to avoid writing to configuration file if IntelliSense is not enabled. But if you do enable IntelliSense, then this side effect will remain. No plan to fix it at this moment.

**Comment by BlackZork** [comment]
This behaviour forces me to revert settings file every time I commit changes. It would be ok if extension will preserve existing value as:

"restructuredtext.workspaceRoot": "${workspaceFolder}"

and do not change it to 

"restructuredtext.workspaceRoot": "/home/zork/sources/myproject"

every time an rst file is opened.

**Comment by Yajo** [comment]
That would be a good intermediate solution indeed. The other one is to uninstall the extension, of course, but that's a bit radical and I really like it :thinking: 

The scenario @lextm describes seems more in the shape of a temporary file. Couldn't you use just that?

I mean... I have lots of languages support in my system, and this one is the only one that does this, so there definitely must be a better way to do it.

**Comment by lextm** [comment]
@Yajo I finally had some time to dig into LSP further to resolve it.
