### ISSUE TITLE
Had to create 'conf.py' and 'contents.rst' in my project folder to use preview

### ISSUE THREAD

**Issue by garytyler** [vscode-restructuredtext/vscode-restructuredtext#81]
It looks like I will have to manually create multiple files (conf.py and content.rst) in my project directory to render a preview. Is this accurate? If not, the documentation could use an update.

**Environment**
- [ ] Extension version: 48.0.0
- [ ] Visual Studio Code version: 1.2
- [ ] Operating System version: Windows 10
- [ ] Python version: 3.6
- [ ] sphinx version: 1.7.1
- [ ] A sample of conf.py or its important fragments: None

**Expected behavior**
Renders a preview

**Actual behavior**
Log errors:

master file c:\projectfolder not found

and

Command failed: py -m sphinx -b html . "c:\projectfolder\_build\html"

**Detailed Steps to reproduce the problem**

Install extension, follow previously-unannounced instructions to install python packages, try to use extension to display a preview

**Comment by lextm** [comment]
You need to show your directory structure. A typical sphinx project (https://github.com/lextudio/linpeiman) only needs a single `conf.py`.

If you are not familiar with sphinx yet, please spend some time on that before using this extension.

**Comment by garytyler** [comment]
Alright. I will just view .rst another way for now. Thanks.

**Comment by lextm** [comment]
Related to #61
