### ISSUE TITLE
Warnings D002 and D004 at every single line

### ISSUE THREAD

**Issue by lgarcin** [vscode-restructuredtext/vscode-restructuredtext#84]
Please follow [the troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 57.0.0
- [x] Visual Studio Code version: 1.21.1
- [x] Operating System version: Windows 10
- [x] Python version: 3.6
- [x] sphinx version: 1.6.7
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
No warnings.

**Actual behavior**
I get these two warnings at every line of rST document
'D002 Trailing whitespace'
'D004 Found literal carriage return'
I still get these warnings even after trimming whitespaces in VSCode 

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
Similar to #83 you need to pass extra arguments to `doc8` to suppress the two warnings.

My investigation shows that `doc8` seems to assume all line endings should be `\n`, not `\r\n`, so it keeps reporting the two issues for Windows based files.

Need to report to `doc8` developers as only they can fix it.

**Comment by lextm** [comment]
Reported back to doc8 developers,

https://bugs.launchpad.net/doc8/+bug/1756704

Wait for their responses.

**Comment by mloskot** [comment]
@lextm I confirm your finding about `\r\n` not being kosher for `doc8`. Thanks for reporting it upstream.

**Comment by tormiss** [comment]
Temporary workaround is to ignore these two rules with custom VSCode config:
```
{
    "restructuredtext.linter.extraArgs": [
        "--ignore D002",
        "--ignore D004"
    ]
}
```

**Comment by lextm** [comment]
Please report to doc8 developers if you want this issue to be fixed ultimately,

https://bugs.launchpad.net/doc8/+bug/1756704/+affectsmetoo

**Comment by lextm** [comment]
Close it now as there isn't much to do in this extension.

**Comment by Ryonez** [comment]
Defiantly a faq candidate, I checked there before ending up here.

**Comment by edurojasr** [comment]
> 
> 
> A temporary workaround is to ignore these two rules with custom VSCode config:
> 
> ```
> {
>     "restructuredtext.linter.extraArgs": [
>         "--ignore D002",
>         "--ignore D004"
>     ]
> }
> ```
Maybe can be added in the README file?

**Comment by edurojasr** [comment]
The **D004 Found literal carriage return** can be "fixed" changing the *End of line sequence* in VS Code just select LF instead of CRLF

**Comment by myidealab** [comment]
> 
> 
> A temporary workaround is to ignore these two rules with custom VSCode config:
> 
> ```
> {
>     "restructuredtext.linter.extraArgs": [
>         "--ignore D002",
>         "--ignore D004"
>     ]
> }
> ```

Would you be able to provide an additional description of where I enter this argument? I attempted to put this code in the settings.json file for Visual Code, but that may not be the correct location.

Steps:
1. Command Palette...
2. Preferences: Configure Language Specific Settings
3. reStructuredText
4. At bottom, json key automatically generated: `"[restructuredtext]": {  }
5. The above code was added.

**Comment by myidealab** [comment]
> 
> 
> A temporary workaround is to ignore these two rules with custom VSCode config:
> 
> ```
> {
>     "restructuredtext.linter.extraArgs": [
>         "--ignore D002",
>         "--ignore D004"
>     ]
> }
> ```

For those who may be unfamiliar with configuring Visual Studio Code (Windows):
1. File
2. Preferences
3. Settings
4. Extensions (drop-down)
5. reStructuredText
6. In the Conflicting Extensions section, click on the link "Edit in settings.json"
7. Enter the json key:value provided by @tormiss

**Comment by bilderbuchi** [comment]
I think the doc8 project has moved to https://github.com/PyCQA/doc8, so you'll probably have to report there.

**Comment by lextm** [comment]
@bilderbuchi That still seems to be a dead repo, https://github.com/PyCQA/doc8/issues/23 As long as no more release to PyPI is made, reporting it to nowhere can help.

**Comment by MS44neuro** [comment]
> > A temporary workaround is to ignore these two rules with custom VSCode config:
> > ```
> > {
> >     "restructuredtext.linter.extraArgs": [
> >         "--ignore D002",
> >         "--ignore D004"
> >     ]
> > }
> > ```
> 
> For those who may be unfamiliar with configuring Visual Studio Code (Windows):
> 
> 1. File
> 2. Preferences
> 3. Settings
> 4. Extensions (drop-down)
> 5. reStructuredText
> 6. In the Conflicting Extensions section, click on the link "Edit in settings.json"
> 7. Enter the json key:value provided by @tormiss

Getting this error with doc8: This setting is obsolete. Please refer to https://docs.restructuredtext.net/articles/configuration.html#linter.
but this worked: "restructuredtext.linter.doc8.extraArgs": [ "--ignore D002", "--ignore D004"]

**Comment by jfthuong** [comment]
As mentioned by MS44neuro, the following settings works nicely:

```json
    "restructuredtext.linter.doc8.extraArgs": [
        "--ignore D002",
        "--ignore D004"
    ]
```
