### ISSUE TITLE
Unnecessary if branch

### ISSUE THREAD

**Issue by glmdgrielson** [vscode-restructuredtext/vscode-restructuredtext#89]
https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/09e406116027d64afa3aca321f096081ca66a1f6/src/rstLsp/extension.ts#L23-L33

Why is this here? The condition will always be true. I think it was supposed to be:
```ts
let serverModule: string = null; 
for (let p of languageServerPaths) { 
	p = context.asAbsolutePath(p); 
	// console.log(p); 
	if (fs.existsSync(p)) { 
		serverModule = p; 
		break; 
	} 
} 
```

**Comment by lextm** [comment]
You can send a pull request.
