### ISSUE TITLE
Preview not working: syntax error and newlines displayed literally

### ISSUE THREAD

**Issue by mcavigelli** [vscode-restructuredtext/vscode-restructuredtext#9]
Hello

When trying to preview a rst document (1),
I get a Python error. The parentheses are missing. The script broke with fixing #8.
When changing file preview.py from
  `print html_document.encode('utf8')`
to
  `print (html_document.encode('utf8'))`
the html preview works again.

However all the newlines in the reStructuredText document are translated to \n in the output.
![tomanynewlines](https://cloud.githubusercontent.com/assets/829336/14234468/c9178732-f9e3-11e5-9aaa-6035c51b8d3b.PNG)

Thanks for your extension, Matthias

(1) https://github.com/divio/django-cms/blob/master/docs/contributing/code.rst

**Comment by lextm** [comment]
Thanks very much for this tip, but I am currently working on a very different approach which is going to give you a live preview with almost all cool features you want. So stay tuned.
