### ISSUE TITLE
Add configuration option to automatically find conf.py for "most people"

### ISSUE THREAD

**Issue by TormodLandet** [vscode-restructuredtext/vscode-restructuredtext#91]
It may not work for everyone, but I assume more than 90% of people will have `conf.py` in the same directory or a parent directory of where the `*.rst` file being edited is located? I may be wrong, but this is what Sphinx creates by default.

A new configuration option could be introduced, `restructuredtext.confInSameOrParentDir`. It would turn on a feature that walks the current and parent directories to find `conf.py`. This may not work in every situation, but I think it would help most people? Only those with non-standard directory layouts will then have to configure the path to `conf.py`, which is OK if you are going outside "the norm".

This is related to issue #59, but there the requester wants to figure out the path to `_build/html` by parsing the conf.py file, which is a second step after locating the file, and also much harder since you can have arbitrary Python code in `conf.py` (though, most people do not).

**Comment by lextm** [comment]
Related to #10.

Ideally there should be a selector similar to what C# extension offers.

I don't plan to accept the pull request at this moment, as it does not cover enough scenarios. A thorough approach would be preferred.

**Comment by TormodLandet** [comment]
What would be an acceptable solution? Give the user a choice of all directories containing a conf.py file found in the workspace? It should be quite fast to look them up as long as there is no massive directory structures. Should the users choice be saved on a per file or per workspace basis or should the menu to select come up every time there is a preview refresh?

I still think searching up from the current directory should be included as a way to find conf.py in case a single file is opened without a project / workspace / directory.

**Comment by TormodLandet** [comment]
Thanks for the C# extension pointer. I updated the pull request using that code as a template for how to search the workspace for files and how to prompt the user if more than one file is found.

**Comment by TormodLandet** [comment]
Closed by pull request #92
