### ISSUE TITLE
Support for workspace folders

### ISSUE THREAD

**Issue by ytimenkov** [vscode-restructuredtext/vscode-restructuredtext#95]
reStructuredText version 65.0.0
Python extension 2018.6.0
VSCode: 1.25.1 (Windows-x64)

I have python with sphinx in virtual env and it's automatically discovered by Python extension (I suppose) and it provides path to Python.

This path is `${workspaceFolder}\env\Scripts\python.exe` which seems to be treated literally by reStructuredText extension without substituting `${workspaceFolder}`, and I get error message:

```
Command failed: ${workspaceFolder}\env\Scripts\python.exe -m sphinx -b html .
"c:\Users\Me\Source\conan\docs/_build/html" The system cannot find the path specified.
```

(Most of my settings are default).

**Comment by lextm** [comment]
Related to #52 . 

"Open Workspace" is not supported yet. Pull requests are welcome.

**Comment by lextm** [comment]
Please upgrade to release 67.0.0 and report back other issues you meet.

I just finished some initial testing, and #92 seems to have resolved the problem you reported.
