### ISSUE TITLE
Code snippets crash the Extension host

### ISSUE THREAD

**Issue by albireox** [vscode-restructuredtext/vscode-restructuredtext#96]
**Environment**
- [X] Extension version: 65.0.0
- [X] Visual Studio Code version: 1.26.0-insiders
- [X] Operating System version: macOS 10.14
- [X] Python version: 3.7.0
- [X] sphinx version: 1.7.5
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
Working extension.

**Actual behavior**
I'm not sure if this is a problem with `vscode-restructuredtext` or an upstream change in `vscode-insiders`, but since yesterday using the restructuredtext extension crashes the Extension host as soon as you open a rst file.

The crash seems to be related to the contents of the file. Some files won't crash the host, but others will do immediately.

**Detailed Steps to reproduce the problem**

Use the latest vscode-insiders version. Open the attached file. The extension host should crash. I've tried to identify what part of the code is actually triggering the issue but  it doesn't seem to be very consistent.

[galaxy_tools.rst.zip](https://github.com/vscode-restructuredtext/vscode-restructuredtext/files/2233309/galaxy_tools.rst.zip)

**Comment by lextm** [comment]
Thanks. I will take a look when I have time. Personally I saw similar stability issues in recent VSCode build.

**Comment by albireox** [comment]
In case it's useful, it seems setting the linter to run only on save fixes the problem (and the linter still works).

**Comment by lextm** [comment]
Temporarily close it.
